
#
# Makefile for the memory technology device drivers.
#
# Core functionality.

ifeq ($(strip $(llt_gcov)),y)
GCOV_PROFILE := y
endif

obj-y				+= dump_exc_table.o 



GCOV_PROFILE := y
GCOV_PROFILE_dump_exc_table.o := n