ccflags-y += -I$(srctree)/platform_source/basicplatform/drivers/mntn/blackbox \
             -I$(srctree)/platform_source/cee/drivers/ddrc \
             -Wall -Werror

obj-$(CONFIG_DDR_TEST) += ddr_rw_test.o
