LINUXINCLUDE += -I$(srctree)/platform_source/basicplatform/drivers/sdcu
LINUXINCLUDE += -I$(srctree)/platform_source/basicplatform/drivers/sdcu/test
LINUXINCLUDE += -I$(srctree)/drivers/block/zram

obj-$(CONFIG_MM_SDCU) += sdcu_cmdlist.o sdcu_support.o
obj-$(CONFIG_MM_SDCU_TEST) += test/
obj-$(CONFIG_CRYPTO_SDCU) += sdcu_alg.o
