
#
# Makefile for the memory technology device drivers.
#
# Core functionality.

ifeq ($(strip $(llt_gcov)),y)
GCOV_PROFILE := y
endif

obj-y				+= dump_agent.o 
obj-y				+= dump_eproc.o


GCOV_PROFILE := y