EXTRA_CFLAGS += -I$(FPD_DIR)/
EXTRA_CFLAGS += -I$(FKD_DIR)/
EXTRA_CFLAGS += -I$(FKD_DIR)/core
EXTRA_CFLAGS += -I$(UNIFORM_ID_DIR)/
EXTRA_CFLAGS += -I$(srctree)/drivers/platform_drivers/ap/platform/$(FFTS_CHIP_PLATFORM_DIR)

obj-y += fpd.o

fpd-objs := ffts_hw_config.o fpd_main.o ffts_resmem.o ffts_platform_pm.o