EXTRA_CFLAGS += -I$(srctree)/platform_source/camera/drivers/media/native/camera/
EXTRA_CFLAGS += -I$(srctree)/platform_source/camera/drivers/media/native/camera/cam_star_module/
EXTRA_CFLAGS += -I$(srctree)/platform_source/camera/drivers/media/native/camera/cam_star_module/stm32g031/
EXTRA_CFLAGS += -fno-pic

obj-$(CONFIG_KERNEL_CAMERA_SENSORMOTOR) += stm32g031.o
obj-$(CONFIG_KERNEL_CAMERA_SENSORMOTOR) += stm32g031_fw.o
