# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the phy drivers.
#

ccflags-y += -Wdate-time -Wextra -Wfloat-equal -Wformat=2 -Wshadow
obj-y += hisilicon/
obj-$(CONFIG_PHY_HISI_USB2_T5) += chip-usb2-phy-t5.o
obj-$(CONFIG_PHY_HISI_USB3_LITE) += chip_usb3_lite_phy.o
