ccflags-y += -I$(srctree)/drivers/huawei_platform/sensor/ext_inputhub/default/
ccflags-y += -I$(srctree)/drivers/huawei_platform/sensor/ext_inputhub/default/bus_driver/

obj-$(CONFIG_EXT_INPUTHUB) += spi_commu.o
obj-$(CONFIG_EXT_INPUTHUB) += uart_commu.o
obj-$(CONFIG_EXT_INPUTHUB) += sdio_commu.o
obj-$(CONFIG_EXT_INPUTHUB) += spi_slave_commu.o
