#ifndef __LPMCU_DIAGINFO_MAP
#define __LPMCU_DIAGINFO_MAP(x,y,z) 
#endif
#include <bbox_diaginfo_id_def.h>
__LPMCU_DIAGINFO_MAP(LPM3_DDR_FAIl, 3, "PLL lock fail:")
__LPMCU_DIAGINFO_MAP(LPM3_DDR_PA_SENSOR, 6, "PASENSOR:")
__LPMCU_DIAGINFO_MAP(LPM3_DDR_TRAINING, 6, "TRAINING:")
__LPMCU_DIAGINFO_MAP(ACPU_LIT_AVS_VAL, 6, "CPU_LIT_AVS:")
__LPMCU_DIAGINFO_MAP(ACPU_MID_AVS_VAL, 6, "CPU_MID_AVS:")
__LPMCU_DIAGINFO_MAP(ACPU_BIG_AVS_VAL, 6, "CPU_BIG_AVS:")
__LPMCU_DIAGINFO_MAP(ACPU_L3_AVS_VAL, 6, "CPU_L3_AVS:")
__LPMCU_DIAGINFO_MAP(LPM3_PERI_PA_SENSOR, 5, "PERI_PASENSOR:")
__LPMCU_DIAGINFO_MAP(LOWPOWER_GPU_AVS_VAL, 6, "GPU_AVS:")
__LPMCU_DIAGINFO_MAP(MSPC_DIAG_INFO, 1, "CRYPTO_CORE:")
