#ifndef __DDR_PLATFORM_AUTOFSGT_H__
#define __DDR_PLATFORM_AUTOFSGT_H__ 
enum ddr_dmc_autofsgt_mode {
 DMC_EXT_AUTOFSGT_ALL_BYPASS,
 DMC_EXT_AUTOFSGT_DDRPHY_EN,
 DMC_EXT_AUTOFSGT_DDRCCRG_EN,
 DMC_EXT_AUTOFSGT_CRGPERI_EN,
};
typedef enum {
 DDR_AUTOFSGT_ENABLE = 1,
 DDR_AUTOFSGT_DISABLE,
 DDR_AUTOFSGT_LOGIC_EN,
 DDR_AUTOFSGT_LOGIC_DIS
} DDR_AUTOFSGT_CMD_ID;
typedef enum {
 DDR_AUTOFSGT_BIT_LPMCU = 0,
 DDR_AUTOFSGT_BIT_LPMCU_NMI,
 DDR_AUTOFSGT_BIT_BL2,
 DDR_AUTOFSGT_BIT_FASTBOOT,
 DDR_AUTOFSGT_BIT_BL31,
 DDR_AUTOFSGT_BIT_SECURE_OS,
 DDR_AUTOFSGT_BIT_SENSORHUB,
 DDR_AUTOFSGT_BIT_KERNEL,
 DDR_AUTOFSGT_BIT_CPUXPU,
 DDR_AUTOFSGT_BIT_GPUXPU,
 DDR_AUTOFSGT_BIT_DDRXPU,
 DDR_AUTOFSGT_BIT_TZSP,
 DDR_AUTOFSGT_BIT_MAX
} DDR_AUTOFSGT_PROXY_CLIENT_ID;
#endif
