#ifndef __DDR_VOTE_STATISTIC_STRUCT_H__
#define __DDR_VOTE_STATISTIC_STRUCT_H__ 
#include <ddr_define.h>
enum sw_vote_stat_ip {
 LIT_CLUSTER_ID = 0x80,
 BIG_CLUSTER_ID = 0x81,
 GPU_ID = 0x82,
 IOMCU_ID = 0x83,
 MODEM_ID = 0x84,
 TEMPERTURE_ID = 0x85,
 MID_CLUSTER_ID = 0x86,
 L3_CLUSTER_ID = 0x87,
 MODEM_5G_ID = 0x88
};
enum hw_vote_stat_ip {
 FLOOR_VOTE_HW_AP_ID = 0x0,
 FLOOR_VOTE_HW_HIFI_ID = 0x1,
 FLOOR_VOTE_HW_IOMCU_ID = 0x2,
 FLOOR_VOTE_HW_LIT_LAT_ID = 0x3,
 FLOOR_VOTE_HW_BIG_LAT_ID = 0x4,
 FLOOR_VOTE_HW_MID_LAT_ID = 0x5,
 FLOOR_VOTE_HW_LATSTAT_ID = 0x6,
 FLOOR_VOTE_HW_MODEM_ID = 0x7,
 FLOOR_VOTE_HW_CPU_XPU_ID = 0x8,
 FLOOR_VOTE_HW_GPU_XPU_ID = 0x9,
 FLOOR_VOTE_HW_RESERVED11_ID = 0xa,
 FLOOR_VOTE_HW_RESERVED12_ID = 0xb,
 FLOOR_VOTE_HW_RESERVED13_ID = 0xc,
 FLOOR_VOTE_HW_RESERVED14_ID = 0xd,
 FLOOR_VOTE_HW_DSS_ID = 0xe
};
enum DDR_LP_STATISTIC_ID {
 DDR_PD_RANK0_CNT = 0,
 DDR_PD_RANK1_CNT,
 DDR_ACT_PD_RANK0_CNT,
 DDR_ACT_PD_RANK1_CNT,
 DDR_ACT_NPD_RANK0_CNT,
 DDR_ACT_NPD_RANK1_CNT,
 DDR_ASREF_RANK0_CNT,
 DDR_ASREF_RANK1_CNT,
 DDR_LP_STATISTIC_CNT_MAX,
 DDR_PD_RANK0_NUM = DDR_LP_STATISTIC_CNT_MAX,
 DDR_PD_RANK1_NUM,
 DDR_ASREF_RANK0_NUM,
 DDR_ASREF_RANK1_NUM,
 DDR_LP_NUM,
 DDR_LP_STATISTIC_MAX
};
struct ddr_freq_stat {
 unsigned int readable;
 unsigned int freq_num;
 unsigned int stat_ms[LPMCU_FREQ_NUM_MAX];
};
#endif
