obj-$(CONFIG_EL3_PA_TEST) += el3_pa_test.o
obj-$(CONFIG_BTI_TEST) += bti_test.o
obj-$(CONFIG_BTI_TEST) += bti_testcase.o
obj-$(CONFIG_PAC_TEST) += pac_test.o
obj-$(CONFIG_PAC_TEST) += pac_testcase.o
obj-$(CONFIG_FAC_TEST) += fac_test.o

subdir-ccflags-y += -Wdate-time -Wextra -Wfloat-equal -Wformat=2 -Wshadow
