ccflags-y += -I$(srctree)/include/linux
ccflags-y += -I$(srctree)/drivers/dma-buf/heaps
ccflags-y += -I$(srctree)/platform_source/basicplatform/drivers/dma-buf/heaps
ccflags-y += -I$(srctree)/platform_source/basicplatform/drivers/secmem
obj-$(CONFIG_DMABUF_MM)			+= of_mm_dma_heap.o mm_dmaheap_dump.o mm_dmaheap_alloc_debug.o
