# SPDX-License-Identifier: GPL-2.0
# hisilicon clock driver

obj-$(CONFIG_RTC_DRV_PMIC_SPMI)	+= rtc_pmic_spmi.o
obj-$(CONFIG_VM_TIME_SYNC)	+= rtc_time_sync.o
obj-$(CONFIG_PLATFORM_RTC)	+= rtc_platform.o