/*
 * audio_pcm_ddr_map.h -- audio pcm ddr map info
 *
 * Copyright (c) 2023-2023 Huawei Technologies Co., Ltd.
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 */

#ifndef __AUDIO_PCM_DDR_MAP_H__
#define __AUDIO_PCM_DDR_MAP_H__

#include "audio_ddr_map.h"
#include "audio_common_msg.h"

#ifdef CONFIG_SND_SOC_CDC_PCM
/* sampling rate * time * bit width * channel num * buf num */
#ifdef CONFIG_CHARPRO_IP_PLATFORM
#define PCM_DMA_BUF_PLAYBACK_PRIMARY_LEN (48 * 20 * 4 * 32 * 2)
#define PCM_DMA_BUF_CAPTURE_PRIMARY_LEN (48 * 20 * 2 * 64 * 2)
#define PCM_DMA_BUF_PLAYBACK_FAST_LEN (48 * 10 * 4 * 32 * 2)
#define PCM_DMA_BUF_CAPTURE_FAST_LEN (48 * 10 * 2 * 64 * 2)
#else
#define PCM_DMA_BUF_PLAYBACK_PRIMARY_LEN (48 * 20 * 4 * 12 * 2)
#define PCM_DMA_BUF_CAPTURE_PRIMARY_LEN (48 * 20 * 2 * 30 * 2)
#define PCM_DMA_BUF_PLAYBACK_FAST_LEN (48 * 5 * 4 * 12 * 2)
#define PCM_DMA_BUF_CAPTURE_FAST_LEN (48 * 5 * 2 * 30 * 2)
#endif

#define PCM_DMA_BUF_CAPTURE_FM_LEN (48 * 20 * 4 * 2 * 2)
#define PCM_DMA_BUF_PLAYBACK_BT_LEN (48 * 20 * 4 * 2 * 2)
#define PCM_DMA_BUF_CAPTURE_BT_LEN (48 * 20 * 4 * 2 * 2)
#define PCM_DMA_BUF_CAPTURE_XCALL_LEN (48 * 20 * 4 * 8 * 2)

/* primary */
#define PCM_DMA_BUF_0_PLAYBACK_BASE (PCM_PLAY_BUFF_LOCATION)
#define PCM_DMA_BUF_0_PLAYBACK_LEN  (PCM_DMA_BUF_PLAYBACK_PRIMARY_LEN)
#define PCM_DMA_BUF_0_CAPTURE_BASE  (PCM_DMA_BUF_0_PLAYBACK_BASE + PCM_DMA_BUF_0_PLAYBACK_LEN)
#define PCM_DMA_BUF_0_CAPTURE_LEN   (PCM_DMA_BUF_CAPTURE_PRIMARY_LEN)
/* BT device */
#define PCM_DMA_BUF_1_PLAYBACK_BASE (PCM_DMA_BUF_0_CAPTURE_BASE + PCM_DMA_BUF_0_CAPTURE_LEN)
#define PCM_DMA_BUF_1_PLAYBACK_LEN  (PCM_DMA_BUF_PLAYBACK_BT_LEN)
#define PCM_DMA_BUF_1_CAPTURE_BASE  (PCM_DMA_BUF_1_PLAYBACK_BASE + PCM_DMA_BUF_1_PLAYBACK_LEN)
#define PCM_DMA_BUF_1_CAPTURE_LEN   (PCM_DMA_BUF_CAPTURE_BT_LEN)
/* FM device */
#define PCM_DMA_BUF_2_CAPTURE_BASE (PCM_DMA_BUF_1_CAPTURE_BASE + PCM_DMA_BUF_1_CAPTURE_LEN)
#define PCM_DMA_BUF_2_CAPTURE_LEN  (PCM_DMA_BUF_CAPTURE_FM_LEN)
/* lowlatency */
#define PCM_DMA_BUF_3_PLAYBACK_BASE (PCM_DMA_BUF_2_CAPTURE_BASE + PCM_DMA_BUF_2_CAPTURE_LEN)
#define PCM_DMA_BUF_3_PLAYBACK_LEN  (PCM_DMA_BUF_PLAYBACK_FAST_LEN)
#define PCM_DMA_BUF_3_CAPTURE_BASE  (PCM_DMA_BUF_3_PLAYBACK_BASE + PCM_DMA_BUF_3_PLAYBACK_LEN)
#define PCM_DMA_BUF_3_CAPTURE_LEN   (PCM_DMA_BUF_CAPTURE_FAST_LEN)
/* mmap device */
#define PCM_DMA_BUF_4_PLAYBACK_BASE (PCM_DMA_BUF_3_CAPTURE_BASE + PCM_DMA_BUF_3_CAPTURE_LEN)
#define PCM_DMA_BUF_4_PLAYBACK_LEN  (PCM_DMA_BUF_MMAP_MAX_SIZE)
#define PCM_DMA_BUF_4_CAPTURE_BASE  (PCM_DMA_BUF_4_PLAYBACK_BASE + PCM_DMA_BUF_4_PLAYBACK_LEN)
#define PCM_DMA_BUF_4_CAPTURE_LEN   (PCM_DMA_BUF_MMAP_MAX_SIZE)

/* karaoke record */
#define PCM_DMA_BUF_5_CAPTURE_LEN   (PCM_DMA_BUF_PLAYBACK_FAST_LEN)
#define PCM_DMA_BUF_5_CAPTURE_BASE  (PCM_DMA_BUF_4_CAPTURE_BASE + PCM_DMA_BUF_4_CAPTURE_LEN)
/* XCALL */
#define PCM_DMA_BUF_6_CAPTURE_BASE (PCM_DMA_BUF_5_CAPTURE_BASE + PCM_DMA_BUF_5_CAPTURE_LEN)
#define PCM_DMA_BUF_6_CAPTURE_LEN  (PCM_DMA_BUF_CAPTURE_XCALL_LEN)

#define PCM_DMA_BUF_END_ADDR        (PCM_DMA_BUF_6_CAPTURE_BASE + PCM_DMA_BUF_6_CAPTURE_LEN)
#else
#ifdef CONFIG_HIFI_MEMORY_15M
/* sampling rate * time * bit width * channel num * buf num */
#define PCM_DMA_BUF_PLAYBACK_PRIMARY_LEN (48 * 20 * 4 * 2 * 2)
#define PCM_DMA_BUF_PLAYBACK_DIRECT_LEN (48 * 20 * 4 * 2 * 4)
#define PCM_DMA_BUF_CAPTURE_PRIMARY_LEN (48 * 20 * 2 * 4 * 8)
#define PCM_DMA_BUF_CAPTURE_DIRECT_LEN ((60 + 19) * 1024)
#define PCM_DMA_BUF_SPATIAL_AUDIO_LEN (48 * 20 * 4 * 16 * 4)
#define PCM_DMA_BUF_SPATIAL_AUDIO_CAPTURE_LEN 256
#else
#define PCM_DMA_BUF_PLAYBACK_PRIMARY_LEN (48 * 20 * 2 * 4 * 4)
#define PCM_DMA_BUF_PLAYBACK_DIRECT_LEN (384 * 20 * 4 * 2 * 4)
#define PCM_DMA_BUF_CAPTURE_PRIMARY_LEN (48 * 20 * 2 * 13 * 8)
#define PCM_DMA_BUF_SPATIAL_AUDIO_LEN (48 * 20 * 4 * 16 * 4)
#define PCM_DMA_BUF_SPATIAL_AUDIO_CAPTURE_LEN 256
#endif

#define PCM_DMA_BUF_0_PLAYBACK_BASE (PCM_PLAY_BUFF_LOCATION)
#define PCM_DMA_BUF_0_PLAYBACK_LEN  (PCM_DMA_BUF_PLAYBACK_PRIMARY_LEN)
#define PCM_DMA_BUF_0_CAPTURE_BASE  (PCM_DMA_BUF_0_PLAYBACK_BASE + PCM_DMA_BUF_0_PLAYBACK_LEN)
#define PCM_DMA_BUF_0_CAPTURE_LEN   (PCM_DMA_BUF_CAPTURE_PRIMARY_LEN)

#define PCM_DMA_BUF_1_PLAYBACK_BASE (PCM_DMA_BUF_0_CAPTURE_BASE + PCM_DMA_BUF_0_CAPTURE_LEN)
#define PCM_DMA_BUF_1_PLAYBACK_LEN  (PCM_DMA_BUF_PLAYBACK_DIRECT_LEN)
#define PCM_DMA_BUF_1_CAPTURE_BASE  (PCM_DMA_BUF_1_PLAYBACK_BASE + PCM_DMA_BUF_1_PLAYBACK_LEN)
#ifdef CONFIG_HIFI_MEMORY_15M
#define PCM_DMA_BUF_1_CAPTURE_LEN   (PCM_DMA_BUF_CAPTURE_DIRECT_LEN)
#else
#define PCM_DMA_BUF_1_CAPTURE_LEN   (193 * 1024)
#endif

#define PCM_DMA_BUF_2_PLAYBACK_BASE (PCM_DMA_BUF_1_CAPTURE_BASE + PCM_DMA_BUF_1_CAPTURE_LEN)
#define PCM_DMA_BUF_2_PLAYBACK_LEN  (PCM_DMA_BUF_PLAYBACK_PRIMARY_LEN)
#define PCM_DMA_BUF_2_CAPTURE_BASE  (PCM_DMA_BUF_2_PLAYBACK_BASE + PCM_DMA_BUF_2_PLAYBACK_LEN)
#define PCM_DMA_BUF_2_CAPTURE_LEN   (PCM_DMA_BUF_PLAYBACK_PRIMARY_LEN)

/* mmap device */
#define PCM_DMA_BUF_3_PLAYBACK_BASE (PCM_DMA_BUF_2_CAPTURE_BASE + PCM_DMA_BUF_2_CAPTURE_LEN)
#define PCM_DMA_BUF_3_PLAYBACK_LEN  (PCM_DMA_BUF_MMAP_MAX_SIZE)
#define PCM_DMA_BUF_3_CAPTURE_BASE  (PCM_DMA_BUF_3_PLAYBACK_BASE + PCM_DMA_BUF_3_PLAYBACK_LEN)
#define PCM_DMA_BUF_3_CAPTURE_LEN   (PCM_DMA_BUF_MMAP_MAX_SIZE)

/* spatial audio */
#define PCM_DMA_BUF_4_PLAYBACK_BASE (PCM_DMA_BUF_3_CAPTURE_BASE + PCM_DMA_BUF_3_CAPTURE_LEN)
#define PCM_DMA_BUF_4_PLAYBACK_LEN  (PCM_DMA_BUF_SPATIAL_AUDIO_LEN)
#define PCM_DMA_BUF_4_CAPTURE_BASE  (PCM_DMA_BUF_4_PLAYBACK_BASE + PCM_DMA_BUF_4_PLAYBACK_LEN)
#define PCM_DMA_BUF_4_CAPTURE_LEN   (PCM_DMA_BUF_SPATIAL_AUDIO_CAPTURE_LEN)

#define PCM_DMA_BUF_END_ADDR        (PCM_DMA_BUF_4_CAPTURE_BASE + PCM_DMA_BUF_4_CAPTURE_LEN)
#endif

#define DSP_AP_MMAP_OUT_DATA_BASE   (PCM_DMA_BUF_3_PLAYBACK_BASE + 2048)

#endif /* __AUDIO_PCM_DDR_MAP_H__ */
