ccflags-$(CONFIG_HUAWEI_VIBRATOR_V2_0) += -DAAC_RICHTAP_SUPPORT

obj-$(CONFIG_HUAWEI_VIBRATOR_V2_0) 	+= haptic.o
haptic-y += haptic_core.o haptic_i2c.o haptic_misc.o haptic_regmap.o haptic_richtap.o haptic_sysfs.o

