# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the I2C input drivers
#

obj-$(CONFIG_UART_HID)	+= uart-hid.o

uart-hid-objs	=  uart_hid_core.o uart_hid_uart_protocol.o uart_hid_report.o uart_hid_uart_cmd.o uart_hid_desc.o