# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_BQ40Z50_FUEL_GAUGE) += bq40z50.o
obj-$(CONFIG_BQ40Z50_FUEL_GAUGE) += bq40z50_base.o
obj-$(CONFIG_COUL_DRV) += bq40z50_hisi.o
obj-$(CONFIG_COUL_DRV) += bq40z50_soc_cali.o
