#=============================================================================
#=============================================================================

obj-y += nfc_interface.o
obj-$(CONFIG_PN547_NFC_64)   += NXP_PN547_64/
obj-$(CONFIG_BCM20793_NFC)   += nfc_bcm20793/
obj-$(CONFIG_NFC_CXD224X)   += cxd224x/
obj-$(CONFIG_NFC_ST21NFC)   += st21nfc/
obj-$(CONFIG_NFC_TAGS)   += nfc_tags/
obj-$(CONFIG_THN31_NFC_64)   += TMS_THN31_64/
obj-$(CONFIG_CA11_NFC)   += ca11/
export CONFIG_PRIV_NFC_ADAPTER_PLAT=hisi
export TARGET_BUILD_VARIANT=user