# SPDX-License-Identifier: GPL-2.0
#
# Makefile for USB Core files and filesystem
#

ccflags-y += -I$(srctree)/drivers/usb/core
ccflags-y += -Wdate-time -Wextra -Wfloat-equal -Wformat=2 -Wshadow

obj-y += vendor-usb-core.o
