#ifndef __ASP_REGISTER_H__
#define __ASP_REGISTER_H__ 
#define SOC_ACPU_intr_hub_ao_BASE_ADDR (0xFB24F000)
#define SOC_ACPU_PAD_AO_IOMG_IOCG_BASE_ADDR (0xFB229000)
#define SOC_ACPU_SCTRL_BASE_ADDR (0xFB21B000)
#define SOC_ACPU_ACTRL_BASE_ADDR (0xFB214000)
#define SOC_ACPU_soundwire_BASE_ADDR (0xFAB54000)
#define SOC_ACPU_ASP_CODEC_BASE_ADDR (0xFAB52000)
#define SOC_ACPU_DSD_BASE_ADDR (0xFAB4FC00)
#define SOC_ACPU_SLIMBUS_BASE_ADDR (0xFAB50000)
#define SOC_ACPU_ASP_CFG_BASE_ADDR (0xFAB4E000)
#define SOC_ACPU_ASP_WD_BASE_ADDR (0xFAB4D000)
#define SOC_ACPU_ASP_DMAC_BASE_ADDR (0xFAB4B000)
#define SOC_ACPU_SECRAM_BASE_ADDR (0xFAA80000)
#define PAGE_ASPCFG SOC_ACPU_ASP_CFG_BASE_ADDR
#define PAGE_SCTRL SOC_ACPU_SCTRL_BASE_ADDR
#define RST_CTRLEN_CFG_ADDR PAGE_ASPCFG
#define RST_CTRLDIS_CFG_ADDR ((PAGE_ASPCFG) + 0x004)
#define GATE_EN_CFG_ADDR ((PAGE_ASPCFG) + 0x00C)
#define TZ_SECURE_N_CFG_ADDR ((PAGE_ASPCFG) + 0x100)
#define CLK_SEL_CFG_ADDR ((PAGE_ASPCFG) + 0x038)
#define R_DMA_SEL_CFG_ADDR ((PAGE_ASPCFG) + 0x054)
#define R_GATE1_EN_ADDR ((PAGE_ASPCFG) + 0x21C)
#define OCRAM_R0SIZE_CFG_ADDR ((PAGE_ASPCFG) + 0x104)
#define SCTRL_CLKDIV9 ((PAGE_SCTRL) + 0x274)
#define SCTRL_CLKDIV11 ((PAGE_SCTRL) + 0x284)
#define SCTRL_SCPERCLKEN1 ((PAGE_SCTRL) + 0x170)
#define REG_PCTRL 0x0
#define PERI_CTRL1 0x0
#define PERI_STAT6 0x0
#define ASP_LOGIC_FLAG 0x0
#define SOC_ACPU_SoundWire_BASE_ADDR SOC_ACPU_soundwire_BASE_ADDR
#define HI_SOUNDWIRE_DP1_FIFO_ADDR (SOC_ACPU_SoundWire_BASE_ADDR + 0x0)
#define HI_SOUNDWIRE_DP2_FIFO_ADDR (SOC_ACPU_SoundWire_BASE_ADDR + 0x100)
#define HI_SOUNDWIRE_DP3_FIFO_ADDR (SOC_ACPU_SoundWire_BASE_ADDR + 0x200)
#define HI_SOUNDWIRE_DP4_FIFO_ADDR (SOC_ACPU_SoundWire_BASE_ADDR + 0x300)
#define HI_SOUNDWIRE_DP5_FIFO_ADDR (SOC_ACPU_SoundWire_BASE_ADDR + 0x400)
#define HI_SOUNDWIRE_DP6_FIFO_ADDR (SOC_ACPU_SoundWire_BASE_ADDR + 0x500)
#define HI_SOUNDWIRE_DP7_FIFO_ADDR (SOC_ACPU_SoundWire_BASE_ADDR + 0x600)
#define HI_SOUNDWIRE_DP8_FIFO_ADDR (SOC_ACPU_SoundWire_BASE_ADDR + 0x700)
#define HI_SOUNDWIRE_DP9_FIFO_ADDR (SOC_ACPU_SoundWire_BASE_ADDR + 0x800)
#define HI_SOUNDWIRE_DP10_FIFO_ADDR (SOC_ACPU_SoundWire_BASE_ADDR + 0x900)
#define HI_SOUNDWIRE_DP11_FIFO_ADDR (SOC_ACPU_SoundWire_BASE_ADDR + 0xB00)
#define HI_SOUNDWIRE_DP12_FIFO_ADDR (SOC_ACPU_SoundWire_BASE_ADDR + 0xC00)
#define HI_SOUNDWIRE_DP13_FIFO_ADDR (SOC_ACPU_SoundWire_BASE_ADDR + 0xD00)
#define HI_SOUNDWIRE_DP14_FIFO_ADDR (SOC_ACPU_SoundWire_BASE_ADDR + 0xE00)
#endif
