obj-y += scharger_v700_watchdog.o
obj-y += scharger_v700_buck.o
obj-y += scharger_v700_batctl.o
obj-y += scharger_v700_dc.o
obj-y += scharger_v700_fcp.o
obj-y += scharger_v700_log.o
obj-y += bat_par_ctrl.o
obj-y += scharger_v700_waterdet.o
