/******************************************************************
 * Copyright (c) Hisilicon Technologies Co., Ltd. 2012-2018. All rights reserved.
 * File name  :
 * Description: arfeature_reg_offset_field.h
 *
 * Date         2021-12-29
 ********************************************************************/

#ifndef __AR_FEATURE_REG_OFFSET_FIELD_H__
#define __AR_FEATURE_REG_OFFSET_FIELD_H__

#define AR_FEATURE_FIRST_DETECT_LEN     1
#define AR_FEATURE_FIRST_DETECT_OFFSET  9
#define AR_FEATURE_ITER_NUM_LEN         1
#define AR_FEATURE_ITER_NUM_OFFSET      8
#define AR_FEATURE_LAYER_LEN            2
#define AR_FEATURE_LAYER_OFFSET         6
#define AR_FEATURE_ORIENT_EN_LEN        1
#define AR_FEATURE_ORIENT_EN_OFFSET     5
#define AR_FEATURE_KLTPRE_OUT_EN_LEN    1
#define AR_FEATURE_KLTPRE_OUT_EN_OFFSET 4
#define AR_FEATURE_MODE_LEN             3
#define AR_FEATURE_MODE_OFFSET          1
#define AR_FEATURE_AR_FEATURE_EN_LEN    1
#define AR_FEATURE_AR_FEATURE_EN_OFFSET 0

#define AR_FEATURE_HEIGHT_LEN    11
#define AR_FEATURE_HEIGHT_OFFSET 16
#define AR_FEATURE_WIDTH_LEN     11
#define AR_FEATURE_WIDTH_OFFSET  0

#define AR_FEATURE_BLK_H_NUM_LEN    4
#define AR_FEATURE_BLK_H_NUM_OFFSET 4
#define AR_FEATURE_BLK_V_NUM_LEN    4
#define AR_FEATURE_BLK_V_NUM_OFFSET 0

#define AR_FEATURE_BLK_H_SIZE_INV_LEN    16
#define AR_FEATURE_BLK_H_SIZE_INV_OFFSET 16
#define AR_FEATURE_BLK_V_SIZE_INV_LEN    16
#define AR_FEATURE_BLK_V_SIZE_INV_OFFSET 0

#define AR_FEATURE_CUR_KPNUM_LEN    12
#define AR_FEATURE_CUR_KPNUM_OFFSET 12
#define AR_FEATURE_MAX_KPNUM_LEN    12
#define AR_FEATURE_MAX_KPNUM_OFFSET 0

#define AR_FEATURE_SIGMA_ORI_LEN    10
#define AR_FEATURE_SIGMA_ORI_OFFSET 16
#define AR_FEATURE_SIGMA_DES_LEN    10
#define AR_FEATURE_SIGMA_DES_OFFSET 0

#define AR_FEATURE_GAUSS_ORG_3_LEN    8
#define AR_FEATURE_GAUSS_ORG_3_OFFSET 24
#define AR_FEATURE_GAUSS_ORG_2_LEN    8
#define AR_FEATURE_GAUSS_ORG_2_OFFSET 16
#define AR_FEATURE_GAUSS_ORG_1_LEN    8
#define AR_FEATURE_GAUSS_ORG_1_OFFSET 8
#define AR_FEATURE_GAUSS_ORG_0_LEN    8
#define AR_FEATURE_GAUSS_ORG_0_OFFSET 0

#define AR_FEATURE_GAUSS_1ST_2_LEN    8
#define AR_FEATURE_GAUSS_1ST_2_OFFSET 16
#define AR_FEATURE_GAUSS_1ST_1_LEN    8
#define AR_FEATURE_GAUSS_1ST_1_OFFSET 8
#define AR_FEATURE_GAUSS_1ST_0_LEN    8
#define AR_FEATURE_GAUSS_1ST_0_OFFSET 0

#define AR_FEATURE_GAUSS_2ND_3_LEN    8
#define AR_FEATURE_GAUSS_2ND_3_OFFSET 24
#define AR_FEATURE_GAUSS_2ND_2_LEN    8
#define AR_FEATURE_GAUSS_2ND_2_OFFSET 16
#define AR_FEATURE_GAUSS_2ND_1_LEN    8
#define AR_FEATURE_GAUSS_2ND_1_OFFSET 8
#define AR_FEATURE_GAUSS_2ND_0_LEN    8
#define AR_FEATURE_GAUSS_2ND_0_OFFSET 0

#define AR_FEATURE_DOG_THRESHOLD_LEN     15
#define AR_FEATURE_DOG_THRESHOLD_OFFSET  16
#define AR_FEATURE_EDGE_THRESHOLD_LEN    16
#define AR_FEATURE_EDGE_THRESHOLD_OFFSET 0

#define AR_FEATURE_MAG_THRESHOLD_LEN    8
#define AR_FEATURE_MAG_THRESHOLD_OFFSET 0

#define AR_FEATURE_VPRD_LAST_PAGE_LEN          19
#define AR_FEATURE_VPRD_LAST_PAGE_OFFSET       13
#define AR_FEATURE_VPRD_ALLOCATED_DU_LEN       5
#define AR_FEATURE_VPRD_ALLOCATED_DU_OFFSET    6
#define AR_FEATURE_VPRD_PIXEL_EXPANSION_LEN    1
#define AR_FEATURE_VPRD_PIXEL_EXPANSION_OFFSET 5
#define AR_FEATURE_VPRD_PIXEL_FORMAT_LEN       5
#define AR_FEATURE_VPRD_PIXEL_FORMAT_OFFSET    0

#define AR_FEATURE_VPRD_IHLEFT_LEN       6
#define AR_FEATURE_VPRD_IHLEFT_OFFSET    24
#define AR_FEATURE_VPRD_LINE_SIZE_LEN    15
#define AR_FEATURE_VPRD_LINE_SIZE_OFFSET 0

#define AR_FEATURE_VPRD_FRAME_SIZE_LEN    15
#define AR_FEATURE_VPRD_FRAME_SIZE_OFFSET 0

#define AR_FEATURE_VPRD_AXI_FRAME_START_LEN    30
#define AR_FEATURE_VPRD_AXI_FRAME_START_OFFSET 2

#define AR_FEATURE_VPRD_LINE_WRAP_0_LEN      14
#define AR_FEATURE_VPRD_LINE_WRAP_0_OFFSET   18
#define AR_FEATURE_VPRD_LINE_STRIDE_0_LEN    14
#define AR_FEATURE_VPRD_LINE_STRIDE_0_OFFSET 0

#define AR_FEATURE_VPRD_PREFETCH_BYPASS_LEN                      1
#define AR_FEATURE_VPRD_PREFETCH_BYPASS_OFFSET                   31
#define AR_FEATURE_VP_RD_STOP_LEN                                1
#define AR_FEATURE_VP_RD_STOP_OFFSET                             25
#define AR_FEATURE_VP_RD_STOP_OK_LEN                             1
#define AR_FEATURE_VP_RD_STOP_OK_OFFSET                          24
#define AR_FEATURE_VP_RD_STOP_ENABLE_PRESSURE_LEN                1
#define AR_FEATURE_VP_RD_STOP_ENABLE_PRESSURE_OFFSET             18
#define AR_FEATURE_VP_RD_STOP_ENABLE_FLUX_CTRL_LEN               1
#define AR_FEATURE_VP_RD_STOP_ENABLE_FLUX_CTRL_OFFSET            17
#define AR_FEATURE_VP_RD_STOP_ENABLE_DU_THRESHOLD_REACHED_LEN    1
#define AR_FEATURE_VP_RD_STOP_ENABLE_DU_THRESHOLD_REACHED_OFFSET 16

#define AR_FEATURE_PRE_VPRD_FRAME_SIZE_LEN    15
#define AR_FEATURE_PRE_VPRD_FRAME_SIZE_OFFSET 0

#define AR_FEATURE_VPWR_LAST_PAGE_LEN          19
#define AR_FEATURE_VPWR_LAST_PAGE_OFFSET       13
#define AR_FEATURE_VPWR_PIXEL_EXPANSION_LEN    1
#define AR_FEATURE_VPWR_PIXEL_EXPANSION_OFFSET 5
#define AR_FEATURE_VPWR_PIXEL_FORMAT_LEN       5
#define AR_FEATURE_VPWR_PIXEL_FORMAT_OFFSET    0

#define AR_FEATURE_VPWR_ADDRESS_FRAME_START_LEN    30
#define AR_FEATURE_VPWR_ADDRESS_FRAME_START_OFFSET 2

#define AR_FEATURE_VPWR_LINE_WRAP_LEN           14
#define AR_FEATURE_VPWR_LINE_WRAP_OFFSET        18
#define AR_FEATURE_VPWR_LINE_START_WSTRB_LEN    4
#define AR_FEATURE_VPWR_LINE_START_WSTRB_OFFSET 14
#define AR_FEATURE_VPWR_LINE_STRIDE_LEN         14
#define AR_FEATURE_VPWR_LINE_STRIDE_OFFSET      0

#define AR_FEATURE_VPWR_PREFETCH_BYPASS_LEN                      1
#define AR_FEATURE_VPWR_PREFETCH_BYPASS_OFFSET                   31
#define AR_FEATURE_VP_WR_STOP_LEN                                1
#define AR_FEATURE_VP_WR_STOP_OFFSET                             25
#define AR_FEATURE_VP_WR_STOP_OK_LEN                             1
#define AR_FEATURE_VP_WR_STOP_OK_OFFSET                          24
#define AR_FEATURE_VP_WR_STOP_ENABLE_PRESSURE_LEN                1
#define AR_FEATURE_VP_WR_STOP_ENABLE_PRESSURE_OFFSET             18
#define AR_FEATURE_VP_WR_STOP_ENABLE_FLUX_CTRL_LEN               1
#define AR_FEATURE_VP_WR_STOP_ENABLE_FLUX_CTRL_OFFSET            17
#define AR_FEATURE_VP_WR_STOP_ENABLE_DU_THRESHOLD_REACHED_LEN    1
#define AR_FEATURE_VP_WR_STOP_ENABLE_DU_THRESHOLD_REACHED_OFFSET 16

#define AR_FEATURE_PRE_VPWR_ADDRESS_FRAME_START_LEN    30
#define AR_FEATURE_PRE_VPWR_ADDRESS_FRAME_START_OFFSET 2

#define AR_FEATURE_KLTPRE_BLK_H_SIZE_INV_LEN    16
#define AR_FEATURE_KLTPRE_BLK_H_SIZE_INV_OFFSET 16
#define AR_FEATURE_KLTPRE_BLK_V_SIZE_INV_LEN    16
#define AR_FEATURE_KLTPRE_BLK_V_SIZE_INV_OFFSET 0

#define AR_FEATURE_KLTPRE_BLK_MAX_KPNUM_LEN    3
#define AR_FEATURE_KLTPRE_BLK_MAX_KPNUM_OFFSET 8
#define AR_FEATURE_KLTPRE_BLK_H_NUM_LEN        4
#define AR_FEATURE_KLTPRE_BLK_H_NUM_OFFSET     4
#define AR_FEATURE_KLTPRE_BLK_V_NUM_LEN        4
#define AR_FEATURE_KLTPRE_BLK_V_NUM_OFFSET     0

#define AR_FEATURE_MFPDA_SCORE_STEP_0_LEN    13
#define AR_FEATURE_MFPDA_SCORE_STEP_0_OFFSET 16
#define AR_FEATURE_MFPDA_KPNUM_TH_0_LEN      12
#define AR_FEATURE_MFPDA_KPNUM_TH_0_OFFSET   0

#define AR_FEATURE_MFPDA_SCORE_STEP_1_LEN    13
#define AR_FEATURE_MFPDA_SCORE_STEP_1_OFFSET 16
#define AR_FEATURE_MFPDA_KPNUM_TH_1_LEN      12
#define AR_FEATURE_MFPDA_KPNUM_TH_1_OFFSET   0

#define AR_FEATURE_MFPDA_SCORE_STEP_2_LEN    13
#define AR_FEATURE_MFPDA_SCORE_STEP_2_OFFSET 16
#define AR_FEATURE_MFPDA_KPNUM_TH_2_LEN      12
#define AR_FEATURE_MFPDA_KPNUM_TH_2_OFFSET   0

#define AR_FEATURE_MFPDA_SCORE_STEP_3_LEN    13
#define AR_FEATURE_MFPDA_SCORE_STEP_3_OFFSET 16
#define AR_FEATURE_MFPDA_KPNUM_TH_3_LEN      12
#define AR_FEATURE_MFPDA_KPNUM_TH_3_OFFSET   0

#define AR_FEATURE_MFPDA_SCORE_STEP_4_LEN    13
#define AR_FEATURE_MFPDA_SCORE_STEP_4_OFFSET 16
#define AR_FEATURE_MFPDA_KPNUM_TH_4_LEN      12
#define AR_FEATURE_MFPDA_KPNUM_TH_4_OFFSET   0

#define AR_FEATURE_MFPDA_SCORE_STEP_5_LEN    13
#define AR_FEATURE_MFPDA_SCORE_STEP_5_OFFSET 16
#define AR_FEATURE_MFPDA_KPNUM_TH_5_LEN      12
#define AR_FEATURE_MFPDA_KPNUM_TH_5_OFFSET   0

#define AR_FEATURE_MFPDA_GRID_SCORE_STEP_0_LEN    13
#define AR_FEATURE_MFPDA_GRID_SCORE_STEP_0_OFFSET 16
#define AR_FEATURE_MFPDA_GRID_KPNUM_TH_0_LEN      8
#define AR_FEATURE_MFPDA_GRID_KPNUM_TH_0_OFFSET   0

#define AR_FEATURE_MFPDA_GRID_SCORE_STEP_1_LEN    13
#define AR_FEATURE_MFPDA_GRID_SCORE_STEP_1_OFFSET 16
#define AR_FEATURE_MFPDA_GRID_KPNUM_TH_1_LEN      8
#define AR_FEATURE_MFPDA_GRID_KPNUM_TH_1_OFFSET   0

#define AR_FEATURE_MFPDA_GRID_SCORE_STEP_2_LEN    13
#define AR_FEATURE_MFPDA_GRID_SCORE_STEP_2_OFFSET 16
#define AR_FEATURE_MFPDA_GRID_KPNUM_TH_2_LEN      8
#define AR_FEATURE_MFPDA_GRID_KPNUM_TH_2_OFFSET   0

#define AR_FEATURE_MFPDA_GRID_SCORE_STEP_3_LEN    13
#define AR_FEATURE_MFPDA_GRID_SCORE_STEP_3_OFFSET 16
#define AR_FEATURE_MFPDA_GRID_KPNUM_TH_3_LEN      8
#define AR_FEATURE_MFPDA_GRID_KPNUM_TH_3_OFFSET   0

#define AR_FEATURE_MFPDA_GRID_SCORE_STEP_4_LEN    13
#define AR_FEATURE_MFPDA_GRID_SCORE_STEP_4_OFFSET 16
#define AR_FEATURE_MFPDA_GRID_KPNUM_TH_4_LEN      8
#define AR_FEATURE_MFPDA_GRID_KPNUM_TH_4_OFFSET   0

#define AR_FEATURE_MFPDA_GRID_SCORE_STEP_5_LEN    13
#define AR_FEATURE_MFPDA_GRID_SCORE_STEP_5_OFFSET 16
#define AR_FEATURE_MFPDA_GRID_KPNUM_TH_5_LEN      8
#define AR_FEATURE_MFPDA_GRID_KPNUM_TH_5_OFFSET   0

#define AR_FEATURE_ROI_START_Y_0_LEN    10
#define AR_FEATURE_ROI_START_Y_0_OFFSET 16
#define AR_FEATURE_ROI_START_X_0_LEN    10
#define AR_FEATURE_ROI_START_X_0_OFFSET 0

#define AR_FEATURE_ROI_START_Y_1_LEN    10
#define AR_FEATURE_ROI_START_Y_1_OFFSET 16
#define AR_FEATURE_ROI_START_X_1_LEN    10
#define AR_FEATURE_ROI_START_X_1_OFFSET 0

#define AR_FEATURE_ROI_START_Y_2_LEN    10
#define AR_FEATURE_ROI_START_Y_2_OFFSET 16
#define AR_FEATURE_ROI_START_X_2_LEN    10
#define AR_FEATURE_ROI_START_X_2_OFFSET 0

#define AR_FEATURE_ROI_START_Y_3_LEN    10
#define AR_FEATURE_ROI_START_Y_3_OFFSET 16
#define AR_FEATURE_ROI_START_X_3_LEN    10
#define AR_FEATURE_ROI_START_X_3_OFFSET 0

#define AR_FEATURE_ROI_START_Y_4_LEN    10
#define AR_FEATURE_ROI_START_Y_4_OFFSET 16
#define AR_FEATURE_ROI_START_X_4_LEN    10
#define AR_FEATURE_ROI_START_X_4_OFFSET 0

#define AR_FEATURE_ROI_START_Y_5_LEN    10
#define AR_FEATURE_ROI_START_Y_5_OFFSET 16
#define AR_FEATURE_ROI_START_X_5_LEN    10
#define AR_FEATURE_ROI_START_X_5_OFFSET 0

#define AR_FEATURE_ROI_START_Y_6_LEN    10
#define AR_FEATURE_ROI_START_Y_6_OFFSET 16
#define AR_FEATURE_ROI_START_X_6_LEN    10
#define AR_FEATURE_ROI_START_X_6_OFFSET 0

#define AR_FEATURE_ROI_START_Y_7_LEN    10
#define AR_FEATURE_ROI_START_Y_7_OFFSET 16
#define AR_FEATURE_ROI_START_X_7_LEN    10
#define AR_FEATURE_ROI_START_X_7_OFFSET 0

#define AR_FEATURE_ROI_END_Y_0_LEN    10
#define AR_FEATURE_ROI_END_Y_0_OFFSET 16
#define AR_FEATURE_ROI_END_X_0_LEN    10
#define AR_FEATURE_ROI_END_X_0_OFFSET 0

#define AR_FEATURE_ROI_END_Y_1_LEN    10
#define AR_FEATURE_ROI_END_Y_1_OFFSET 16
#define AR_FEATURE_ROI_END_X_1_LEN    10
#define AR_FEATURE_ROI_END_X_1_OFFSET 0

#define AR_FEATURE_ROI_END_Y_2_LEN    10
#define AR_FEATURE_ROI_END_Y_2_OFFSET 16
#define AR_FEATURE_ROI_END_X_2_LEN    10
#define AR_FEATURE_ROI_END_X_2_OFFSET 0

#define AR_FEATURE_ROI_END_Y_3_LEN    10
#define AR_FEATURE_ROI_END_Y_3_OFFSET 16
#define AR_FEATURE_ROI_END_X_3_LEN    10
#define AR_FEATURE_ROI_END_X_3_OFFSET 0

#define AR_FEATURE_ROI_END_Y_4_LEN    10
#define AR_FEATURE_ROI_END_Y_4_OFFSET 16
#define AR_FEATURE_ROI_END_X_4_LEN    10
#define AR_FEATURE_ROI_END_X_4_OFFSET 0

#define AR_FEATURE_ROI_END_Y_5_LEN    10
#define AR_FEATURE_ROI_END_Y_5_OFFSET 16
#define AR_FEATURE_ROI_END_X_5_LEN    10
#define AR_FEATURE_ROI_END_X_5_OFFSET 0

#define AR_FEATURE_ROI_END_Y_6_LEN    10
#define AR_FEATURE_ROI_END_Y_6_OFFSET 16
#define AR_FEATURE_ROI_END_X_6_LEN    10
#define AR_FEATURE_ROI_END_X_6_OFFSET 0

#define AR_FEATURE_ROI_END_Y_7_LEN    10
#define AR_FEATURE_ROI_END_Y_7_OFFSET 16
#define AR_FEATURE_ROI_END_X_7_LEN    10
#define AR_FEATURE_ROI_END_X_7_OFFSET 0

#define AR_FEATURE_ROI_WIN_MODE_LEN    1
#define AR_FEATURE_ROI_WIN_MODE_OFFSET 0

#define AR_FEATURE_GRID_MAX_KPNUM_0_LEN    8
#define AR_FEATURE_GRID_MAX_KPNUM_0_OFFSET 16
#define AR_FEATURE_SCORE_TH_0_LEN          15
#define AR_FEATURE_SCORE_TH_0_OFFSET       0

#define AR_FEATURE_GRID_MAX_KPNUM_255_LEN    8
#define AR_FEATURE_GRID_MAX_KPNUM_255_OFFSET 16
#define AR_FEATURE_SCORE_TH_255_LEN          15
#define AR_FEATURE_SCORE_TH_255_OFFSET       0

#define AR_FEATURE_KPT_NUM_0_LEN    8
#define AR_FEATURE_KPT_NUM_0_OFFSET 0

#define AR_FEATURE_KPT_NUM_255_LEN    8
#define AR_FEATURE_KPT_NUM_255_OFFSET 0

#define AR_FEATURE_KPT_COUNT_0_LEN    8
#define AR_FEATURE_KPT_COUNT_0_OFFSET 16
#define AR_FEATURE_MIN_SCORE_0_LEN    15
#define AR_FEATURE_MIN_SCORE_0_OFFSET 0

#define AR_FEATURE_KPT_COUNT_255_LEN    8
#define AR_FEATURE_KPT_COUNT_255_OFFSET 16
#define AR_FEATURE_MIN_SCORE_255_LEN    15
#define AR_FEATURE_MIN_SCORE_255_OFFSET 0

#define AR_FEATURE_SUM_SCORE_0_LEN    23
#define AR_FEATURE_SUM_SCORE_0_OFFSET 0

#define AR_FEATURE_SUM_SCORE_255_LEN    23
#define AR_FEATURE_SUM_SCORE_255_OFFSET 0

#define AR_FEATURE_TOTAL_KPT_NUM_LEN    12
#define AR_FEATURE_TOTAL_KPT_NUM_OFFSET 0

#define AR_FEATURE_KLTPRE_TOTAL_KPT_NUM_LEN    8
#define AR_FEATURE_KLTPRE_TOTAL_KPT_NUM_OFFSET 0

#define AR_FEATURE_NXT_DOG_THRESHOLD_LEN    15
#define AR_FEATURE_NXT_DOG_THRESHOLD_OFFSET 0

#define AR_FEATURE_DEBUG0_LEN    32
#define AR_FEATURE_DEBUG0_OFFSET 0

#define AR_FEATURE_DEBUG1_LEN    32
#define AR_FEATURE_DEBUG1_OFFSET 0

#define AR_FEATURE_DEBUG2_LEN    32
#define AR_FEATURE_DEBUG2_OFFSET 0

#define AR_FEATURE_DEBUG3_LEN    32
#define AR_FEATURE_DEBUG3_OFFSET 0

#endif // __AR_FEATURE_REG_OFFSET_FIELD_H__
