/******************************************************************
 * Copyright (c) Hisilicon Technologies Co., Ltd. 2012-2018. All rights reserved.
 * File name  :
 * Description:
 *
 * Date         2020-04-17 16:28:10
 ********************************************************************/

#ifndef __SLAM_COMPARE_REG_OFFSET_FIELD_H__
#define __SLAM_COMPARE_REG_OFFSET_FIELD_H__

#define COMPARE_COMPARE_EN_LEN    1
#define COMPARE_COMPARE_EN_OFFSET 0

#define COMPARE_BLK_NUM_LEN      8
#define COMPARE_BLK_NUM_OFFSET   16
#define COMPARE_BLK_H_NUM_LEN    4
#define COMPARE_BLK_H_NUM_OFFSET 8
#define COMPARE_BLK_V_NUM_LEN    4
#define COMPARE_BLK_V_NUM_OFFSET 0

#define COMPARE_DIS_THRESHOLD_LEN    15
#define COMPARE_DIS_THRESHOLD_OFFSET 17
#define COMPARE_DIS_RATIO_LEN        13
#define COMPARE_DIS_RATIO_OFFSET     4
#define COMPARE_H_RADIUS_LEN         2
#define COMPARE_H_RADIUS_OFFSET      2
#define COMPARE_V_RADIUS_LEN         2
#define COMPARE_V_RADIUS_OFFSET      0

#define COMPARE_STAT_EN_LEN       1
#define COMPARE_STAT_EN_OFFSET    24
#define COMPARE_MAX3_RATIO_LEN    5
#define COMPARE_MAX3_RATIO_OFFSET 16
#define COMPARE_BIN_FACTOR_LEN    8
#define COMPARE_BIN_FACTOR_OFFSET 8
#define COMPARE_BIN_NUM_LEN       6
#define COMPARE_BIN_NUM_OFFSET    0

#define COMPARE_PREFETCH_ENABLE_LEN    1
#define COMPARE_PREFETCH_ENABLE_OFFSET 20
#define COMPARE_FIRST_32K_PAGE_LEN     19
#define COMPARE_FIRST_32K_PAGE_OFFSET  0

#define COMPARE_CENH_OFFSET_LEN    4
#define COMPARE_CENH_OFFSET_OFFSET 4
#define COMPARE_CENV_OFFSET_LEN    4
#define COMPARE_CENV_OFFSET_OFFSET 0

#define COMPARE_TOTAL_KPT_NUM_LEN    12
#define COMPARE_TOTAL_KPT_NUM_OFFSET 0

#define COMPARE_REF_KPT_NUM_0_LEN    8
#define COMPARE_REF_KPT_NUM_0_OFFSET 0

#define COMPARE_REF_KPT_NUM_255_LEN    8
#define COMPARE_REF_KPT_NUM_255_OFFSET 0

#define COMPARE_CUR_KPT_NUM_0_LEN    8
#define COMPARE_CUR_KPT_NUM_0_OFFSET 0

#define COMPARE_CUR_KPT_NUM_255_LEN    8
#define COMPARE_CUR_KPT_NUM_255_OFFSET 0

#define COMPARE_MATCHED_KPTS_LEN    11
#define COMPARE_MATCHED_KPTS_OFFSET 0

#define COMPARE_REF_INDEX_0_LEN    12
#define COMPARE_REF_INDEX_0_OFFSET 12
#define COMPARE_CUR_INDEX_0_LEN    12
#define COMPARE_CUR_INDEX_0_OFFSET 0

#define COMPARE_REF_INDEX_1599_LEN    12
#define COMPARE_REF_INDEX_1599_OFFSET 12
#define COMPARE_CUR_INDEX_1599_LEN    12
#define COMPARE_CUR_INDEX_1599_OFFSET 0

#define COMPARE_DISTANCE_0_LEN    15
#define COMPARE_DISTANCE_0_OFFSET 0

#define COMPARE_DISTANCE_1599_LEN    15
#define COMPARE_DISTANCE_1599_OFFSET 0

#define COMPARE_DEBUG0_LEN    32
#define COMPARE_DEBUG0_OFFSET 0

#define COMPARE_DEBUG1_LEN    32
#define COMPARE_DEBUG1_OFFSET 0

#define COMPARE_EC_0_LEN    32
#define COMPARE_EC_0_OFFSET 0

#define COMPARE_EC_1_LEN    32
#define COMPARE_EC_1_OFFSET 0

#endif // __SLAM_COMPARE_REG_OFFSET_FIELD_H__
