ccflags-y += -I$(srctree)/drivers/huawei_platform/sensor/ext_inputhub/default/
ccflags-y += -I$(srctree)/../../vendor/huawei/extra/kernel/include/power/

obj-$(CONFIG_HUAWEI_WATCH_CHARGER) += huawei_watch_charger.o
obj-$(CONFIG_HUAWEI_WATCH_POWER_CONTROLLER) += watch_power_controller.o
