ccflags-y += -I$(srctree)/include/linux
ccflags-y += -I$(srctree)/drivers/platform_drivers/tzdriver
ccflags-y += -I$(srctree)/drivers/dma-buf/heaps
ccflags-y += -I$(srctree)/platform_source/basicplatform/drivers/dma-buf/heaps
obj-$(CONFIG_DMABUF_MM)			+= mm_sec_alloc.o
obj-$(CONFIG_DMABUF_MM)			+= mm_tee_op.o
obj-$(CONFIG_MEMORY_VLTMM)		+= mm_vltmm.o mm_vltmm_agent.o
