/*
 * Copyright (c) @CompanyNameMagicTag 2021-2023. All rights reserved.
 * 功能说明   : wifi定制化头文件声明
 * 作者       :
 * 创建日期   : 2015年10月08日
 */

#ifndef HISI_CUSTOMIZE_WIFI_DYN_POW_H
#define HISI_CUSTOMIZE_WIFI_DYN_POW_H

/* 动态功率校准参数 */
typedef enum {
    /* pa */
    WLAN_CFG_DYN_POW_RATIO_PA2GCCKA0,
    WLAN_CFG_DYN_POW_RATIO_PA2GA0,
    WLAN_CFG_DYN_POW_RATIO_PA2G40A0,
    WLAN_CFG_DYN_POW_RATIO_PA5GA0,
    /* add 5g low power part */
    WLAN_CFG_DYN_POW_RATIO_PA5GA0_LOW,
    /* 5g Band1& 2g CW */
    WLAN_CFG_DYN_POW_RATIO_PA5GA0_BAND1,
    WLAN_CFG_DYN_POW_RATIO_PA5GA0_BAND1_LOW,

    WLAN_CFG_DYN_POW_RATIO_PA2GCCKA1,
    WLAN_CFG_DYN_POW_RATIO_PA2GA1,
    WLAN_CFG_DYN_POW_RATIO_PA2G40A1,
    WLAN_CFG_DYN_POW_RATIO_PA5GA1,
    WLAN_CFG_DYN_POW_RATIO_PA5GA1_LOW,
    /* 5g Band1& 2g CW */
    WLAN_CFG_DYN_POW_RATIO_PA5GA1_BAND1,
    WLAN_CFG_DYN_POW_RATIO_PA5GA1_BAND1_LOW,

    WLAN_CFG_DYN_POW_RATIO_PA2GCCKA2,
    WLAN_CFG_DYN_POW_RATIO_PA2GA2,
    WLAN_CFG_DYN_POW_RATIO_PA2G40A2,
    WLAN_CFG_DYN_POW_RATIO_PA5GA2,
    WLAN_CFG_DYN_POW_RATIO_PA5GA2_LOW,
    /* 5g Band1& 2g CW */
    WLAN_CFG_DYN_POW_RATIO_PA5GA2_BAND1,
    WLAN_CFG_DYN_POW_RATIO_PA5GA2_BAND1_LOW,

    WLAN_CFG_DYN_POW_RATIO_PA2GCCKA3,
    WLAN_CFG_DYN_POW_RATIO_PA2GA3,
    WLAN_CFG_DYN_POW_RATIO_PA2G40A3,
    WLAN_CFG_DYN_POW_RATIO_PA5GA3,
    WLAN_CFG_DYN_POW_RATIO_PA5GA3_LOW,
    /* 5g Band1& 2g CW */
    WLAN_CFG_DYN_POW_RATIO_PA5GA3_BAND1,
    WLAN_CFG_DYN_POW_RATIO_PA5GA3_BAND1_LOW,
    /* 6G Band 0~14 */
#ifdef _PRE_WLAN_FEATURE_6G_EXTEND
    WLAN_CFG_DYN_POW_RATIO_PA6G_BAND0,
    WLAN_CFG_DYN_POW_RATIO_PA6G_BAND1,
    WLAN_CFG_DYN_POW_RATIO_PA6G_BAND2,
    WLAN_CFG_DYN_POW_RATIO_PA6G_BAND3,
    WLAN_CFG_DYN_POW_RATIO_PA6G_BAND4,
    WLAN_CFG_DYN_POW_RATIO_PA6G_BAND5,
    WLAN_CFG_DYN_POW_RATIO_PA6G_BAND6,
    WLAN_CFG_DYN_POW_RATIO_PA6G_BAND7,
    WLAN_CFG_DYN_POW_RATIO_PA6G_BAND8,
    WLAN_CFG_DYN_POW_RATIO_PA6G_BAND9,
    WLAN_CFG_DYN_POW_RATIO_PA6G_BAND10,
    WLAN_CFG_DYN_POW_RATIO_PA6G_BAND11,
    WLAN_CFG_DYN_POW_RATIO_PA6G_BAND12,
    WLAN_CFG_DYN_POW_RATIO_PA6G_BAND13,
    WLAN_CFG_DYN_POW_RATIO_PA6G_BAND14,
#endif
    WLAN_CFG_DYN_POW_MUFREQ_2GCCK_C0,
    WLAN_CFG_DYN_POW_MUFREQ_2G20_C0,
    WLAN_CFG_DYN_POW_MUFREQ_2G40_C0,
    WLAN_CFG_DYN_POW_MUFREQ_5G160_C0,

    WLAN_CFG_DYN_POW_MUFREQ_2GCCK_C1,
    WLAN_CFG_DYN_POW_MUFREQ_2G20_C1,
    WLAN_CFG_DYN_POW_MUFREQ_2G40_C1,
    WLAN_CFG_DYN_POW_MUFREQ_5G160_C1,

    WLAN_CFG_DYN_POW_MUFREQ_2GCCK_C2,
    WLAN_CFG_DYN_POW_MUFREQ_2G20_C2,
    WLAN_CFG_DYN_POW_MUFREQ_2G40_C2,
    WLAN_CFG_DYN_POW_MUFREQ_5G160_C2,

    WLAN_CFG_DYN_POW_MUFREQ_2GCCK_C3,
    WLAN_CFG_DYN_POW_MUFREQ_2G20_C3,
    WLAN_CFG_DYN_POW_MUFREQ_2G40_C3,
    WLAN_CFG_DYN_POW_MUFREQ_5G160_C3,
    /* DPN */
    WLAN_CFG_DYN_POW_2G_CORE0_DPN_11B,
    WLAN_CFG_DYN_POW_2G_CORE1_DPN_11B,
    WLAN_CFG_DYN_POW_2G_CORE2_DPN_11B,
    WLAN_CFG_DYN_POW_2G_CORE3_DPN_11B,
    WLAN_CFG_DYN_POW_2G_CORE0_DPN_OFDM_20M,
    WLAN_CFG_DYN_POW_2G_CORE1_DPN_OFDM_20M,
    WLAN_CFG_DYN_POW_2G_CORE2_DPN_OFDM_20M,
    WLAN_CFG_DYN_POW_2G_CORE3_DPN_OFDM_20M,
    WLAN_CFG_DYN_POW_2G_CORE0_DPN_OFDM_40M,
    WLAN_CFG_DYN_POW_2G_CORE1_DPN_OFDM_40M,
    WLAN_CFG_DYN_POW_2G_CORE2_DPN_OFDM_40M,
    WLAN_CFG_DYN_POW_2G_CORE3_DPN_OFDM_40M,

    WLAN_CFG_DYN_POW_5G_CORE0_DPN_20M,
    WLAN_CFG_DYN_POW_5G_CORE1_DPN_20M,
    WLAN_CFG_DYN_POW_5G_CORE2_DPN_20M,
    WLAN_CFG_DYN_POW_5G_CORE3_DPN_20M,
    WLAN_CFG_DYN_POW_5G_CORE0_DPN_40M,
    WLAN_CFG_DYN_POW_5G_CORE1_DPN_40M,
    WLAN_CFG_DYN_POW_5G_CORE2_DPN_40M,
    WLAN_CFG_DYN_POW_5G_CORE3_DPN_40M,
    WLAN_CFG_DYN_POW_5G_CORE0_DPN_80M,
    WLAN_CFG_DYN_POW_5G_CORE1_DPN_80M,
    WLAN_CFG_DYN_POW_5G_CORE2_DPN_80M,
    WLAN_CFG_DYN_POW_5G_CORE3_DPN_80M,
    WLAN_CFG_DYN_POW_5G_CORE0_DPN_160M,
    WLAN_CFG_DYN_POW_5G_CORE1_DPN_160M,
    WLAN_CFG_DYN_POW_5G_CORE2_DPN_160M,
    WLAN_CFG_DYN_POW_5G_CORE3_DPN_160M,
#ifdef _PRE_WLAN_FEATURE_6G_EXTEND
    WLAN_CFG_DYN_POW_6G_CORE0_DPN_20M,
    WLAN_CFG_DYN_POW_6G_CORE1_DPN_20M,
    WLAN_CFG_DYN_POW_6G_CORE2_DPN_20M,
    WLAN_CFG_DYN_POW_6G_CORE3_DPN_20M,
    WLAN_CFG_DYN_POW_6G_CORE0_DPN_40M,
    WLAN_CFG_DYN_POW_6G_CORE1_DPN_40M,
    WLAN_CFG_DYN_POW_6G_CORE2_DPN_40M,
    WLAN_CFG_DYN_POW_6G_CORE3_DPN_40M,
    WLAN_CFG_DYN_POW_6G_CORE0_DPN_80M,
    WLAN_CFG_DYN_POW_6G_CORE1_DPN_80M,
    WLAN_CFG_DYN_POW_6G_CORE2_DPN_80M,
    WLAN_CFG_DYN_POW_6G_CORE3_DPN_80M,
    WLAN_CFG_DYN_POW_6G_CORE0_DPN_160M,
    WLAN_CFG_DYN_POW_6G_CORE1_DPN_160M,
    WLAN_CFG_DYN_POW_6G_CORE2_DPN_160M,
    WLAN_CFG_DYN_POW_6G_CORE3_DPN_160M,
#endif
    WLAN_CFG_DYN_POW_2G_CORE0_DPN_11B_LOW,
    WLAN_CFG_DYN_POW_2G_CORE1_DPN_11B_LOW,
    WLAN_CFG_DYN_POW_2G_CORE2_DPN_11B_LOW,
    WLAN_CFG_DYN_POW_2G_CORE3_DPN_11B_LOW,
    WLAN_CFG_DYN_POW_2G_CORE0_DPN_OFDM_20M_LOW,
    WLAN_CFG_DYN_POW_2G_CORE1_DPN_OFDM_20M_LOW,
    WLAN_CFG_DYN_POW_2G_CORE2_DPN_OFDM_20M_LOW,
    WLAN_CFG_DYN_POW_2G_CORE3_DPN_OFDM_20M_LOW,
    WLAN_CFG_DYN_POW_2G_CORE0_DPN_OFDM_40M_LOW,
    WLAN_CFG_DYN_POW_2G_CORE1_DPN_OFDM_40M_LOW,
    WLAN_CFG_DYN_POW_2G_CORE2_DPN_OFDM_40M_LOW,
    WLAN_CFG_DYN_POW_2G_CORE3_DPN_OFDM_40M_LOW,

    WLAN_CFG_DYN_POW_5G_CORE0_DPN_20M_LOW,
    WLAN_CFG_DYN_POW_5G_CORE1_DPN_20M_LOW,
    WLAN_CFG_DYN_POW_5G_CORE2_DPN_20M_LOW,
    WLAN_CFG_DYN_POW_5G_CORE3_DPN_20M_LOW,
    WLAN_CFG_DYN_POW_5G_CORE0_DPN_40M_LOW,
    WLAN_CFG_DYN_POW_5G_CORE1_DPN_40M_LOW,
    WLAN_CFG_DYN_POW_5G_CORE2_DPN_40M_LOW,
    WLAN_CFG_DYN_POW_5G_CORE3_DPN_40M_LOW,
    WLAN_CFG_DYN_POW_5G_CORE0_DPN_80M_LOW,
    WLAN_CFG_DYN_POW_5G_CORE1_DPN_80M_LOW,
    WLAN_CFG_DYN_POW_5G_CORE2_DPN_80M_LOW,
    WLAN_CFG_DYN_POW_5G_CORE3_DPN_80M_LOW,
    WLAN_CFG_DYN_POW_5G_CORE0_DPN_160M_LOW,
    WLAN_CFG_DYN_POW_5G_CORE1_DPN_160M_LOW,
    WLAN_CFG_DYN_POW_5G_CORE2_DPN_160M_LOW,
    WLAN_CFG_DYN_POW_5G_CORE3_DPN_160M_LOW,
#ifdef _PRE_WLAN_FEATURE_6G_EXTEND
    WLAN_CFG_DYN_POW_6G_CORE0_DPN_20M_LOW,
    WLAN_CFG_DYN_POW_6G_CORE1_DPN_20M_LOW,
    WLAN_CFG_DYN_POW_6G_CORE2_DPN_20M_LOW,
    WLAN_CFG_DYN_POW_6G_CORE3_DPN_20M_LOW,
    WLAN_CFG_DYN_POW_6G_CORE0_DPN_40M_LOW,
    WLAN_CFG_DYN_POW_6G_CORE1_DPN_40M_LOW,
    WLAN_CFG_DYN_POW_6G_CORE2_DPN_40M_LOW,
    WLAN_CFG_DYN_POW_6G_CORE3_DPN_40M_LOW,
    WLAN_CFG_DYN_POW_6G_CORE0_DPN_80M_LOW,
    WLAN_CFG_DYN_POW_6G_CORE1_DPN_80M_LOW,
    WLAN_CFG_DYN_POW_6G_CORE2_DPN_80M_LOW,
    WLAN_CFG_DYN_POW_6G_CORE3_DPN_80M_LOW,
    WLAN_CFG_DYN_POW_6G_CORE0_DPN_160M_LOW,
    WLAN_CFG_DYN_POW_6G_CORE1_DPN_160M_LOW,
    WLAN_CFG_DYN_POW_6G_CORE2_DPN_160M_LOW,
    WLAN_CFG_DYN_POW_6G_CORE3_DPN_160M_LOW,
#endif

    WLAN_CFG_DYN_POW_PARAMS_BUTT,
} wlan_dyn_pow_cfg_enum;

#endif  // hisi_customize_wifi_pow.h
