/*
 * Copyright (c) @CompanyNameMagicTag 2021-2023. All rights reserved.
 * 功能说明   : wifi定制化配置列表
 * 作者       :
 * 创建日期   : 2020年5月20日
 */

/* 头文件包含 */
#include "hisi_customize_wifi_mp16.h"
#include "hisi_customize_wifi.h"
#include "hisi_ini.h"
#include "plat_type.h"
#include "oam_ext_if.h"
#include "oam_ext_if.h"
#include "hmac_tx_amsdu.h"
#undef THIS_FILE_ID
#define THIS_FILE_ID OAM_FILE_ID_HISI_CUSTOMIZE_WIFI_DATA_C

wlan_cust_cfg_cmd g_wifi_cfg_host[WLAN_CFG_HOST_BUTT] = {
    /* ROAM */
    {"roam_switch",     WLAN_CFG_HOST_ROAM_SWITCH, &g_wlan_cust.uc_roam_switch,
     sizeof(g_wlan_cust.uc_roam_switch), WLAN_CUST_NUM_1, OAL_FALSE},
    {"scan_orthogonal", WLAN_CFG_HOST_SCAN_ORTHOGONAL, &g_wlan_cust.uc_roam_scan_orthogonal,
     sizeof(g_wlan_cust.uc_roam_scan_orthogonal), WLAN_CUST_NUM_1, OAL_FALSE},
    {"trigger_b",       WLAN_CFG_HOST_TRIGGER_B, &g_wlan_cust.c_roam_trigger_b,
     sizeof(g_wlan_cust.c_roam_trigger_b), WLAN_CUST_NUM_1, OAL_FALSE},
    {"trigger_a",       WLAN_CFG_HOST_TRIGGER_A, &g_wlan_cust.c_roam_trigger_a,
     sizeof(g_wlan_cust.c_roam_trigger_a), WLAN_CUST_NUM_1, OAL_FALSE},
    {"delta_b",         WLAN_CFG_HOST_DELTA_B, &g_wlan_cust.c_roam_delta_b,
     sizeof(g_wlan_cust.c_roam_delta_b), WLAN_CUST_NUM_1, OAL_FALSE},
    {"delta_a",         WLAN_CFG_HOST_DELTA_A, &g_wlan_cust.c_roam_delta_a,
     sizeof(g_wlan_cust.c_roam_delta_a), WLAN_CUST_NUM_1, OAL_FALSE},
    {"dense_env_trigger_b", WLAN_CFG_HOST_DENSE_ENV_TRIGGER_B, &g_wlan_cust.c_dense_env_roam_trigger_b,
     sizeof(g_wlan_cust.c_dense_env_roam_trigger_b), WLAN_CUST_NUM_1, OAL_FALSE},
    {"dense_env_trigger_a", WLAN_CFG_HOST_DENSE_ENV_TRIGGER_A, &g_wlan_cust.c_dense_env_roam_trigger_a,
     sizeof(g_wlan_cust.c_dense_env_roam_trigger_a), WLAN_CUST_NUM_1, OAL_FALSE},
    {"scenario_enable",     WLAN_CFG_HOST_SCENARIO_ENABLE, &g_wlan_cust.uc_scenario_enable,
     sizeof(g_wlan_cust.uc_scenario_enable), WLAN_CUST_NUM_1, OAL_FALSE},
    {"candidate_good_rssi", WLAN_CFG_HOST_CANDIDATE_GOOD_RSSI, &g_wlan_cust.c_candidate_good_rssi,
     sizeof(g_wlan_cust.c_candidate_good_rssi), WLAN_CUST_NUM_1, OAL_FALSE},
    {"candidate_good_num",  WLAN_CFG_HOST_CANDIDATE_GOOD_NUM, &g_wlan_cust.uc_candidate_good_num,
     sizeof(g_wlan_cust.uc_candidate_good_num), WLAN_CUST_NUM_1, OAL_FALSE},
    {"candidate_weak_num",  WLAN_CFG_HOST_CANDIDATE_WEAK_NUM, &g_wlan_cust.uc_candidate_weak_num,
     sizeof(g_wlan_cust.uc_candidate_weak_num), WLAN_CUST_NUM_1, OAL_FALSE},
    {"interval_variable",   WLAN_CFG_HOST_INTERVAL_VARIABLE, &g_wlan_cust.us_roam_interval,
     sizeof(g_wlan_cust.us_roam_interval), WLAN_CUST_NUM_1, OAL_FALSE},
    /* 性能 */
    {"ampdu_tx_max_num",    WLAN_CFG_HOST_AMPDU_TX_MAX_NUM, &g_wlan_cust.ampdu_tx_max_num,
     sizeof(g_wlan_cust.ampdu_tx_max_num), WLAN_CUST_NUM_1, OAL_FALSE},
    {"lock_dma_latency", WLAN_CFG_HOST_DMA_LATENCY, &g_cust_host.freq_lock.dma_latency_val,
     sizeof(g_cust_host.freq_lock.dma_latency_val), WLAN_CUST_NUM_1, OAL_FALSE},

    {"lock_cpu_th_high", WLAN_CFG_HOST_LOCK_CPU_TH_HIGH, &g_cust_host.freq_lock.lock_cpu_th_high,
     sizeof(g_cust_host.freq_lock.lock_cpu_th_high), WLAN_CUST_NUM_1, OAL_FALSE},
    {"lock_cpu_th_low", WLAN_CFG_HOST_LOCK_CPU_TH_LOW, &g_cust_host.freq_lock.lock_cpu_th_low,
     sizeof(g_cust_host.freq_lock.lock_cpu_th_low), WLAN_CUST_NUM_1, OAL_FALSE},

    {"irq_affinity",       WLAN_CFG_HOST_IRQ_AFFINITY, &g_cust_host.freq_lock.en_irq_affinity,
     sizeof(g_cust_host.freq_lock.en_irq_affinity), WLAN_CUST_NUM_1, OAL_FALSE},
    {"cpu_id_th_low",      WLAN_CFG_HOST_IRQ_TH_LOW, &g_cust_host.freq_lock.throughput_irq_low,
     sizeof(g_cust_host.freq_lock.throughput_irq_low), WLAN_CUST_NUM_1, OAL_FALSE},
    {"cpu_id_th_high",     WLAN_CFG_HOST_IRQ_TH_HIGH, &g_cust_host.freq_lock.throughput_irq_high,
     sizeof(g_cust_host.freq_lock.throughput_irq_high), WLAN_CUST_NUM_1, OAL_FALSE},
    {"cpu_id_pps_th_low",  WLAN_CFG_HOST_IRQ_PPS_TH_LOW, &g_cust_host.freq_lock.irq_pps_low,
     sizeof(g_cust_host.freq_lock.irq_pps_low), WLAN_CUST_NUM_1, OAL_FALSE},
    {"cpu_id_pps_th_high", WLAN_CFG_HOST_IRQ_PPS_TH_HIGH, &g_cust_host.freq_lock.irq_pps_high,
     sizeof(g_cust_host.freq_lock.irq_pps_high), WLAN_CUST_NUM_1, OAL_FALSE},
#ifdef _PRE_WLAN_FEATURE_AMPDU_TX_HW
    /* ó2?t??o?ê1?ü */
    {"hw_ampdu", WLAN_CFG_HOST_HW_AMPDU, &g_cust_host.tx_ampdu.ampdu_hw_en,
     sizeof(g_cust_host.tx_ampdu.ampdu_hw_en), WLAN_CUST_NUM_1, OAL_FALSE},
    {"hw_ampdu_th_l", WLAN_CFG_HOST_HW_AMPDU_TH_LOW, &g_cust_host.tx_ampdu.throughput_low,
     sizeof(g_cust_host.tx_ampdu.throughput_low), WLAN_CUST_NUM_1, OAL_FALSE},
    {"hw_ampdu_th_h", WLAN_CFG_HOST_HW_AMPDU_TH_HIGH, &g_cust_host.tx_ampdu.throughput_high,
     sizeof(g_cust_host.tx_ampdu.throughput_high), WLAN_CUST_NUM_1, OAL_FALSE},
#endif
#ifdef _PRE_WLAN_FEATURE_MULTI_NETBUF_AMSDU
    {"tx_amsdu_ampdu", WLAN_CFG_HOST_AMPDU_AMSDU_SKB, &g_cust_host.large_amsdu.large_amsdu_en,
     sizeof(g_cust_host.large_amsdu.large_amsdu_en), WLAN_CUST_NUM_1, OAL_FALSE},
    {"tx_amsdu_ampdu_th_l", WLAN_CFG_HOST_AMSDU_AMPDU_TH_LOW, &g_cust_host.large_amsdu.throughput_low,
     sizeof(g_cust_host.large_amsdu.throughput_low), WLAN_CUST_NUM_1, OAL_FALSE},
    {"tx_amsdu_ampdu_th_m", WLAN_CFG_HOST_AMSDU_AMPDU_TH_MIDDLE, &g_cust_host.large_amsdu.throughput_middle,
     sizeof(g_st_tx_large_amsdu.us_amsdu_throughput_middle), WLAN_CUST_NUM_1, OAL_FALSE},
    {"tx_amsdu_ampdu_th_h", WLAN_CFG_HOST_AMSDU_AMPDU_TH_HIGH, &g_cust_host.large_amsdu.throughput_high,
     sizeof(g_cust_host.large_amsdu.throughput_high), WLAN_CUST_NUM_1, OAL_FALSE},
#endif
#ifdef _PRE_WLAN_TCP_OPT
    {"en_tcp_ack_filter",      WLAN_CFG_HOST_TCP_ACK_FILTER, &g_cust_host.tcp_ack_filt.filter_en,
     sizeof(g_cust_host.tcp_ack_filt.filter_en), WLAN_CUST_NUM_1, OAL_FALSE},
    {"rx_tcp_ack_filter_th_l", WLAN_CFG_HOST_TCP_ACK_FILTER_TH_LOW, &g_cust_host.tcp_ack_filt.throughput_low,
     sizeof(g_cust_host.tcp_ack_filt.throughput_low), WLAN_CUST_NUM_1, OAL_FALSE},
    {"rx_tcp_ack_filter_th_h", WLAN_CFG_HOST_TCP_ACK_FILTER_TH_HIGH, &g_cust_host.tcp_ack_filt.throughput_high,
     sizeof(g_cust_host.tcp_ack_filt.throughput_high), WLAN_CUST_NUM_1, OAL_FALSE},
#endif

    {"small_amsdu_switch",   WLAN_CFG_HOST_TX_SMALL_AMSDU, &g_cust_host.small_amsdu.en_switch,
     sizeof(g_cust_host.small_amsdu.en_switch), WLAN_CUST_NUM_1, OAL_FALSE},
    {"small_amsdu_th_h", WLAN_CFG_HOST_SMALL_AMSDU_HIGH,
     &g_cust_host.small_amsdu.throughput_high,
     sizeof(g_cust_host.small_amsdu.throughput_high), WLAN_CUST_NUM_1, OAL_FALSE},
    {"small_amsdu_th_l",     WLAN_CFG_HOST_SMALL_AMSDU_LOW,
     &g_cust_host.small_amsdu.throughput_low,
     sizeof(g_cust_host.small_amsdu.throughput_low), WLAN_CUST_NUM_1, OAL_FALSE},
    {"small_amsdu_pps_th_h", WLAN_CFG_HOST_SMALL_AMSDU_PPS_HIGH,
     &g_cust_host.small_amsdu.pps_high,
     sizeof(g_cust_host.small_amsdu.pps_high), WLAN_CUST_NUM_1, OAL_FALSE},
    {"small_amsdu_pps_th_l", WLAN_CFG_HOST_SMALL_AMSDU_PPS_LOW,
     &g_cust_host.small_amsdu.pps_low,
     sizeof(g_cust_host.small_amsdu.pps_low), WLAN_CUST_NUM_1, OAL_FALSE},

    {"tcp_ack_buf_switch", WLAN_CFG_HOST_TX_TCP_ACK_BUF, &g_cust_host.tcp_ack_buf.host_buf_en,
     sizeof(g_cust_host.tcp_ack_buf.host_buf_en), WLAN_CUST_NUM_1, OAL_FALSE},
    {"device_tcp_ack_buf_switch", WLAN_CFG_DEVICE_TX_TCP_ACK_BUF, &g_cust_host.tcp_ack_buf.device_buf_en,
     sizeof(g_cust_host.tcp_ack_buf.device_buf_en), WLAN_CUST_NUM_1, OAL_FALSE},
    {"tcp_ack_buf_th_h", WLAN_CFG_HOST_TCP_ACK_BUF_HIGH,
     &g_cust_host.tcp_ack_buf.throughput_high,
     sizeof(g_cust_host.tcp_ack_buf.throughput_high), WLAN_CUST_NUM_1, OAL_FALSE},
    {"tcp_ack_buf_th_l", WLAN_CFG_HOST_TCP_ACK_BUF_LOW,
     &g_cust_host.tcp_ack_buf.throughput_low,
     sizeof(g_cust_host.tcp_ack_buf.throughput_low), WLAN_CUST_NUM_1, OAL_FALSE},
    {"tcp_ack_buf_th_h_40M",  WLAN_CFG_HOST_TCP_ACK_BUF_HIGH_40M,
     &g_cust_host.tcp_ack_buf.throughput_high_40m,
     sizeof(g_cust_host.tcp_ack_buf.throughput_high_40m), WLAN_CUST_NUM_1, OAL_FALSE},
    {"tcp_ack_buf_th_l_40M",  WLAN_CFG_HOST_TCP_ACK_BUF_LOW_40M,
     &g_cust_host.tcp_ack_buf.throughput_low_40m,
     sizeof(g_cust_host.tcp_ack_buf.throughput_low_40m), WLAN_CUST_NUM_1, OAL_FALSE},
    {"tcp_ack_buf_th_h_80M",  WLAN_CFG_HOST_TCP_ACK_BUF_HIGH_80M,
     &g_cust_host.tcp_ack_buf.throughput_high_80m,
     sizeof(g_cust_host.tcp_ack_buf.throughput_high_80m), WLAN_CUST_NUM_1, OAL_FALSE},
    {"tcp_ack_buf_th_l_80M",  WLAN_CFG_HOST_TCP_ACK_BUF_LOW_80M,
     &g_cust_host.tcp_ack_buf.throughput_low_80m,
     sizeof(g_cust_host.tcp_ack_buf.throughput_low_80m), WLAN_CUST_NUM_1, OAL_FALSE},
    {"tcp_ack_buf_th_h_160M", WLAN_CFG_HOST_TCP_ACK_BUF_HIGH_160M,
     &g_cust_host.tcp_ack_buf.throughput_high_160m,
     sizeof(g_cust_host.tcp_ack_buf.throughput_high_160m), WLAN_CUST_NUM_1, OAL_FALSE},
    {"tcp_ack_buf_th_l_160M", WLAN_CFG_HOST_TCP_ACK_BUF_LOW_160M,
     &g_cust_host.tcp_ack_buf.throughput_low_160m,
     sizeof(g_cust_host.tcp_ack_buf.throughput_low_160m), WLAN_CUST_NUM_1, OAL_FALSE},
    {"tcp_ack_buf_userctl_switch", WLAN_CFG_HOST_TX_TCP_ACK_BUF_USERCTL, &g_cust_host.tcp_ack_buf.buf_userctl_test_en,
     sizeof(g_cust_host.tcp_ack_buf.buf_userctl_test_en), WLAN_CUST_NUM_1, OAL_FALSE},
    {"tcp_ack_buf_userctl_h",      WLAN_CFG_HOST_TCP_ACK_BUF_USERCTL_HIGH, &g_cust_host.tcp_ack_buf.buf_userctl_high,
     sizeof(g_cust_host.tcp_ack_buf.buf_userctl_high), WLAN_CUST_NUM_1, OAL_FALSE},
    {"tcp_ack_buf_userctl_l",      WLAN_CFG_HOST_TCP_ACK_BUF_USERCTL_LOW, &g_cust_host.tcp_ack_buf.buf_userctl_low,
     sizeof(g_cust_host.tcp_ack_buf.buf_userctl_low), WLAN_CUST_NUM_1, OAL_FALSE},

    {"dyn_bypass_extlna_th_switch", WLAN_CFG_HOST_RX_DYN_BYPASS_EXTLNA, &g_cust_host.dyn_extlna.switch_en,
     sizeof(g_cust_host.dyn_extlna.switch_en), WLAN_CUST_NUM_1, OAL_FALSE},
    {"dyn_bypass_extlna_th_h",      WLAN_CFG_HOST_RX_DYN_BYPASS_EXTLNA_HIGH,
     &g_cust_host.dyn_extlna.throughput_high, sizeof(g_cust_host.dyn_extlna.throughput_high),
     WLAN_CUST_NUM_1, OAL_FALSE},
    {"dyn_bypass_extlna_th_l",      WLAN_CFG_HOST_RX_DYN_BYPASS_EXTLNA_LOW, &g_cust_host.dyn_extlna.throughput_low,
     sizeof(g_cust_host.dyn_extlna.throughput_low), WLAN_CUST_NUM_1, OAL_FALSE},

    {"rx_ampdu_amsdu", WLAN_CFG_HOST_RX_AMPDU_AMSDU_SKB, &g_cust_host.host_rx_ampdu_amsdu,
     sizeof(g_cust_host.host_rx_ampdu_amsdu), WLAN_CUST_NUM_1, OAL_FALSE},
    {"rx_ampdu_bitmap", WLAN_CFG_HOST_RX_AMPDU_BITMAP, &g_cust_host.rx_buffer_size,
     sizeof(g_cust_host.rx_buffer_size), WLAN_CUST_NUM_1, OAL_FALSE},

    {"ps_mode", WLAN_CFG_HOST_PS_MODE, &g_cust_host.wlan_ps_mode,
     sizeof(g_cust_host.wlan_ps_mode), WLAN_CUST_NUM_1, OAL_FALSE},
    /* SCAN */
    {"random_mac_addr_scan", WLAN_CFG_HOST_RANDOM_MAC_ADDR_SCAN, &g_wlan_cust.uc_random_mac_addr_scan,
     sizeof(g_wlan_cust.uc_random_mac_addr_scan), WLAN_CUST_NUM_1, OAL_FALSE},
    /* 11AC2G */
    {"11ac2g_enable",        WLAN_CFG_HOST_11AC2G_ENABLE, &g_cust_host.wlan_11ac2g_switch,
     sizeof(g_cust_host.wlan_11ac2g_switch), WLAN_CUST_NUM_1, OAL_FALSE},
    {"disable_capab_2ght40", WLAN_CFG_HOST_DISABLE_CAPAB_2GHT40, &g_wlan_cust.uc_disable_capab_2ght40,
     sizeof(g_wlan_cust.uc_disable_capab_2ght40), WLAN_CUST_NUM_1, OAL_FALSE},

    {"probe_resp_mode", WLAN_CFG_HOST_PROBE_RESP_MODE, &g_cust_host.wlan_probe_resp_mode,
     sizeof(g_cust_host.wlan_probe_resp_mode), WLAN_CUST_NUM_1, OAL_FALSE},
    {"miracast_enable", WLAN_CFG_HOST_MIRACAST_SINK_ENABLE,
     &g_cust_host.en_hmac_feature_switch[CUST_MIRACAST_SINK_SWITCH],
     sizeof(g_cust_host.en_hmac_feature_switch[CUST_MIRACAST_SINK_SWITCH]), WLAN_CUST_NUM_1, OAL_FALSE},
    {"reduce_miracast_log", WLAN_CFG_HOST_REDUCE_MIRACAST_LOG,
     &g_cust_host.en_hmac_feature_switch[CUST_MIRACAST_REDUCE_LOG_SWITCH],
     sizeof(g_cust_host.en_hmac_feature_switch[CUST_MIRACAST_REDUCE_LOG_SWITCH]), WLAN_CUST_NUM_1, OAL_FALSE},
    {"core_bind_cap", WLAN_CFG_HOST_CORE_BIND_CAP,
     &g_cust_host.en_hmac_feature_switch[CUST_CORE_BIND_SWITCH],
     sizeof(g_cust_host.en_hmac_feature_switch[CUST_CORE_BIND_SWITCH]), WLAN_CUST_NUM_1, OAL_FALSE},

    {"lte_gpio_check_switch", WLAN_CFG_HOST_LTE_GPIO_CHECK_SWITCH, &g_wlan_cust.lte_gpio_check_switch,
     sizeof(g_wlan_cust.lte_gpio_check_switch), WLAN_CUST_NUM_1, OAL_FALSE},
    {"ism_priority", WLAN_HOST_ATCMDSRV_ISM_PRIORITY, &g_wlan_cust.ism_priority,
     sizeof(g_wlan_cust.ism_priority), WLAN_CUST_NUM_1, OAL_FALSE},
    {"lte_rx", WLAN_HOST_ATCMDSRV_LTE_RX, &g_wlan_cust.lte_rx,
     sizeof(g_wlan_cust.lte_rx), WLAN_CUST_NUM_1, OAL_FALSE},
    {"lte_tx", WLAN_HOST_ATCMDSRV_LTE_TX, &g_wlan_cust.lte_tx,
     sizeof(g_wlan_cust.lte_tx), WLAN_CUST_NUM_1, OAL_FALSE},
    {"lte_inact", WLAN_HOST_ATCMDSRV_LTE_INACT, &g_wlan_cust.lte_inact,
     sizeof(g_wlan_cust.lte_inact), WLAN_CUST_NUM_1, OAL_FALSE},
    {"ism_rx_act", WLAN_HOST_ATCMDSRV_ISM_RX_ACT, &g_wlan_cust.ism_rx_act,
     sizeof(g_wlan_cust.ism_rx_act), WLAN_CUST_NUM_1, OAL_FALSE},
    {"bant_pri", WLAN_HOST_ATCMDSRV_BANT_PRI, &g_wlan_cust.bant_pri,
     sizeof(g_wlan_cust.bant_pri), WLAN_CUST_NUM_1, OAL_FALSE},
    {"bant_status", WLAN_HOST_ATCMDSRV_BANT_STATUS, &g_wlan_cust.bant_status,
     sizeof(g_wlan_cust.bant_status), WLAN_CUST_NUM_1, OAL_FALSE},
    {"want_pri", WLAN_HOST_ATCMDSRV_WANT_PRI, &g_wlan_cust.want_pri,
     sizeof(g_wlan_cust.want_pri), WLAN_CUST_NUM_1, OAL_FALSE},
    {"want_status", WLAN_HOST_ATCMDSRV_WANT_STATUS, &g_wlan_cust.want_status,
     sizeof(g_wlan_cust.want_status), WLAN_CUST_NUM_1, OAL_FALSE},

    {"lock_cpu_freq", WLAN_CFG_HOST_LOCK_CPU_FREQ, &g_cust_host.lock_max_cpu_freq,
     sizeof(g_cust_host.lock_max_cpu_freq), WLAN_CUST_NUM_1, OAL_FALSE},
    {"optimized_feature_mask",     WLAN_CFG_HOST_OPTIMIZED_FEATURE_SWITCH,
     &g_cust_cap.optimized_feature_mask, sizeof(g_cust_cap.optimized_feature_mask), WLAN_CUST_NUM_1, OAL_FALSE},
#ifdef _PRE_WLAN_CHBA_MGMT
    {"chba_init_social_channel",     WLAN_CFG_HOST_CHBA_INIT_SOCIAL_CHAN,
     &g_cust_cap.chba_init_social_channel, sizeof(g_cust_cap.chba_init_social_channel), WLAN_CUST_NUM_1, OAL_FALSE},
    {"chba_social_follow_work_disable", WLAN_CFG_HOST_CHBA_SOCIAL_FOLLOW_WORK,
     &g_cust_cap.chba_social_follow_work_disable, sizeof(g_cust_cap.chba_social_follow_work_disable),
     WLAN_CUST_NUM_1, OAL_FALSE},
    /* chba信道跟随开关 */
    {"chba_dbac_chan_follow_switch", WLAN_CFG_HOST_CHBA_DBAC_CHAN_FOLLOW_SWITCH,
     &g_cust_cap.chba_dbac_chan_follow_switch, sizeof(g_cust_cap.chba_dbac_chan_follow_switch),
     WLAN_CUST_NUM_1, OAL_FALSE},
#endif
    {"expand_feature_switch_bitmap", WLAN_CFG_HOST_EXTPAND_FEATURE_SWITCH_BITMAP,
     &g_cust_cap.expand_feature_switch_bitmap, sizeof(g_cust_cap.expand_feature_switch_bitmap), WLAN_CUST_NUM_1, OAL_FALSE},
    {"reduce_pwr_2g_40mhz_channel_bitmap", WLAN_CFG_HOST_REDUCE_PWR_2G_40MHZ_CHANNEL_BITMAP,
     &g_cust_host.reduce_pwr_2g_40mhz_channel_bitmap, sizeof(g_cust_host.reduce_pwr_2g_40mhz_channel_bitmap),
     WLAN_CUST_NUM_1, OAL_FALSE},
};

wlan_cust_cfg_cmd g_wifi_cfg_rf_cali[WLAN_CFG_RF_CALI_BUTT] = {
    /* 动态校准 */
    {"dyn_cali_dscr_interval", WLAN_CFG_DYN_CALI_DSCR_ITERVL, &g_cust_rf_cali.dyn_cali_dscr_interval[WLAN_CALI_BAND_2G],
     sizeof(g_cust_rf_cali.dyn_cali_dscr_interval[WLAN_CALI_BAND_2G]) << BIT_OFFSET_1, WLAN_CUST_NUM_1, OAL_FALSE},
    {"far_dist_pow_gain_switch", WLAN_CFG_FAR_DIST_POW_GAIN_SWITCH, &g_cust_rf_front.far_dist_pow_gain_switch,
     sizeof(g_cust_rf_front.far_dist_pow_gain_switch), WLAN_CUST_NUM_1, OAL_FALSE},

    /* 2G RF前端插损 */
    {"rf_rx_insertion_loss_2g_b1", WLAN_CFG_RF_RX_INSERTION_LOSS_2G_BAND1,
     &g_cust_rf_front.rf_loss_gain_db.gain_db_2g[WLAN_2G_BAND_IDX0][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rf_loss_gain_db.gain_db_2g[WLAN_2G_BAND_IDX0][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rf_loss_gain_db.gain_db_2g[WLAN_2G_BAND_IDX0]), OAL_FALSE},
    {"rf_rx_insertion_loss_2g_b2", WLAN_CFG_RF_RX_INSERTION_LOSS_2G_BAND2,
     &g_cust_rf_front.rf_loss_gain_db.gain_db_2g[WLAN_2G_BAND_IDX1][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rf_loss_gain_db.gain_db_2g[WLAN_2G_BAND_IDX1][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rf_loss_gain_db.gain_db_2g[WLAN_2G_BAND_IDX1]), OAL_FALSE},
    {"rf_rx_insertion_loss_2g_b3", WLAN_CFG_RF_RX_INSERTION_LOSS_2G_BAND3,
     &g_cust_rf_front.rf_loss_gain_db.gain_db_2g[WLAN_2G_BAND_IDX2][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rf_loss_gain_db.gain_db_2g[WLAN_2G_BAND_IDX2][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rf_loss_gain_db.gain_db_2g[WLAN_2G_BAND_IDX2]), OAL_FALSE},

    /* 5G RF前端插损 */
    {"rf_rx_insertion_loss_5g_b1", WLAN_CFG_RF_RX_INSERTION_LOSS_5G_BAND1,
     &g_cust_rf_front.rf_loss_gain_db.gain_db_5g[WLAN_5G_BAND_IDX0][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rf_loss_gain_db.gain_db_5g[WLAN_5G_BAND_IDX0][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rf_loss_gain_db.gain_db_5g[WLAN_5G_BAND_IDX0]), OAL_FALSE},
    {"rf_rx_insertion_loss_5g_b2", WLAN_CFG_RF_RX_INSERTION_LOSS_5G_BAND2,
     &g_cust_rf_front.rf_loss_gain_db.gain_db_5g[WLAN_5G_BAND_IDX1][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rf_loss_gain_db.gain_db_5g[WLAN_5G_BAND_IDX1][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rf_loss_gain_db.gain_db_5g[WLAN_5G_BAND_IDX1]), OAL_FALSE},
    {"rf_rx_insertion_loss_5g_b3", WLAN_CFG_RF_RX_INSERTION_LOSS_5G_BAND3,
     &g_cust_rf_front.rf_loss_gain_db.gain_db_5g[WLAN_5G_BAND_IDX2][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rf_loss_gain_db.gain_db_5g[WLAN_5G_BAND_IDX2][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rf_loss_gain_db.gain_db_5g[WLAN_5G_BAND_IDX2]), OAL_FALSE},
    {"rf_rx_insertion_loss_5g_b4", WLAN_CFG_RF_RX_INSERTION_LOSS_5G_BAND4,
     &g_cust_rf_front.rf_loss_gain_db.gain_db_5g[WLAN_5G_BAND_IDX3][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rf_loss_gain_db.gain_db_5g[WLAN_5G_BAND_IDX3][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rf_loss_gain_db.gain_db_5g[WLAN_5G_BAND_IDX3]), OAL_FALSE},
    {"rf_rx_insertion_loss_5g_b5", WLAN_CFG_RF_RX_INSERTION_LOSS_5G_BAND5,
     &g_cust_rf_front.rf_loss_gain_db.gain_db_5g[WLAN_5G_BAND_IDX4][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rf_loss_gain_db.gain_db_5g[WLAN_5G_BAND_IDX4][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rf_loss_gain_db.gain_db_5g[WLAN_5G_BAND_IDX4]), OAL_FALSE},
    {"rf_rx_insertion_loss_5g_b6", WLAN_CFG_RF_RX_INSERTION_LOSS_5G_BAND6,
     &g_cust_rf_front.rf_loss_gain_db.gain_db_5g[WLAN_5G_BAND_IDX5][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rf_loss_gain_db.gain_db_5g[WLAN_5G_BAND_IDX5][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rf_loss_gain_db.gain_db_5g[WLAN_5G_BAND_IDX5]), OAL_FALSE},
    {"rf_rx_insertion_loss_5g_b7", WLAN_CFG_RF_RX_INSERTION_LOSS_5G_BAND7,
     &g_cust_rf_front.rf_loss_gain_db.gain_db_5g[WLAN_5G_BAND_IDX6][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rf_loss_gain_db.gain_db_5g[WLAN_5G_BAND_IDX6][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rf_loss_gain_db.gain_db_5g[WLAN_5G_BAND_IDX6]), OAL_FALSE},
#ifdef _PRE_WLAN_FEATURE_6G_EXTEND
    /* 6G RF前端插损 */
    {"rf_rx_insertion_loss_6g_b0", WLAN_CFG_RF_RX_INSERTION_LOSS_6G_BAND0,
     &g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX0][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX0][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX0]), OAL_FALSE},
    {"rf_rx_insertion_loss_6g_b1", WLAN_CFG_RF_RX_INSERTION_LOSS_6G_BAND1,
     &g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX1][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX1][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX1]), OAL_FALSE},
    {"rf_rx_insertion_loss_6g_b2", WLAN_CFG_RF_RX_INSERTION_LOSS_6G_BAND2,
     &g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX2][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX2][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX2]), OAL_FALSE},
    {"rf_rx_insertion_loss_6g_b3", WLAN_CFG_RF_RX_INSERTION_LOSS_6G_BAND3,
     &g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX3][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX3][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX3]), OAL_FALSE},
    {"rf_rx_insertion_loss_6g_b4", WLAN_CFG_RF_RX_INSERTION_LOSS_6G_BAND4,
     &g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX4][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX4][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX4]), OAL_FALSE},
    {"rf_rx_insertion_loss_6g_b5", WLAN_CFG_RF_RX_INSERTION_LOSS_6G_BAND5,
     &g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX5][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX5][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX5]), OAL_FALSE},
    {"rf_rx_insertion_loss_6g_b6", WLAN_CFG_RF_RX_INSERTION_LOSS_6G_BAND6,
     &g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX6][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX6][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX6]), OAL_FALSE},
    {"rf_rx_insertion_loss_6g_b7", WLAN_CFG_RF_RX_INSERTION_LOSS_6G_BAND7,
     &g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX7][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX7][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX7]), OAL_FALSE},
    {"rf_rx_insertion_loss_6g_b8", WLAN_CFG_RF_RX_INSERTION_LOSS_6G_BAND8,
     &g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX8][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX8][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX8]), OAL_FALSE},
    {"rf_rx_insertion_loss_6g_b9", WLAN_CFG_RF_RX_INSERTION_LOSS_6G_BAND9,
     &g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX9][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX9][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX9]), OAL_FALSE},
    {"rf_rx_insertion_loss_6g_b10", WLAN_CFG_RF_RX_INSERTION_LOSS_6G_BAND10,
     &g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX10][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX10][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX10]), OAL_FALSE},
    {"rf_rx_insertion_loss_6g_b11", WLAN_CFG_RF_RX_INSERTION_LOSS_6G_BAND11,
     &g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX11][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX11][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX11]), OAL_FALSE},
    {"rf_rx_insertion_loss_6g_b12", WLAN_CFG_RF_RX_INSERTION_LOSS_6G_BAND12,
     &g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX12][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX12][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX12]), OAL_FALSE},
    {"rf_rx_insertion_loss_6g_b13", WLAN_CFG_RF_RX_INSERTION_LOSS_6G_BAND13,
     &g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX13][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX13][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX13]), OAL_FALSE},
    {"rf_rx_insertion_loss_6g_b14", WLAN_CFG_RF_RX_INSERTION_LOSS_6G_BAND14,
     &g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX14][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX14][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rf_loss_gain_db.gain_db_6g[WLAN_6G_BAND_IDX14]), OAL_FALSE},
#endif
    /* 用于定制化计算PWR RF值的偏差 */
    {"rf_line_rf_pwr_ref_rssi_db_2g_20m_mult4", WLAN_CFG_RF_PWR_REF_RSSI_2G_20M_MULT4,
     &g_cust_rf_front.delta_pwr_ref.delta_rssi_2g[WLAN_2G_DELTA_RSSI_BAND_20M][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.delta_pwr_ref.delta_rssi_2g[0][0]),
     oal_array_size(g_cust_rf_front.delta_pwr_ref.delta_rssi_2g[WLAN_2G_DELTA_RSSI_BAND_20M]), OAL_FALSE},
    {"rf_line_rf_pwr_ref_rssi_db_2g_40m_mult4",  WLAN_CFG_RF_PWR_REF_RSSI_2G_40M_MULT4,
     &g_cust_rf_front.delta_pwr_ref.delta_rssi_2g[WLAN_2G_DELTA_RSSI_BAND_40M][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.delta_pwr_ref.delta_rssi_2g[1][0]),
     oal_array_size(g_cust_rf_front.delta_pwr_ref.delta_rssi_2g[WLAN_2G_DELTA_RSSI_BAND_40M]), OAL_FALSE},

    {"rf_line_rf_pwr_ref_rssi_db_5g_20m_mult4",  WLAN_CFG_RF_PWR_REF_RSSI_5G_20M_MULT4,
     &g_cust_rf_front.delta_pwr_ref.delta_rssi_5g[WLAN_5G_DELTA_RSSI_BAND_20M][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.delta_pwr_ref.delta_rssi_5g[WLAN_5G_DELTA_RSSI_BAND_20M][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.delta_pwr_ref.delta_rssi_5g[WLAN_5G_DELTA_RSSI_BAND_20M]), OAL_FALSE},
    {"rf_line_rf_pwr_ref_rssi_db_5g_40m_mult4",  WLAN_CFG_RF_PWR_REF_RSSI_5G_40M_MULT4,
     &g_cust_rf_front.delta_pwr_ref.delta_rssi_5g[WLAN_5G_DELTA_RSSI_BAND_40M][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.delta_pwr_ref.delta_rssi_5g[WLAN_5G_DELTA_RSSI_BAND_40M][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.delta_pwr_ref.delta_rssi_5g[WLAN_5G_DELTA_RSSI_BAND_40M]), OAL_FALSE},
    {"rf_line_rf_pwr_ref_rssi_db_5g_80m_mult4",  WLAN_CFG_RF_PWR_REF_RSSI_5G_80M_MULT4,
     &g_cust_rf_front.delta_pwr_ref.delta_rssi_5g[WLAN_5G_DELTA_RSSI_BAND_80M][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.delta_pwr_ref.delta_rssi_5g[WLAN_5G_DELTA_RSSI_BAND_80M][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.delta_pwr_ref.delta_rssi_5g[WLAN_5G_DELTA_RSSI_BAND_80M]), OAL_FALSE},
    {"rf_line_rf_pwr_ref_rssi_db_5g_160m_mult4",  WLAN_CFG_RF_PWR_REF_RSSI_5G_160M_MULT4,
     &g_cust_rf_front.delta_pwr_ref.delta_rssi_5g[WLAN_5G_DELTA_RSSI_BAND_160M][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.delta_pwr_ref.delta_rssi_5g[WLAN_5G_DELTA_RSSI_BAND_160M][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.delta_pwr_ref.delta_rssi_5g[WLAN_5G_DELTA_RSSI_BAND_160M]), OAL_FALSE},
#ifdef _PRE_WLAN_FEATURE_6G_EXTEND
    {"rf_line_rf_pwr_ref_rssi_db_6g_20m_mult4",  WLAN_CFG_RF_PWR_REF_RSSI_6G_20M_MULT4,
     &g_cust_rf_front.delta_pwr_ref.delta_rssi_6g[WLAN_5G_DELTA_RSSI_BAND_20M][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.delta_pwr_ref.delta_rssi_6g[WLAN_5G_DELTA_RSSI_BAND_20M][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.delta_pwr_ref.delta_rssi_6g[WLAN_5G_DELTA_RSSI_BAND_20M]), OAL_FALSE},
    {"rf_line_rf_pwr_ref_rssi_db_6g_40m_mult4",  WLAN_CFG_RF_PWR_REF_RSSI_6G_40M_MULT4,
     &g_cust_rf_front.delta_pwr_ref.delta_rssi_6g[WLAN_5G_DELTA_RSSI_BAND_40M][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.delta_pwr_ref.delta_rssi_6g[WLAN_5G_DELTA_RSSI_BAND_40M][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.delta_pwr_ref.delta_rssi_6g[WLAN_5G_DELTA_RSSI_BAND_40M]), OAL_FALSE},
    {"rf_line_rf_pwr_ref_rssi_db_6g_80m_mult4",  WLAN_CFG_RF_PWR_REF_RSSI_6G_80M_MULT4,
     &g_cust_rf_front.delta_pwr_ref.delta_rssi_6g[WLAN_5G_DELTA_RSSI_BAND_80M][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.delta_pwr_ref.delta_rssi_6g[WLAN_5G_DELTA_RSSI_BAND_80M][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.delta_pwr_ref.delta_rssi_6g[WLAN_5G_DELTA_RSSI_BAND_80M]), OAL_FALSE},
    {"rf_line_rf_pwr_ref_rssi_db_6g_160m_mult4",  WLAN_CFG_RF_PWR_REF_RSSI_6G_160M_MULT4,
     &g_cust_rf_front.delta_pwr_ref.delta_rssi_6g[WLAN_5G_DELTA_RSSI_BAND_160M][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.delta_pwr_ref.delta_rssi_6g[WLAN_5G_DELTA_RSSI_BAND_160M][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.delta_pwr_ref.delta_rssi_6g[WLAN_5G_DELTA_RSSI_BAND_160M]), OAL_FALSE},
#endif
    {"rf_rssi_amend_2g_20M", WLAN_CFG_RF_AMEND_RSSI_2G_20M,
     &g_cust_rf_front.rssi_amend_cfg.amend_rssi_2g[WLAN_2G_AMEND_RSSI_BAND_20M][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rssi_amend_cfg.amend_rssi_2g[WLAN_2G_AMEND_RSSI_BAND_20M][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rssi_amend_cfg.amend_rssi_2g[WLAN_2G_AMEND_RSSI_BAND_20M]), OAL_FALSE},
    {"rf_rssi_amend_2g_40M", WLAN_CFG_RF_AMEND_RSSI_2G_40M,
     &g_cust_rf_front.rssi_amend_cfg.amend_rssi_2g[WLAN_2G_AMEND_RSSI_BAND_40M][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rssi_amend_cfg.amend_rssi_2g[WLAN_2G_AMEND_RSSI_BAND_40M][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rssi_amend_cfg.amend_rssi_2g[WLAN_2G_AMEND_RSSI_BAND_40M]), OAL_FALSE},
    {"rf_rssi_amend_2g_11b", WLAN_CFG_RF_AMEND_RSSI_2G_11B,
     &g_cust_rf_front.rssi_amend_cfg.amend_rssi_2g[WLAN_2G_AMEND_RSSI_BAND_11B][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rssi_amend_cfg.amend_rssi_2g[WLAN_2G_AMEND_RSSI_BAND_11B][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rssi_amend_cfg.amend_rssi_2g[WLAN_2G_AMEND_RSSI_BAND_11B]), OAL_FALSE},

    {"rf_rssi_amend_5g_20M", WLAN_CFG_RF_AMEND_RSSI_5G_20M,
     &g_cust_rf_front.rssi_amend_cfg.amend_rssi_5g[WLAN_5G_AMEND_RSSI_BAND_20M][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rssi_amend_cfg.amend_rssi_5g[WLAN_5G_AMEND_RSSI_BAND_20M][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rssi_amend_cfg.amend_rssi_5g[WLAN_5G_AMEND_RSSI_BAND_20M]), OAL_FALSE},
    {"rf_rssi_amend_5g_40M", WLAN_CFG_RF_AMEND_RSSI_5G_40M,
     &g_cust_rf_front.rssi_amend_cfg.amend_rssi_5g[WLAN_5G_AMEND_RSSI_BAND_40M][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rssi_amend_cfg.amend_rssi_5g[WLAN_5G_AMEND_RSSI_BAND_40M][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rssi_amend_cfg.amend_rssi_5g[WLAN_5G_AMEND_RSSI_BAND_40M]), OAL_FALSE},
    {"rf_rssi_amend_5g_80M", WLAN_CFG_RF_AMEND_RSSI_5G_80M,
     &g_cust_rf_front.rssi_amend_cfg.amend_rssi_5g[WLAN_5G_AMEND_RSSI_BAND_80M][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rssi_amend_cfg.amend_rssi_5g[WLAN_5G_AMEND_RSSI_BAND_80M][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rssi_amend_cfg.amend_rssi_5g[WLAN_5G_AMEND_RSSI_BAND_80M]), OAL_FALSE},
    {"rf_rssi_amend_5g_160M", WLAN_CFG_RF_AMEND_RSSI_5G_160M,
     &g_cust_rf_front.rssi_amend_cfg.amend_rssi_5g[WLAN_5G_AMEND_RSSI_BAND_160M][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rssi_amend_cfg.amend_rssi_5g[WLAN_5G_AMEND_RSSI_BAND_160M][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rssi_amend_cfg.amend_rssi_5g[WLAN_5G_AMEND_RSSI_BAND_160M]), OAL_FALSE},
#ifdef _PRE_WLAN_FEATURE_6G_EXTEND
    {"rf_rssi_amend_6g_20M", WLAN_CFG_RF_AMEND_RSSI_6G_20M,
     &g_cust_rf_front.rssi_amend_cfg.amend_rssi_6g[WLAN_5G_AMEND_RSSI_BAND_20M][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rssi_amend_cfg.amend_rssi_6g[WLAN_5G_AMEND_RSSI_BAND_20M][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rssi_amend_cfg.amend_rssi_6g[WLAN_5G_AMEND_RSSI_BAND_20M]), OAL_FALSE},
    {"rf_rssi_amend_6g_40M", WLAN_CFG_RF_AMEND_RSSI_6G_40M,
     &g_cust_rf_front.rssi_amend_cfg.amend_rssi_6g[WLAN_5G_AMEND_RSSI_BAND_40M][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rssi_amend_cfg.amend_rssi_6g[WLAN_5G_AMEND_RSSI_BAND_40M][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rssi_amend_cfg.amend_rssi_6g[WLAN_5G_AMEND_RSSI_BAND_40M]), OAL_FALSE},
    {"rf_rssi_amend_6g_80M", WLAN_CFG_RF_AMEND_RSSI_6G_80M,
     &g_cust_rf_front.rssi_amend_cfg.amend_rssi_6g[WLAN_5G_AMEND_RSSI_BAND_80M][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rssi_amend_cfg.amend_rssi_6g[WLAN_5G_AMEND_RSSI_BAND_80M][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rssi_amend_cfg.amend_rssi_6g[WLAN_5G_AMEND_RSSI_BAND_80M]), OAL_FALSE},
    {"rf_rssi_amend_6g_160M", WLAN_CFG_RF_AMEND_RSSI_6G_160M,
     &g_cust_rf_front.rssi_amend_cfg.amend_rssi_6g[WLAN_5G_AMEND_RSSI_BAND_160M][WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.rssi_amend_cfg.amend_rssi_6g[WLAN_5G_AMEND_RSSI_BAND_160M][WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.rssi_amend_cfg.amend_rssi_6g[WLAN_5G_AMEND_RSSI_BAND_160M]), OAL_FALSE},
#endif

    /* fem */
    {"rf_lna_bypass_gain_db_2g", WLAN_CFG_RF_LNA_BYPASS_GAIN_DB_2G,
     &g_cust_rf_front.ext_rf[WLAN_CALI_BAND_2G].lna_bypass_gain_db[WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_2G].lna_bypass_gain_db[WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_2G].lna_bypass_gain_db), OAL_FALSE},
    {"rf_lna_gain_db_2g",        WLAN_CFG_RF_LNA_GAIN_DB_2G,
     &g_cust_rf_front.ext_rf[WLAN_CALI_BAND_2G].lna_gain_db[WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_2G].lna_gain_db[WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_2G].lna_gain_db), OAL_FALSE},
    {"rf_pa_db_b0_2g",           WLAN_CFG_RF_PA_GAIN_DB_B0_2G,
     &g_cust_rf_front.ext_rf[WLAN_CALI_BAND_2G].pa_gain_b0_db[WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_2G].pa_gain_b0_db[WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_2G].pa_gain_b0_db), OAL_FALSE},
    {"rf_pa_db_b1_2g",          WLAN_CFG_RF_PA_GAIN_DB_B1_2G,
     &g_cust_rf_front.ext_rf[WLAN_CALI_BAND_2G].pa_gain_b1_db[WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_2G].pa_gain_b1_db[WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_2G].pa_gain_b1_db), OAL_FALSE},
    {"rf_pa_db_lvl_2g",          WLAN_CFG_RF_PA_GAIN_LVL_2G,
     &g_cust_rf_front.ext_rf[WLAN_CALI_BAND_2G].pa_gain_lvl_num[WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_2G].pa_gain_lvl_num[WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_2G].pa_gain_lvl_num), OAL_FALSE},
    {"ext_switch_isexist_2g",    WLAN_CFG_EXT_SWITCH_ISEXIST_2G,
     &g_cust_rf_front.ext_rf[WLAN_CALI_BAND_2G].ext_switch_isexist[WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_2G].ext_switch_isexist[WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_2G].ext_switch_isexist), OAL_FALSE},
    {"ext_pa_isexist_2g",        WLAN_CFG_EXT_PA_ISEXIST_2G,
     &g_cust_rf_front.ext_rf[WLAN_CALI_BAND_2G].ext_pa_isexist[WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_2G].ext_pa_isexist[WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_2G].ext_pa_isexist), OAL_FALSE},
    {"ext_lna_isexist_2g",       WLAN_CFG_EXT_LNA_ISEXIST_2G,
     &g_cust_rf_front.ext_rf[WLAN_CALI_BAND_2G].ext_lna_isexist[WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_2G].ext_lna_isexist[WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_2G].ext_lna_isexist), OAL_FALSE},
    {"lna_on2off_time_ns_2g",    WLAN_CFG_LNA_ON2OFF_TIME_NS_2G,
     &g_cust_rf_front.ext_rf[WLAN_CALI_BAND_2G].lna_on2off_time_ns[WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_2G].lna_on2off_time_ns[WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_2G].lna_on2off_time_ns), OAL_FALSE},
    {"lna_off2on_time_ns_2g",    WLAN_CFG_LNA_OFF2ON_TIME_NS_2G,
     &g_cust_rf_front.ext_rf[WLAN_CALI_BAND_2G].lna_off2on_time_ns[WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_2G].lna_off2on_time_ns[WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_2G].lna_off2on_time_ns), OAL_FALSE},
    {"rf_lna_bypass_gain_db_5g", WLAN_CFG_RF_LNA_BYPASS_GAIN_DB_5G,
     &g_cust_rf_front.ext_rf[WLAN_CALI_BAND_5G].lna_bypass_gain_db[WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_5G].lna_bypass_gain_db[WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_5G].lna_bypass_gain_db), OAL_FALSE},
    {"rf_lna_gain_db_5g",        WLAN_CFG_RF_LNA_GAIN_DB_5G,
     &g_cust_rf_front.ext_rf[WLAN_CALI_BAND_5G].lna_gain_db[WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_5G].lna_gain_db[WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_5G].lna_gain_db), OAL_FALSE},
    {"rf_pa_db_b0_5g",           WLAN_CFG_RF_PA_GAIN_DB_B0_5G,
     &g_cust_rf_front.ext_rf[WLAN_CALI_BAND_5G].pa_gain_b0_db[WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_5G].pa_gain_b0_db[WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_5G].pa_gain_b0_db), OAL_FALSE},
    {"rf_pa_db_b1_5g",           WLAN_CFG_RF_PA_GAIN_DB_B1_5G,
     &g_cust_rf_front.ext_rf[WLAN_CALI_BAND_5G].pa_gain_b1_db[WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_5G].pa_gain_b1_db[WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_5G].pa_gain_b1_db), OAL_FALSE},
    {"rf_pa_db_lvl_5g",          WLAN_CFG_RF_PA_GAIN_LVL_5G,
     &g_cust_rf_front.ext_rf[WLAN_CALI_BAND_5G].pa_gain_lvl_num[WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_5G].pa_gain_lvl_num[WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_5G].pa_gain_lvl_num), OAL_FALSE},
    {"ext_switch_isexist_5g",    WLAN_CFG_EXT_SWITCH_ISEXIST_5G,
     &g_cust_rf_front.ext_rf[WLAN_CALI_BAND_5G].ext_switch_isexist[WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_5G].ext_switch_isexist[WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_5G].ext_switch_isexist), OAL_FALSE},
    {"ext_pa_isexist_5g",        WLAN_CFG_EXT_PA_ISEXIST_5G,
     &g_cust_rf_front.ext_rf[WLAN_CALI_BAND_5G].ext_pa_isexist[WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_5G].ext_pa_isexist[WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_5G].ext_pa_isexist), OAL_FALSE},
    {"ext_lna_isexist_5g",       WLAN_CFG_EXT_LNA_ISEXIST_5G,
     &g_cust_rf_front.ext_rf[WLAN_CALI_BAND_5G].ext_lna_isexist[WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_5G].ext_lna_isexist[WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_5G].ext_lna_isexist), OAL_FALSE},
    {"lna_on2off_time_ns_5g",    WLAN_CFG_LNA_ON2OFF_TIME_NS_5G,
     &g_cust_rf_front.ext_rf[WLAN_CALI_BAND_5G].lna_on2off_time_ns[WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_5G].lna_on2off_time_ns[WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_5G].lna_on2off_time_ns), OAL_FALSE},
    {"lna_off2on_time_ns_5g",    WLAN_CFG_LNA_OFF2ON_TIME_NS_5G,
     &g_cust_rf_front.ext_rf[WLAN_CALI_BAND_5G].lna_off2on_time_ns[WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_5G].lna_off2on_time_ns[WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_5G].lna_off2on_time_ns), OAL_FALSE},
#ifdef _PRE_WLAN_FEATURE_6G_EXTEND
    {"rf_lna_bypass_gain_db_6g", WLAN_CFG_RF_LNA_BYPASS_GAIN_DB_6G,
     &g_cust_rf_front.ext_rf[WLAN_CALI_BAND_6G].lna_bypass_gain_db[WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_6G].lna_bypass_gain_db[WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_6G].lna_bypass_gain_db), OAL_FALSE},
    {"rf_lna_gain_db_6g",        WLAN_CFG_RF_LNA_GAIN_DB_6G,
     &g_cust_rf_front.ext_rf[WLAN_CALI_BAND_6G].lna_gain_db[WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_6G].lna_gain_db[WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_6G].lna_gain_db), OAL_FALSE},
    {"rf_pa_db_b0_6g",           WLAN_CFG_RF_PA_GAIN_DB_B0_6G,
     &g_cust_rf_front.ext_rf[WLAN_CALI_BAND_6G].pa_gain_b0_db[WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_6G].pa_gain_b0_db[WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_6G].pa_gain_b0_db), OAL_FALSE},
    {"rf_pa_db_b1_6g",           WLAN_CFG_RF_PA_GAIN_DB_B1_6G,
     &g_cust_rf_front.ext_rf[WLAN_CALI_BAND_6G].pa_gain_b1_db[WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_6G].pa_gain_b1_db[WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_6G].pa_gain_b1_db), OAL_FALSE},
    {"rf_pa_db_lvl_6g",          WLAN_CFG_RF_PA_GAIN_LVL_6G,
     &g_cust_rf_front.ext_rf[WLAN_CALI_BAND_6G].pa_gain_lvl_num[WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_6G].pa_gain_lvl_num[WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_6G].pa_gain_lvl_num), OAL_FALSE},
    {"ext_switch_isexist_6g",    WLAN_CFG_EXT_SWITCH_ISEXIST_6G,
     &g_cust_rf_front.ext_rf[WLAN_CALI_BAND_6G].ext_switch_isexist[WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_6G].ext_switch_isexist[WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_6G].ext_switch_isexist), OAL_FALSE},
    {"ext_pa_isexist_6g",        WLAN_CFG_EXT_PA_ISEXIST_6G,
     &g_cust_rf_front.ext_rf[WLAN_CALI_BAND_6G].ext_pa_isexist[WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_6G].ext_pa_isexist[WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_6G].ext_pa_isexist), OAL_FALSE},
    {"ext_lna_isexist_6g",       WLAN_CFG_EXT_LNA_ISEXIST_6G,
     &g_cust_rf_front.ext_rf[WLAN_CALI_BAND_6G].ext_lna_isexist[WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_6G].ext_lna_isexist[WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_6G].ext_lna_isexist), OAL_FALSE},
    {"lna_on2off_time_ns_6g",    WLAN_CFG_LNA_ON2OFF_TIME_NS_6G,
     &g_cust_rf_front.ext_rf[WLAN_CALI_BAND_6G].lna_on2off_time_ns[WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_6G].lna_on2off_time_ns[WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_6G].lna_on2off_time_ns), OAL_FALSE},
    {"lna_off2on_time_ns_6g",    WLAN_CFG_LNA_OFF2ON_TIME_NS_6G,
     &g_cust_rf_front.ext_rf[WLAN_CALI_BAND_6G].lna_off2on_time_ns[WLAN_RF_CHANNEL_ZERO],
     sizeof(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_6G].lna_off2on_time_ns[WLAN_RF_CHANNEL_ZERO]),
     oal_array_size(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_6G].lna_off2on_time_ns), OAL_FALSE},
#endif
    {"fem_mode_2g",          WLAN_CFG_FEM_MODE_2G,
     &g_cust_rf_front.ext_rf[WLAN_CALI_BAND_2G].fem_mode,
     sizeof(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_2G].fem_mode), WLAN_CUST_NUM_1, OAL_FALSE},
    {"fem_mode_5g",          WLAN_CFG_FEM_MODE_5G,
     &g_cust_rf_front.ext_rf[WLAN_CALI_BAND_5G].fem_mode,
     sizeof(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_5G].fem_mode), WLAN_CUST_NUM_1, OAL_FALSE},
#ifdef _PRE_WLAN_FEATURE_6G_EXTEND
    {"fem_mode_6g",          WLAN_CFG_FEM_MODE_6G,
     &g_cust_rf_front.ext_rf[WLAN_CALI_BAND_6G].fem_mode,
     sizeof(g_cust_rf_front.ext_rf[WLAN_CALI_BAND_6G].fem_mode), WLAN_CUST_NUM_1, OAL_FALSE},
#endif
    {"delta_cca_ed_high_20th_2g", WLAN_CFG_DELTA_CCA_ED_HIGH_20TH_2G, &g_cust_rf_front.delta_cca_ed_high_20th_2g,
     sizeof(g_cust_rf_front.delta_cca_ed_high_20th_2g), WLAN_CUST_NUM_1, OAL_FALSE},
    {"delta_cca_ed_high_40th_2g", WLAN_CFG_DELTA_CCA_ED_HIGH_40TH_2G, &g_cust_rf_front.delta_cca_ed_high_40th_2g,
     sizeof(g_cust_rf_front.delta_cca_ed_high_40th_2g), WLAN_CUST_NUM_1, OAL_FALSE},
    {"delta_cca_ed_high_20th_5g", WLAN_CFG_DELTA_CCA_ED_HIGH_20TH_5G, &g_cust_rf_front.delta_cca_ed_high_20th_5g,
     sizeof(g_cust_rf_front.delta_cca_ed_high_20th_5g), WLAN_CUST_NUM_1, OAL_FALSE},
    {"delta_cca_ed_high_40th_5g", WLAN_CFG_DELTA_CCA_ED_HIGH_40TH_5G, &g_cust_rf_front.delta_cca_ed_high_40th_5g,
     sizeof(g_cust_rf_front.delta_cca_ed_high_40th_5g), WLAN_CUST_NUM_1, OAL_FALSE},
    {"delta_cca_ed_high_80th_5g", WLAN_CFG_DELTA_CCA_ED_HIGH_80TH_5G, &g_cust_rf_front.delta_cca_ed_high_80th_5g,
     sizeof(g_cust_rf_front.delta_cca_ed_high_80th_5g), WLAN_CUST_NUM_1, OAL_FALSE},
#ifdef _PRE_WLAN_FEATURE_6G_EXTEND
    {"delta_cca_ed_high_20th_6g", WLAN_CFG_DELTA_CCA_ED_HIGH_20TH_6G, &g_cust_rf_front.delta_cca_ed_high_20th_6g,
     sizeof(g_cust_rf_front.delta_cca_ed_high_20th_6g), WLAN_CUST_NUM_1, OAL_FALSE},
    {"delta_cca_ed_high_40th_6g", WLAN_CFG_DELTA_CCA_ED_HIGH_40TH_6G, &g_cust_rf_front.delta_cca_ed_high_40th_6g,
     sizeof(g_cust_rf_front.delta_cca_ed_high_40th_6g), WLAN_CUST_NUM_1, OAL_FALSE},
    {"delta_cca_ed_high_80th_6g", WLAN_CFG_DELTA_CCA_ED_HIGH_80TH_6G, &g_cust_rf_front.delta_cca_ed_high_80th_6g,
     sizeof(g_cust_rf_front.delta_cca_ed_high_80th_6g), WLAN_CUST_NUM_1, OAL_FALSE},
#endif
};

wlan_cust_cfg_cmd g_wifi_cfg_cap[WLAN_CFG_CAP_BUTT] = {
    /* 校准开关 */
    {"cali_policy", WLAN_CFG_CAP_CALI_POLICY, &g_cust_cap.cali_policy, sizeof(g_cust_cap.cali_policy),
     WLAN_CUST_NUM_1, OAL_FALSE},
    {"cali_mask_2g", WLAN_CFG_CAP_CALI_MASK_2G, &g_cust_cap.cali_switch.cali_mask[WLAN_CALI_BAND_2G],
     sizeof(g_cust_cap.cali_switch.cali_mask[WLAN_CALI_BAND_2G]), WLAN_CUST_NUM_1, OAL_FALSE},
    {"cali_mask_5g", WLAN_CFG_CAP_CALI_MASK_5G, &g_cust_cap.cali_switch.cali_mask[WLAN_CALI_BAND_5G],
     sizeof(g_cust_cap.cali_switch.cali_mask[WLAN_CALI_BAND_5G]), WLAN_CUST_NUM_1, OAL_FALSE},
#ifdef _PRE_WLAN_FEATURE_6G_EXTEND
    {"cali_mask_6g", WLAN_CFG_CAP_CALI_MASK_6G, &g_cust_cap.cali_switch.cali_mask[WLAN_CALI_BAND_6G],
     sizeof(g_cust_cap.cali_switch.cali_mask[WLAN_CALI_BAND_6G]), WLAN_CUST_NUM_1, OAL_FALSE},
#endif
    {"online_cali_mask", WLAN_CFG_CAP_CALI_ONLINE_MASK, &g_cust_cap.cali_switch.online_cali_mask,
     sizeof(g_cust_cap.cali_switch.online_cali_mask), WLAN_CUST_NUM_1, OAL_FALSE},
    {"dpd_module_mask", WLAN_CFG_CAP_CALI_DPD_MODULE_MASK, &g_cust_cap.cali_switch.dpd_module_mask,
     sizeof(g_cust_cap.cali_switch.dpd_module_mask), WLAN_CUST_NUM_1, OAL_FALSE},
    {"dpd_cali_lvl_num", WLAN_CFG_CAP_CALI_DPD_CALI_LVL_NUM, &g_cust_cap.cali_switch.dpd_cali_lvl_num,
     sizeof(g_cust_cap.cali_switch.dpd_cali_lvl_num), WLAN_CUST_NUM_1, OAL_FALSE},
    /*
     * #bit0:开wifi重新校准 bit1:开wifi重新上传 bit2:开机校准 bit3:动态校准调平Debug
     * #bit4:不读取NV区域的数据(1:不读取 0：读取)
     */
    {"cali_data_mask", WLAN_CFG_CAP_CALI_DATA_MASK,
     &g_cust_cap.cali_data_mask, sizeof(g_cust_cap.cali_data_mask), WLAN_CUST_NUM_1, OAL_FALSE},
    {"bw_max_width", WLAN_CFG_CAP_BW_MAX_WITH,
     &g_cust_cap.en_channel_width, sizeof(g_cust_cap.en_channel_width), WLAN_CUST_NUM_1, OAL_FALSE},
    {"ldpc_coding",  WLAN_CFG_CAP_LDPC_CODING,
     &g_cust_cap.en_ldpc_is_supp, sizeof(g_cust_cap.en_ldpc_is_supp), WLAN_CUST_NUM_1, OAL_FALSE},
    {"rx_stbc",      WLAN_CFG_CAP_RX_STBC,
      &g_cust_cap.en_rx_stbc_is_supp, sizeof(g_cust_cap.en_rx_stbc_is_supp), WLAN_CUST_NUM_1, OAL_FALSE},
    {"tx_stbc",      WLAN_CFG_CAP_TX_STBC,
     &g_cust_cap.en_tx_stbc_is_supp, sizeof(g_cust_cap.en_tx_stbc_is_supp), WLAN_CUST_NUM_1, OAL_FALSE},
    {"su_bfer",      WLAN_CFG_CAP_SU_BFER,
     &g_cust_cap.en_su_bfmer_is_supp, sizeof(g_cust_cap.en_su_bfmer_is_supp), WLAN_CUST_NUM_1, OAL_FALSE},
    {"su_bfee",      WLAN_CFG_CAP_SU_BFEE,
     &g_cust_cap.en_su_bfmee_is_supp, sizeof(g_cust_cap.en_su_bfmee_is_supp), WLAN_CUST_NUM_1, OAL_FALSE},
    {"mu_bfer",      WLAN_CFG_CAP_MU_BFER,
     &g_cust_cap.en_mu_bfmer_is_supp, sizeof(g_cust_cap.en_mu_bfmer_is_supp), WLAN_CUST_NUM_1, OAL_FALSE},
    {"mu_bfee",      WLAN_CFG_CAP_MU_BFEE,
     &g_cust_cap.en_mu_bfmee_is_supp, sizeof(g_cust_cap.en_mu_bfmee_is_supp), WLAN_CUST_NUM_1, OAL_FALSE},
    {"hisi_priv_cap", WLAN_CFG_CAP_HISI_PRIV_IE,
     &g_cust_cap.hisi_priv_cap, sizeof(g_cust_cap.hisi_priv_cap), WLAN_CUST_NUM_1, OAL_FALSE},
    {"voe_switch_mask",           WLAN_CFG_CAP_VOE_SWITCH, &g_cust_cap.voe_switch_mask,
     sizeof(g_cust_cap.voe_switch_mask),   WLAN_CUST_NUM_1, OAL_FALSE},
    {"11ax_switch_mask",          WLAN_CFG_CAP_11AX_SWITCH, &g_cust_cap.wifi_11ax_switch_mask,
     sizeof(g_cust_cap.wifi_11ax_switch_mask),   WLAN_CUST_NUM_1, OAL_FALSE},
    {"htc_switch_mask",           WLAN_CFG_CAP_HTC_SWITCH, &g_cust_cap.htc_switch_mask,
     sizeof(g_cust_cap.htc_switch_mask),   WLAN_CUST_NUM_1, OAL_FALSE},
    {"multi_bssid_switch_mask",   WLAN_CFG_CAP_MULTI_BSSID_SWITCH, &g_cust_cap.mult_bssid_switch_mask,
     sizeof(g_cust_cap.mult_bssid_switch_mask),   WLAN_CUST_NUM_1, OAL_FALSE},
    {"dynamic_dbac_adjust_mask", WLAN_CFG_CAP_DYNAMIC_DBAC_SWITCH, &g_cust_cap.dbac_dynamic_switch,
     sizeof(g_cust_cap.dbac_dynamic_switch),   WLAN_CUST_NUM_1, OAL_FALSE},
    {"mcast_ampdu_enable",           WLAN_CFG_CAP_MCAST_AMPDU_ENABLE, &g_cust_cap.mcast_ampdu_enable,
     sizeof(g_cust_cap.mcast_ampdu_enable),   WLAN_CUST_NUM_1, OAL_FALSE},
    {"pt_mcast_enable",           WLAN_CFG_CAP_PT_MCAST_ENABLE, &g_cust_cap.pt_mcast_enable,
     sizeof(g_cust_cap.pt_mcast_enable),   WLAN_CUST_NUM_1, OAL_FALSE},
    /* DBDC */
    {"radio_cap",     WLAN_CFG_CAP_DBDC_RADIO,
     &g_cust_cap.radio_cap[0], sizeof(g_cust_cap.radio_cap[0]), oal_array_size(g_cust_cap.radio_cap), OAL_FALSE},
    {"dbdc_cap",     WLAN_CFG_CAP_DBDC,
     &g_cust_cap.dbdc_cap, sizeof(g_cust_cap.dbdc_cap), WLAN_CUST_NUM_1, OAL_FALSE},
    {"fastscan_switch", WLAN_CFG_CAP_FASTSCAN_SWITCH,
     &g_cust_cap.fastscan_switch, sizeof(g_cust_cap.fastscan_switch), WLAN_CUST_NUM_1, OAL_FALSE},
    {"device_access_ddr", WLAN_CFG_CAP_DEVICE_ACCESS_DDR,
     &g_cust_cap.device_access_ddr, sizeof(g_cust_cap.device_access_ddr), WLAN_CUST_NUM_1, OAL_FALSE},
    /* RSSI天线切换 */
    {"rssi_ant_switch", WLAN_CFG_CAP_ANT_SWITCH,
     &g_cust_cap.rssi_switch_ant, sizeof(g_cust_cap.rssi_switch_ant), WLAN_CUST_NUM_1, OAL_FALSE},
     /* 国家码自学习功能开关 */
    {"countrycode_selfstudy", WLAN_CFG_CAP_COUNRTYCODE_SELFSTUDY_CFG,
     &g_cust_cap.country_self_study, sizeof(g_cust_cap.country_self_study), WLAN_CUST_NUM_1, OAL_FALSE},
     /* 多通道退化能力 */
    {"degrade_cap", WLAN_CFG_CAP_DEGRADATION_CAP,
     &g_cust_cap.degrade_cap, sizeof(g_cust_cap.degrade_cap), WLAN_CUST_NUM_1, OAL_FALSE},

    /* dyn_pcie_switch */
    {"dyn_pcie_switch", WLAN_CFG_DYN_PCIE_SWITCH_CAP,
    &g_cust_cap.dyn_pcie_switch, sizeof(g_cust_cap.dyn_pcie_switch), WLAN_CUST_NUM_1, OAL_FALSE},
    /* MCM */
    {"chann_radio_cap", WLAN_CFG_CAP_RADIO_CAP,
    &g_cust_cap.chn_radio_cap, sizeof(g_cust_cap.chn_radio_cap), WLAN_CUST_NUM_1, OAL_FALSE},
    {"chann_radio_cap_6g", WLAN_CFG_CAP_RADIO_CAP_6G, &g_cust_cap.chn_radio_cap_6g,
     sizeof(g_cust_cap.chn_radio_cap_6g), WLAN_CUST_NUM_1, OAL_FALSE},
    {"mcm_custom_function_mask", WLAN_CFG_CAP_MCM_CUSTOM_FUNCTION_MASK,
     &g_cust_cap.mcm_custom_func_mask, sizeof(g_cust_cap.mcm_custom_func_mask), WLAN_CUST_NUM_1, OAL_FALSE},
    {"mcm_function_mask", WLAN_CFG_CAP_MCM_FUNCTION_MASK,
     &g_cust_cap.mcm_func_mask, sizeof(g_cust_cap.mcm_func_mask), WLAN_CUST_NUM_1, OAL_FALSE},
    {"linkloss_threshold_fixed", WLAN_CFG_CAP_LINKLOSS_THRESHOLD_FIXED,
     &g_cust_cap.linkloss_threshold_fixed, sizeof(g_cust_cap.linkloss_threshold_fixed), WLAN_CUST_NUM_1, OAL_FALSE},
    {"aput_support_160m", WLAN_CFG_CAP_APUT_160M_ENABLE,
     &g_cust_cap.aput_160m_switch, sizeof(g_cust_cap.aput_160m_switch), WLAN_CUST_NUM_1, OAL_FALSE},
    {"radar_isr_forbid", WLAN_CFG_CAP_RADAR_ISR_FORBID,
     &g_cust_cap.radar_isr_forbid, sizeof(g_cust_cap.radar_isr_forbid), WLAN_CUST_NUM_1, OAL_FALSE},
#ifdef _PRE_WLAN_FEATURE_TXOPPS
    {"txopps_switch", WLAN_CFG_CAP_TXOPPS_SWITCH,
     &g_cust_cap.txopps_switch, sizeof(g_cust_cap.txopps_switch), WLAN_CUST_NUM_1, OAL_FALSE},
#endif
    {"over_temper_protect_threshold",   WLAN_CFG_CAP_OVER_TEMPER_PROTECT_THRESHOLD,
     &g_cust_cap.over_temper_protect.over_temper_protect_th,
     sizeof(g_cust_cap.over_temper_protect.over_temper_protect_th), WLAN_CUST_NUM_1, OAL_FALSE},
    {"over_temp_pro_enable", WLAN_CFG_CAP_OVER_TEMP_PRO_ENABLE,
     &g_cust_cap.over_temper_protect.en_over_temp_pro,
     sizeof(g_cust_cap.over_temper_protect.en_over_temp_pro), WLAN_CUST_NUM_1, OAL_FALSE},
    {"over_temp_pro_reduce_pwr_enable", WLAN_CFG_CAP_OVER_TEMP_PRO_REDUCE_PWR_ENABLE,
     &g_cust_cap.over_temper_protect.en_reduce_pwr,
     sizeof(g_cust_cap.over_temper_protect.en_reduce_pwr), WLAN_CUST_NUM_1, OAL_FALSE},
    {"over_temp_pro_safe_th", WLAN_CFG_CAP_OVER_TEMP_PRO_SAFE_TH,
     &g_cust_cap.over_temper_protect.over_temp_pro_safe_th,
     sizeof(g_cust_cap.over_temper_protect.over_temp_pro_safe_th), WLAN_CUST_NUM_1, OAL_FALSE},
    {"over_temp_pro_over_th", WLAN_CFG_CAP_OVER_TEMP_PRO_OVER_TH,
     &g_cust_cap.over_temper_protect.over_temp_pro_over_th,
     sizeof(g_cust_cap.over_temper_protect.over_temp_pro_over_th), WLAN_CUST_NUM_1, OAL_FALSE},
    {"over_temp_pro_pa_off_th", WLAN_CFG_CAP_OVER_TEMP_PRO_PA_OFF_TH,
     &g_cust_cap.over_temper_protect.over_temp_pro_pa_off_th,
     sizeof(g_cust_cap.over_temper_protect.over_temp_pro_pa_off_th), WLAN_CUST_NUM_1, OAL_FALSE},
    {"alg_switch_ini", WLAN_CFG_CAP_ALG_SWITCH,
     &g_cust_cap.alg_switch_ini, sizeof(g_cust_cap.alg_switch_ini), WLAN_CUST_NUM_1, OAL_FALSE},

    {"dsss2ofdm_dbb_pwr_bo_val",   WLAN_CAP_DSSS2OFDM_DBB_PWR_BO_VAL,
     &g_cust_cap.dsss2ofdm_dbb_pwr_bo_val, sizeof(g_cust_cap.dsss2ofdm_dbb_pwr_bo_val), WLAN_CUST_NUM_1, OAL_FALSE},
    {"evm_fail_pll_reg_fix",       WLAN_CFG_CAP_EVM_PLL_REG_FIX,
     &g_cust_cap.evm_pll_reg_fix, sizeof(g_cust_cap.evm_pll_reg_fix), WLAN_CUST_NUM_1, OAL_FALSE},
    {"ac_priv_mask", WLAN_CFG_CAP_AC_SUSPEND,
     &g_cust_cap.ac_suspend_mask, sizeof(g_cust_cap.ac_suspend_mask), WLAN_CUST_NUM_1, OAL_FALSE},
    {"dyn_bypass_extlna_enable", WLAN_CFG_CAP_DYN_BYPASS_EXTLNA,
     &g_cust_cap.dyn_extlna_bypass, sizeof(g_cust_cap.dyn_extlna_bypass), WLAN_CUST_NUM_1, OAL_FALSE},
    {"ctrl_frame_tx_chain", WLAN_CFG_CAP_CTRL_FRAME_TX_CHAIN,
     &g_cust_cap.frame_tx_chain_ctl, sizeof(g_cust_cap.frame_tx_chain_ctl), WLAN_CUST_NUM_1, OAL_FALSE},
    {"11b_double_chain_bo_pow", WLAN_CFG_CAP_CTRL_11B_DOUBLE_CHAIN_BO_POW,
     &g_cust_cap.double_chain_11b_bo_pow, sizeof(g_cust_cap.double_chain_11b_bo_pow), WLAN_CUST_NUM_1, OAL_FALSE},
    {"hcc_flowctrl_type",  WLAN_CFG_CAP_HCC_FLOWCTRL_TYPE,
     &g_cust_cap.hcc_flowctrl_type, sizeof(g_cust_cap.hcc_flowctrl_type), WLAN_CUST_NUM_1, OAL_FALSE},
#ifdef _PRE_WLAN_FEATURE_MBO
    {"mbo_switch_mask", WLAN_CFG_CAP_MBO_SWITCH, &g_cust_cap.mbo_switch,
     sizeof(g_cust_cap.mbo_switch),   WLAN_CUST_NUM_1, OAL_FALSE},
#endif

    {"dc_flowctl_switch", WLAN_CFG_CAP_DC_FLOWCTL_SWITCH,
     &g_cust_cap.dc_flowctl_switch, sizeof(g_cust_cap.dc_flowctl_switch), WLAN_CUST_NUM_1, OAL_FALSE},
    {"phy_cap_mask", WLAN_CFG_CAP_PHY_CAP_SWITCH,
     &g_cust_cap.phy_cap_mask, sizeof(g_cust_cap.phy_cap_mask), WLAN_CUST_NUM_1, OAL_FALSE},
    {"hal_ps_rssi_param",          WLAN_CFG_CAP_HAL_PS_RSSI_PARAM,
     &g_cust_cap.ps_rssi_param, sizeof(g_cust_cap.ps_rssi_param), WLAN_CUST_NUM_1, OAL_FALSE},
    {"hal_ps_pps_param",           WLAN_CFG_CAP_HAL_PS_PPS_PARAM,
     &g_cust_cap.ps_pps_param, sizeof(g_cust_cap.ps_pps_param), WLAN_CUST_NUM_1, OAL_FALSE},

    {"hiex_cap", WLAN_CFG_CAP_HIEX_CAP, &g_cust_cap.hiex_cap,
     sizeof(g_cust_cap.hiex_cap),   WLAN_CUST_NUM_1, OAL_FALSE},

    {"fem_backoff_pow", WLAN_CFG_CAP_FEM_DELT_POW, g_cust_cap.fem_pow.fem_delt_pow,
     sizeof(g_cust_cap.fem_pow.fem_delt_pow[0]), oal_array_size(g_cust_cap.fem_pow.fem_delt_pow), OAL_FALSE},
    {"tpc_adj_pow_start_idx_by_fem", WLAN_CFG_CAP_FEM_ADJ_TPC_TBL_START_IDX, g_cust_cap.fem_pow.tpc_adj_pow_start_idx,
     sizeof(g_cust_cap.fem_pow.tpc_adj_pow_start_idx[0]),
     oal_array_size(g_cust_cap.fem_pow.tpc_adj_pow_start_idx), OAL_FALSE},
    {"powermgmt_switch", WLAN_CFG_CAP_POWERMGMT_SWITCH,
    &g_cust_cap.wlan_device_pm_switch, sizeof(g_cust_cap.wlan_device_pm_switch), WLAN_CUST_NUM_1, OAL_FALSE},
    {"lowpower_agent_switch", WLAN_CFG_INIT_LOWPOWER_AGENT_SWITCH,
    &g_cust_cap.wlan_device_lp_agent_switch, sizeof(g_cust_cap.wlan_device_lp_agent_switch),
    WLAN_CUST_NUM_1, OAL_FALSE},
    {"min_fast_ps_idle", WLAN_CFG_CAP_MIN_FAST_PS_IDLE,
     &g_cust_cap.fast_ps.wlan_min_fast_ps_idle,
     sizeof(g_cust_cap.fast_ps.wlan_min_fast_ps_idle), WLAN_CUST_NUM_1, OAL_FALSE},
    {"max_fast_ps_idle", WLAN_CFG_CAP_MAX_FAST_PS_IDLE,
     &g_cust_cap.fast_ps.wlan_max_fast_ps_idle,
     sizeof(g_cust_cap.fast_ps.wlan_max_fast_ps_idle), WLAN_CUST_NUM_1, OAL_FALSE},
    {"auto_fast_ps_thresh_screen_on",  WLAN_CFG_CAP_AUTO_FAST_PS_THRESH_SCREENON,
     &g_cust_cap.fast_ps.wlan_auto_ps_thresh_screen_on,
     sizeof(g_cust_cap.fast_ps.wlan_auto_ps_thresh_screen_on), WLAN_CUST_NUM_1, OAL_FALSE},
    {"auto_fast_ps_thresh_screen_off", WLAN_CFG_CAP_AUTO_FAST_PS_THRESH_SCREENOFF,
     &g_cust_cap.fast_ps.wlan_auto_ps_thresh_screen_off,
     sizeof(g_cust_cap.fast_ps.wlan_auto_ps_thresh_screen_off), WLAN_CUST_NUM_1, OAL_FALSE},
    {"close_filter_switch", WLAN_CFG_CAP_CLOSE_FILTER_SWITCH,
     &g_cust_cap.close_filter_switch, sizeof(g_cust_cap.close_filter_switch), WLAN_CUST_NUM_1, OAL_FALSE},

    /* 可维可测 */
    {"loglevel", WLAN_CFG_CAP_LOGLEVEL,
     &g_cust_cap.loglevel, sizeof(g_cust_cap.loglevel), WLAN_CUST_NUM_1, OAL_FALSE},
    {"used_mem_for_start",      WLAN_CFG_CAP_USED_MEM_FOR_START,
     &g_cust_cap.used_mem_for_start, sizeof(g_cust_cap.used_mem_for_start), WLAN_CUST_NUM_1, OAL_FALSE},
    {"used_mem_for_stop", WLAN_CFG_CAP_USED_MEM_FOR_STOP,
     &g_cust_cap.used_mem_for_stop, sizeof(g_cust_cap.used_mem_for_stop), WLAN_CUST_NUM_1, OAL_FALSE},
    {"sdio_d2h_assemble_count", WLAN_CFG_CAP_SDIO_D2H_ASSEMBLE_COUNT,
     &g_cust_cap.sdio_assem_d2h, sizeof(g_cust_cap.sdio_assem_d2h), WLAN_CUST_NUM_1, OAL_FALSE},
    {"sdio_h2d_assemble_count", WLAN_CFG_CAP_SDIO_H2D_ASSEMBLE_COUNT,
     &g_cust_cap.sdio_assem_h2d, sizeof(g_cust_cap.sdio_assem_h2d), WLAN_CUST_NUM_1, OAL_FALSE},
    /* LINKLOSS */
    {"link_loss_threshold_bt",     WLAN_CFG_CAP_LINK_LOSS_THRESHOLD_BT,
     &g_cust_cap.linkloss_th[WLAN_LINKLOSS_MODE_BT],
     sizeof(g_cust_cap.linkloss_th[WLAN_LINKLOSS_MODE_BT]), WLAN_CUST_NUM_1, OAL_FALSE},
    {"link_loss_threshold_dbac",   WLAN_CFG_CAP_LINK_LOSS_THRESHOLD_DBAC,
     &g_cust_cap.linkloss_th[WLAN_LINKLOSS_MODE_DBAC],
     sizeof(g_cust_cap.linkloss_th[WLAN_LINKLOSS_MODE_DBAC]), WLAN_CUST_NUM_1, OAL_FALSE},
    {"link_loss_threshold_normal", WLAN_CFG_CAP_LINK_LOSS_THRESHOLD_NORMAL,
     &g_cust_cap.linkloss_th[WLAN_LINKLOSS_MODE_NORMAL],
     sizeof(g_cust_cap.linkloss_th[WLAN_LINKLOSS_MODE_NORMAL]), WLAN_CUST_NUM_1, OAL_FALSE},

    /* 自动调频 */
    {"pss_threshold_level_0",  WLAN_CFG_CAP_PSS_THRESHOLD_LEVEL_0,
     &g_cust_cap.dev_frequency[DEV_WORK_FREQ_LVL0].speed_level,
     sizeof(g_cust_cap.dev_frequency[DEV_WORK_FREQ_LVL0].speed_level), WLAN_CUST_NUM_1, OAL_FALSE},
    {"pss_threshold_level_1",  WLAN_CFG_CAP_PSS_THRESHOLD_LEVEL_1,
     &g_cust_cap.dev_frequency[DEV_WORK_FREQ_LVL1].speed_level,
     sizeof(g_cust_cap.dev_frequency[DEV_WORK_FREQ_LVL1].speed_level), WLAN_CUST_NUM_1, OAL_FALSE},
    {"pss_threshold_level_2",  WLAN_CFG_CAP_PSS_THRESHOLD_LEVEL_2,
     &g_cust_cap.dev_frequency[DEV_WORK_FREQ_LVL2].speed_level,
     sizeof(g_cust_cap.dev_frequency[DEV_WORK_FREQ_LVL2].speed_level), WLAN_CUST_NUM_1, OAL_FALSE},
    {"pss_threshold_level_3",  WLAN_CFG_CAP_PSS_THRESHOLD_LEVEL_3,
     &g_cust_cap.dev_frequency[DEV_WORK_FREQ_LVL3].speed_level,
      sizeof(g_cust_cap.dev_frequency[DEV_WORK_FREQ_LVL3].speed_level), WLAN_CUST_NUM_1, OAL_FALSE},

    {"device_type_level_0",    WLAN_CFG_CAP_DEVICE_TYPE_LEVEL_0,
     &g_cust_cap.dev_frequency[DEV_WORK_FREQ_LVL0].cpu_freq_type,
     sizeof(g_cust_cap.dev_frequency[DEV_WORK_FREQ_LVL0].cpu_freq_type), WLAN_CUST_NUM_1, OAL_FALSE},
    {"device_type_level_1",    WLAN_CFG_CAP_DEVICE_TYPE_LEVEL_1,
     &g_cust_cap.dev_frequency[DEV_WORK_FREQ_LVL1].cpu_freq_type,
     sizeof(g_cust_cap.dev_frequency[DEV_WORK_FREQ_LVL1].cpu_freq_type), WLAN_CUST_NUM_1, OAL_FALSE},
    {"device_type_level_2",    WLAN_CFG_CAP_DEVICE_TYPE_LEVEL_2,
     &g_cust_cap.dev_frequency[DEV_WORK_FREQ_LVL2].cpu_freq_type,
     sizeof(g_cust_cap.dev_frequency[DEV_WORK_FREQ_LVL2].cpu_freq_type), WLAN_CUST_NUM_1, OAL_FALSE},
    {"device_type_level_3",    WLAN_CFG_CAP_DEVICE_TYPE_LEVEL_3,
     &g_cust_cap.dev_frequency[DEV_WORK_FREQ_LVL3].cpu_freq_type,
     sizeof(g_cust_cap.dev_frequency[DEV_WORK_FREQ_LVL3].cpu_freq_type), WLAN_CUST_NUM_1, OAL_FALSE},
    /* btcoex mcm rssi */
    {"btcoex_threshold_mcm_down", WLAN_CFG_CAP_BTCOEX_THRESHOLD_MCM_DOWN,
     &g_cust_cap.btcoex_threshold_mcm[WLAN_BTCOEX_RSSI_MCM_DOWN],
     sizeof(g_cust_cap.btcoex_threshold_mcm[WLAN_BTCOEX_RSSI_MCM_DOWN]), WLAN_CUST_NUM_1, OAL_FALSE},
    {"btcoex_threshold_mcm_up",   WLAN_CFG_CAP_BTCOEX_THRESHOLD_MCM_UP,
     &g_cust_cap.btcoex_threshold_mcm[WLAN_BTCOEX_RSSI_MCM_UP],
     sizeof(g_cust_cap.btcoex_threshold_mcm[WLAN_BTCOEX_RSSI_MCM_UP]), WLAN_CUST_NUM_1, OAL_FALSE},
    {"ftm_cap", WLAN_CFG_CAP_FTM, &g_cust_cap.ftm_cap, sizeof(g_cust_cap.ftm_cap), WLAN_CUST_NUM_1, OAL_FALSE},
    {"ftm_board_delay", WLAN_CFG_CAP_FTM_BOARD_DELAY, &g_cust_cap.ftm_board_delay,
     sizeof(g_cust_cap.ftm_board_delay), WLAN_CUST_NUM_1, OAL_FALSE},

    {"only_fast_mode", WLAN_CFG_CAP_FAST_MODE, &g_cust_cap.fast_mode,
     sizeof(g_cust_cap.fast_mode), WLAN_CUST_NUM_1, OAL_FALSE},
    {"trx_switch", WLAN_CFG_CAP_TRX_SWITCH, &g_cust_cap.trx_switch, sizeof(g_cust_cap.trx_switch),
     WLAN_CUST_NUM_1, OAL_FALSE},

#ifdef _PRE_WLAN_FEATURE_NRCOEX
    { "nrcoex_enable", WLAN_CFG_CAP_NRCOEX_ENABLE, &g_cust_cap.nrcoex_params.nrcoex_switch,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_switch), WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_version", WLAN_CFG_CAP_NRCOEX_VERSION, &g_cust_cap.nrcoex_params.version_num,
      sizeof(g_cust_cap.nrcoex_params.version_num), WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_hw", WLAN_CFG_CAP_NRCOEX_HW, &g_cust_cap.nrcoex_params.nrcoex_hw,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_hw), WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_advance_low_power", WLAN_CFG_CAP_NRCOEX_ADVANCE_LOW_POWER, &g_cust_cap.nrcoex_params.advance_low_power,
      sizeof(g_cust_cap.nrcoex_params.advance_low_power), WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule0_freq", WLAN_CFG_CAP_NRCOEX_RULE0_FREQ,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_0].freq,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_0].freq), WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule0_40m_20m_gap0", WLAN_CFG_CAP_NRCOEX_RULE0_40M_20M_GAP0,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_0].relative_freq_gap0_40_20,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_0].relative_freq_gap0_40_20),
      WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule0_160m_80m_gap0", WLAN_CFG_CAP_NRCOEX_RULE0_160M_80M_GAP0,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_0].relative_freq_gap0_160_80,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_0].relative_freq_gap0_160_80),
      WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule0_40m_20m_gap1", WLAN_CFG_CAP_NRCOEX_RULE0_40M_20M_GAP1,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_0].relative_freq_gap1_40_20,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_0].relative_freq_gap1_40_20),
      WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule0_160m_80m_gap1", WLAN_CFG_CAP_NRCOEX_RULE0_160M_80M_GAP1,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_0].relative_freq_gap1_160_80,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_0].relative_freq_gap1_160_80),
      WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule0_40m_20m_gap2", WLAN_CFG_CAP_NRCOEX_RULE0_40M_20M_GAP2,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_0].relative_freq_gap2_40_20,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_0].relative_freq_gap2_40_20),
      WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule0_160m_80m_gap2", WLAN_CFG_CAP_NRCOEX_RULE0_160M_80M_GAP2,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_0].relative_freq_gap2_160_80,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_0].relative_freq_gap2_160_80),
      WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule0_smallgap0_act", WLAN_CFG_CAP_NRCOEX_RULE0_SMALLGAP0_ACT,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_0].limit_power_level0,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_0].limit_power_level0), WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule0_gap01_act", WLAN_CFG_CAP_NRCOEX_RULE0_GAP01_ACT,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_0].limit_power_level1,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_0].limit_power_level1), WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule0_gap12_act", WLAN_CFG_CAP_NRCOEX_RULE0_GAP12_ACT,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_0].limit_power_level2,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_0].limit_power_level2), WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule0_rxslot_rssi", WLAN_CFG_CAP_NRCOEX_RULE0_RXSLOT_RSSI,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_0].rssi_threshold,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_0].rssi_threshold), WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule1_freq", WLAN_CFG_CAP_NRCOEX_RULE1_FREQ,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_1].freq,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_1].freq), WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule1_40m_20m_gap0", WLAN_CFG_CAP_NRCOEX_RULE1_40M_20M_GAP0,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_1].relative_freq_gap0_40_20,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_1].relative_freq_gap0_40_20),
      WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule1_160m_80m_gap0", WLAN_CFG_CAP_NRCOEX_RULE1_160M_80M_GAP0,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_1].relative_freq_gap0_160_80,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_1].relative_freq_gap0_160_80),
      WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule1_40m_20m_gap1", WLAN_CFG_CAP_NRCOEX_RULE1_40M_20M_GAP1,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_1].relative_freq_gap1_40_20,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_1].relative_freq_gap1_40_20),
      WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule1_160m_80m_gap1", WLAN_CFG_CAP_NRCOEX_RULE1_160M_80M_GAP1,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_1].relative_freq_gap1_160_80,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_1].relative_freq_gap1_160_80),
      WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule1_40m_20m_gap2", WLAN_CFG_CAP_NRCOEX_RULE1_40M_20M_GAP2,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_1].relative_freq_gap2_40_20,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_1].relative_freq_gap2_40_20),
      WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule1_160m_80m_gap2", WLAN_CFG_CAP_NRCOEX_RULE1_160M_80M_GAP2,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_1].relative_freq_gap2_160_80,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_1].relative_freq_gap2_160_80),
      WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule1_smallgap0_act", WLAN_CFG_CAP_NRCOEX_RULE1_SMALLGAP0_ACT,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_1].limit_power_level0,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_1].limit_power_level0), WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule1_gap01_act", WLAN_CFG_CAP_NRCOEX_RULE1_GAP01_ACT,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_1].limit_power_level1,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_1].limit_power_level1), WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule1_gap12_act", WLAN_CFG_CAP_NRCOEX_RULE1_GAP12_ACT,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_1].limit_power_level2,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_1].limit_power_level2), WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule1_rxslot_rssi", WLAN_CFG_CAP_NRCOEX_RULE1_RXSLOT_RSSI,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_1].rssi_threshold,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_1].rssi_threshold), WLAN_CUST_NUM_1, OAL_FALSE },

    { "nrcoex_rule2_freq", WLAN_CFG_CAP_NRCOEX_RULE2_FREQ,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_2].freq,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_2].freq), WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule2_40m_20m_gap0", WLAN_CFG_CAP_NRCOEX_RULE2_40M_20M_GAP0,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_2].relative_freq_gap0_40_20,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_2].relative_freq_gap0_40_20),
      WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule2_160m_80m_gap0", WLAN_CFG_CAP_NRCOEX_RULE2_160M_80M_GAP0,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_2].relative_freq_gap0_160_80,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_2].relative_freq_gap0_160_80),
      WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule2_40m_20m_gap1", WLAN_CFG_CAP_NRCOEX_RULE2_40M_20M_GAP1,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_2].relative_freq_gap1_40_20,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_2].relative_freq_gap1_40_20),
      WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule2_160m_80m_gap1", WLAN_CFG_CAP_NRCOEX_RULE2_160M_80M_GAP1,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_2].relative_freq_gap1_160_80,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_2].relative_freq_gap1_160_80),
      WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule2_40m_20m_gap2", WLAN_CFG_CAP_NRCOEX_RULE2_40M_20M_GAP2,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_2].relative_freq_gap2_40_20,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_2].relative_freq_gap2_40_20),
      WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule2_160m_80m_gap2", WLAN_CFG_CAP_NRCOEX_RULE2_160M_80M_GAP2,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_2].relative_freq_gap2_160_80,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_2].relative_freq_gap2_160_80),
      WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule2_smallgap0_act", WLAN_CFG_CAP_NRCOEX_RULE2_SMALLGAP0_ACT,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_2].limit_power_level0,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_2].limit_power_level0), WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule2_gap01_act", WLAN_CFG_CAP_NRCOEX_RULE2_GAP01_ACT,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_2].limit_power_level1,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_2].limit_power_level1), WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule2_gap12_act", WLAN_CFG_CAP_NRCOEX_RULE2_GAP12_ACT,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_2].limit_power_level2,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_2].limit_power_level2), WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule2_rxslot_rssi", WLAN_CFG_CAP_NRCOEX_RULE2_RXSLOT_RSSI,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_2].rssi_threshold,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_2].rssi_threshold), WLAN_CUST_NUM_1, OAL_FALSE },

    { "nrcoex_rule3_freq", WLAN_CFG_CAP_NRCOEX_RULE3_FREQ,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_3].freq,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_3].freq), WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule3_40m_20m_gap0", WLAN_CFG_CAP_NRCOEX_RULE3_40M_20M_GAP0,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_3].relative_freq_gap0_40_20,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_3].relative_freq_gap0_40_20),
      WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule3_160m_80m_gap0", WLAN_CFG_CAP_NRCOEX_RULE3_160M_80M_GAP0,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_3].relative_freq_gap0_160_80,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_3].relative_freq_gap0_160_80),
      WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule3_40m_20m_gap1", WLAN_CFG_CAP_NRCOEX_RULE3_40M_20M_GAP1,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_3].relative_freq_gap1_40_20,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_3].relative_freq_gap1_40_20),
      WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule3_160m_80m_gap1", WLAN_CFG_CAP_NRCOEX_RULE3_160M_80M_GAP1,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_3].relative_freq_gap1_160_80,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_3].relative_freq_gap1_160_80),
      WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule3_40m_20m_gap2", WLAN_CFG_CAP_NRCOEX_RULE3_40M_20M_GAP2,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_3].relative_freq_gap2_40_20,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_3].relative_freq_gap2_40_20),
      WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule3_160m_80m_gap2", WLAN_CFG_CAP_NRCOEX_RULE3_160M_80M_GAP2,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_3].relative_freq_gap2_160_80,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_3].relative_freq_gap2_160_80),
      WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule3_smallgap0_act", WLAN_CFG_CAP_NRCOEX_RULE3_SMALLGAP0_ACT,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_3].limit_power_level0,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_3].limit_power_level0), WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule3_gap01_act", WLAN_CFG_CAP_NRCOEX_RULE3_GAP01_ACT,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_3].limit_power_level1,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_3].limit_power_level1), WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule3_gap12_act", WLAN_CFG_CAP_NRCOEX_RULE3_GAP12_ACT,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_3].limit_power_level2,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_3].limit_power_level2), WLAN_CUST_NUM_1, OAL_FALSE },
    { "nrcoex_rule3_rxslot_rssi", WLAN_CFG_CAP_NRCOEX_RULE3_RXSLOT_RSSI,
      &g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_3].rssi_threshold,
      sizeof(g_cust_cap.nrcoex_params.nrcoex_rule[CUST_NRCOEX_RULE_3].rssi_threshold), WLAN_CUST_NUM_1, OAL_FALSE },
#endif
    { "phy_sample", WLAN_CFG_CAP_PHY_SAMPLE_SWITCH, &g_cust_cap.phy_sample_switch, sizeof(g_cust_cap.phy_sample_switch),
        WLAN_CUST_NUM_1, OAL_FALSE },
#ifdef _PRE_WLAN_FEATURE_UWBCOEX
    { "uwbcoex_enable", WLAN_CFG_CAP_UWBCOEX_ENABLE, &g_cust_cap.uwbcoex_switch, sizeof(g_cust_cap.uwbcoex_switch),
        WLAN_CUST_NUM_1, OAL_FALSE },
#endif
    {"cali_freq_mask", WLAN_CFG_CAP_CALI_FREQ_MASK, &g_cust_cap.cali_switch.cali_freq_mask,
     sizeof(g_cust_cap.cali_switch.cali_freq_mask), WLAN_CUST_NUM_1, OAL_FALSE},
    {"fb_gain_delta_pow", WLAN_CFG_CAP_FB_GAIN_DELTA_POW, &g_cust_cap.fb_gain_delta_pow[0],
     sizeof(g_cust_cap.fb_gain_delta_pow[0]), oal_array_size(g_cust_cap.fb_gain_delta_pow), OAL_FALSE},
    {"dpd_en_start_mcs", WLAN_CFG_CAP_CALI_DPD_EN_START_MCS, &g_cust_cap.dpd_en_start_mcs[0],
     sizeof(g_cust_cap.dpd_en_start_mcs[0]), oal_array_size(g_cust_cap.dpd_en_start_mcs), OAL_FALSE},
    {"dpd_lvl_num", WLAN_CFG_CAP_DPD_LVL_NUM, &g_cust_cap.dpd_lvl_num[0],
     sizeof(g_cust_cap.dpd_lvl_num[0]), oal_array_size(g_cust_cap.dpd_lvl_num), OAL_FALSE},
    {"rf_lp_rx_insertion_loss_2g", WLAN_CFG_CAP_LP_LOSS_2G, &g_cust_cap.rf_lp_loss.gain_db_2g[0],
     sizeof(g_cust_cap.rf_lp_loss.gain_db_2g[0]), oal_array_size(g_cust_cap.rf_lp_loss.gain_db_2g), OAL_FALSE},
    {"rf_lp_rx_insertion_loss_5g", WLAN_CFG_CAP_LP_LOSS_5G, &g_cust_cap.rf_lp_loss.gain_db_5g[0],
     sizeof(g_cust_cap.rf_lp_loss.gain_db_5g[0]), oal_array_size(g_cust_cap.rf_lp_loss.gain_db_5g), OAL_FALSE},
    {"sar_cnt_time_lvl1", NVRAM_PARA_SAR_CNT_TIME_LV1, g_cust_cap.sar_total_time[0],
     sizeof(g_cust_cap.sar_total_time[0][0]),  WLAN_CALI_BAND_BUTT, OAL_FALSE},
    {"sar_cnt_time_lvl2", NVRAM_PARA_SAR_CNT_TIME_LV2, g_cust_cap.sar_total_time[1],
     sizeof(g_cust_cap.sar_total_time[1][0]),  WLAN_CALI_BAND_BUTT, OAL_FALSE},
    {"sar_cnt_time_lvl3", NVRAM_PARA_SAR_CNT_TIME_LV3, g_cust_cap.sar_total_time[2],
     sizeof(g_cust_cap.sar_total_time[2][0]),   WLAN_CALI_BAND_BUTT, OAL_FALSE},
    {"sar_cnt_time_lvl4", NVRAM_PARA_SAR_CNT_TIME_LV4, g_cust_cap.sar_total_time[3],
     sizeof(g_cust_cap.sar_total_time[3][0]),  WLAN_CALI_BAND_BUTT, OAL_FALSE},
    {"sar_cnt_time_lvl5", NVRAM_PARA_SAR_CNT_TIME_LV5, g_cust_cap.sar_total_time[4],
     sizeof(g_cust_cap.sar_total_time[4][0]),   WLAN_CALI_BAND_BUTT, OAL_FALSE},
    {"sar_cnt_time_lvl6", NVRAM_PARA_SAR_CNT_TIME_LV6, g_cust_cap.sar_total_time[5],
     sizeof(g_cust_cap.sar_total_time[5][0]),  WLAN_CALI_BAND_BUTT, OAL_FALSE},
    {"sar_cnt_time_lvl7", NVRAM_PARA_SAR_CNT_TIME_LV7, g_cust_cap.sar_total_time[6],
     sizeof(g_cust_cap.sar_total_time[6][0]),  WLAN_CALI_BAND_BUTT, OAL_FALSE},
    {"sar_cnt_time_lvl8", NVRAM_PARA_SAR_CNT_TIME_LV8, g_cust_cap.sar_total_time[7],
     sizeof(g_cust_cap.sar_total_time[7][0]),  WLAN_CALI_BAND_BUTT, OAL_FALSE},
    {"sar_cnt_time_lvl9", NVRAM_PARA_SAR_CNT_TIME_LV9, g_cust_cap.sar_total_time[8],
     sizeof(g_cust_cap.sar_total_time[8][0]), WLAN_CALI_BAND_BUTT, OAL_FALSE},
    {"sar_cnt_time_lvl10", NVRAM_PARA_SAR_CNT_TIME_LV10, g_cust_cap.sar_total_time[9],
     sizeof(g_cust_cap.sar_total_time[9][0]), WLAN_CALI_BAND_BUTT, OAL_FALSE},
    {"sar_cnt_time_lvl11", NVRAM_PARA_SAR_CNT_TIME_LV11, g_cust_cap.sar_total_time[10],
     sizeof(g_cust_cap.sar_total_time[10][0]), WLAN_CALI_BAND_BUTT, OAL_FALSE},
    {"sar_cnt_time_lvl12", NVRAM_PARA_SAR_CNT_TIME_LV12, g_cust_cap.sar_total_time[11],
     sizeof(g_cust_cap.sar_total_time[11][0]), WLAN_CALI_BAND_BUTT, OAL_FALSE},
    {"sar_cnt_time_lvl13", NVRAM_PARA_SAR_CNT_TIME_LV13, g_cust_cap.sar_total_time[12],
     sizeof(g_cust_cap.sar_total_time[12][0]), WLAN_CALI_BAND_BUTT, OAL_FALSE},
    {"sar_cnt_time_lvl14", NVRAM_PARA_SAR_CNT_TIME_LV14, g_cust_cap.sar_total_time[13],
     sizeof(g_cust_cap.sar_total_time[13][0]), WLAN_CALI_BAND_BUTT, OAL_FALSE},
    {"sar_cnt_time_lvl15", NVRAM_PARA_SAR_CNT_TIME_LV15, g_cust_cap.sar_total_time[14],
     sizeof(g_cust_cap.sar_total_time[14][0]), WLAN_CALI_BAND_BUTT, OAL_FALSE},
    {"sar_cnt_time_lvl16", NVRAM_PARA_SAR_CNT_TIME_LV16, g_cust_cap.sar_total_time[15],
     sizeof(g_cust_cap.sar_total_time[15][0]), WLAN_CALI_BAND_BUTT, OAL_FALSE},
    {"sar_cnt_time_lvl17", NVRAM_PARA_SAR_CNT_TIME_LV17, g_cust_cap.sar_total_time[16],
     sizeof(g_cust_cap.sar_total_time[16][0]), WLAN_CALI_BAND_BUTT, OAL_FALSE},
    {"sar_cnt_time_lvl18", NVRAM_PARA_SAR_CNT_TIME_LV18, g_cust_cap.sar_total_time[17],
     sizeof(g_cust_cap.sar_total_time[17][0]), WLAN_CALI_BAND_BUTT, OAL_FALSE},
    {"sar_cnt_time_lvl19", NVRAM_PARA_SAR_CNT_TIME_LV19, g_cust_cap.sar_total_time[18],
     sizeof(g_cust_cap.sar_total_time[18][0]), WLAN_CALI_BAND_BUTT, OAL_FALSE},
    {"sar_cnt_time_lvl20", NVRAM_PARA_SAR_CNT_TIME_LV20, g_cust_cap.sar_total_time[19],
     sizeof(g_cust_cap.sar_total_time[19][0]),  WLAN_CALI_BAND_BUTT, OAL_FALSE},
    {"sar_slide_pow_amend_c0", NVRAM_PARA_SAR_SLIDE_POW_AMEND_C0,
     g_cust_cap.sar_slide_pow_amend[WLAN_SINGLE_STREAM_0],
     sizeof(g_cust_cap.sar_slide_pow_amend[WLAN_SINGLE_STREAM_0][0]), WLAN_CALI_BAND_BUTT, OAL_FALSE},
    {"sar_slide_pow_amend_c1", NVRAM_PARA_SAR_SLIDE_POW_AMEND_C1,
     g_cust_cap.sar_slide_pow_amend[WLAN_SINGLE_STREAM_1],
     sizeof(g_cust_cap.sar_slide_pow_amend[WLAN_SINGLE_STREAM_1][0]), WLAN_CALI_BAND_BUTT, OAL_FALSE},
    {"sar_slide_pow_amend_c2", NVRAM_PARA_SAR_SLIDE_POW_AMEND_C2,
     g_cust_cap.sar_slide_pow_amend[WLAN_SINGLE_STREAM_2],
     sizeof(g_cust_cap.sar_slide_pow_amend[WLAN_SINGLE_STREAM_2][0]), WLAN_CALI_BAND_BUTT, OAL_FALSE},
    {"sar_slide_pow_amend_c3", NVRAM_PARA_SAR_SLIDE_POW_AMEND_C3,
     g_cust_cap.sar_slide_pow_amend[WLAN_SINGLE_STREAM_3],
     sizeof(g_cust_cap.sar_slide_pow_amend[WLAN_SINGLE_STREAM_3][0]), WLAN_CALI_BAND_BUTT, OAL_FALSE},
    {"sar_slide_window_en", WLAN_CFG_CAP_SAR_SLIDE_WINDOW_EN, &g_cust_cap.sar_slide_window_en,
     sizeof(g_cust_cap.sar_slide_window_en), WLAN_CUST_NUM_1, OAL_FALSE},
    {"fem_polar_policy", WLAN_CFG_CAP_FEM_POLAR, g_cust_cap.fem_polar_policy,
     sizeof(g_cust_cap.fem_polar_policy[0]), WLAN_CUST_NUM_3, OAL_FALSE},
    {"gle_ant_use", WLAN_CFG_CAP_GLE_ANT_USE, &g_cust_cap.gle_ant_use,
     sizeof(g_cust_cap.gle_ant_use), WLAN_CUST_NUM_1, OAL_FALSE },
    {"lp_rx_cap", WLAN_CFG_CAP_LP_CAP, &g_cust_cap.lp_rx_cap,
     sizeof(g_cust_cap.lp_rx_cap), WLAN_CUST_NUM_1, OAL_FALSE },
    {"fem_backoff_pow_3a", WLAN_CFG_CAP_FEM_DELT_POW_3A, g_cust_cap.fem_pow_3a.fem_delt_pow_3a,
     sizeof(g_cust_cap.fem_pow_3a.fem_delt_pow_3a[0]),
     oal_array_size(g_cust_cap.fem_pow_3a.fem_delt_pow_3a), OAL_FALSE},
    {"tpc_adj_pow_start_idx_by_fem_3a", WLAN_CFG_CAP_FEM_ADJ_TPC_TBL_START_IDX_3A,
     g_cust_cap.fem_pow_3a.tpc_adj_pow_start_idx_3a, sizeof(g_cust_cap.fem_pow_3a.tpc_adj_pow_start_idx_3a[0]),
     oal_array_size(g_cust_cap.fem_pow_3a.tpc_adj_pow_start_idx_3a), OAL_FALSE},
    {"fem_mode_3a", WLAN_CFG_FEM_MODE_3A, g_cust_cap.fem_mode_3a,
     sizeof(g_cust_cap.fem_mode_3a[0]), WLAN_CUST_NUM_3, OAL_FALSE},

    {"cfg_tpc_ru_max_pow_2g_2x2_c0", NVRAM_RU_2X2_MAX_POWER_2G_C0,
     &g_cust_cap.tb_ru_2g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_1].ru_pwr_2g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_2g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_1].ru_pwr_2g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_2g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_1].ru_pwr_2g), OAL_FALSE},
    {"cfg_tpc_ru_max_pow_2g_2x2_c1", NVRAM_RU_2X2_MAX_POWER_2G_C1,
     &g_cust_cap.tb_ru_2g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_2].ru_pwr_2g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_2g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_2].ru_pwr_2g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_2g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_2].ru_pwr_2g), OAL_FALSE},
    {"cfg_tpc_ru_max_pow_2g_2x2_c2", NVRAM_RU_2X2_MAX_POWER_2G_C2,
     &g_cust_cap.tb_ru_2g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_3].ru_pwr_2g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_2g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_3].ru_pwr_2g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_2g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_3].ru_pwr_2g), OAL_FALSE},
    {"cfg_tpc_ru_max_pow_2g_2x2_c3", NVRAM_RU_2X2_MAX_POWER_2G_C3,
     &g_cust_cap.tb_ru_2g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_4].ru_pwr_2g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_2g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_4].ru_pwr_2g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_2g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_4].ru_pwr_2g), OAL_FALSE},
    {"cfg_tpc_ru_max_pow_5g_2x2_c0", NVRAM_RU_2X2_MAX_POWER_5G_C0,
     &g_cust_cap.tb_ru_5g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_1].ru_pwr_5g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_5g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_1].ru_pwr_5g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_5g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_1].ru_pwr_5g), OAL_FALSE},
    {"cfg_tpc_ru_max_pow_5g_2x2_c1", NVRAM_RU_2X2_MAX_POWER_5G_C1,
     &g_cust_cap.tb_ru_5g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_2].ru_pwr_5g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_5g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_2].ru_pwr_5g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_5g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_2].ru_pwr_5g), OAL_FALSE},
    {"cfg_tpc_ru_max_pow_5g_2x2_c2", NVRAM_RU_2X2_MAX_POWER_5G_C2,
     &g_cust_cap.tb_ru_5g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_3].ru_pwr_5g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_5g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_3].ru_pwr_5g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_5g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_3].ru_pwr_5g), OAL_FALSE},
    {"cfg_tpc_ru_max_pow_5g_2x2_c3", NVRAM_RU_2X2_MAX_POWER_5G_C3,
     &g_cust_cap.tb_ru_5g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_4].ru_pwr_5g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_5g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_4].ru_pwr_5g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_5g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_4].ru_pwr_5g), OAL_FALSE},
#ifdef _PRE_WLAN_FEATURE_6G_EXTEND
    {"cfg_tpc_ru_max_pow_6g_2x2_c0", NVRAM_RU_2X2_MAX_POWER_6G_C0,
     &g_cust_cap.tb_ru_6g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_1].ru_pwr_6g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_6g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_1].ru_pwr_6g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_6g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_1].ru_pwr_6g), OAL_FALSE},
    {"cfg_tpc_ru_max_pow_6g_2x2_c1", NVRAM_RU_2X2_MAX_POWER_6G_C1,
     &g_cust_cap.tb_ru_6g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_2].ru_pwr_6g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_6g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_2].ru_pwr_6g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_6g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_2].ru_pwr_6g), OAL_FALSE},
    {"cfg_tpc_ru_max_pow_6g_2x2_c2", NVRAM_RU_2X2_MAX_POWER_6G_C2,
     &g_cust_cap.tb_ru_6g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_3].ru_pwr_6g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_6g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_3].ru_pwr_6g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_6g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_3].ru_pwr_6g), OAL_FALSE},
    {"cfg_tpc_ru_max_pow_6g_2x2_c3", NVRAM_RU_2X2_MAX_POWER_6G_C3,
     &g_cust_cap.tb_ru_6g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_4].ru_pwr_6g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_6g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_4].ru_pwr_6g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_6g_2x2_max_pow[HAL_POW_RF_SEL_CHAIN_4].ru_pwr_6g), OAL_FALSE},
#endif
    {"cfg_tpc_ru_max_pow_2g_3x3_c0", NVRAM_RU_3X3_MAX_POWER_2G_C0,
     &g_cust_cap.tb_ru_2g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_1].ru_pwr_2g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_2g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_1].ru_pwr_2g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_2g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_1].ru_pwr_2g), OAL_FALSE},
    {"cfg_tpc_ru_max_pow_2g_3x3_c1", NVRAM_RU_3X3_MAX_POWER_2G_C1,
     &g_cust_cap.tb_ru_2g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_2].ru_pwr_2g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_2g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_2].ru_pwr_2g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_2g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_2].ru_pwr_2g), OAL_FALSE},
    {"cfg_tpc_ru_max_pow_2g_3x3_c2", NVRAM_RU_3X3_MAX_POWER_2G_C2,
     &g_cust_cap.tb_ru_2g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_3].ru_pwr_2g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_2g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_3].ru_pwr_2g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_2g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_3].ru_pwr_2g), OAL_FALSE},
    {"cfg_tpc_ru_max_pow_2g_3x3_c3", NVRAM_RU_3X3_MAX_POWER_2G_C3,
     &g_cust_cap.tb_ru_2g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_4].ru_pwr_2g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_2g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_4].ru_pwr_2g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_2g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_4].ru_pwr_2g), OAL_FALSE},
    {"cfg_tpc_ru_max_pow_5g_3x3_c0", NVRAM_RU_3X3_MAX_POWER_5G_C0,
     &g_cust_cap.tb_ru_5g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_1].ru_pwr_5g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_5g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_1].ru_pwr_5g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_5g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_1].ru_pwr_5g), OAL_FALSE},
    {"cfg_tpc_ru_max_pow_5g_3x3_c1", NVRAM_RU_3X3_MAX_POWER_5G_C1,
     &g_cust_cap.tb_ru_5g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_2].ru_pwr_5g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_5g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_2].ru_pwr_5g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_5g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_2].ru_pwr_5g), OAL_FALSE},
    {"cfg_tpc_ru_max_pow_5g_3x3_c2", NVRAM_RU_3X3_MAX_POWER_5G_C2,
     &g_cust_cap.tb_ru_5g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_3].ru_pwr_5g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_5g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_3].ru_pwr_5g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_5g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_3].ru_pwr_5g), OAL_FALSE},
    {"cfg_tpc_ru_max_pow_5g_3x3_c3", NVRAM_RU_3X3_MAX_POWER_5G_C3,
     &g_cust_cap.tb_ru_5g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_4].ru_pwr_5g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_5g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_4].ru_pwr_5g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_5g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_4].ru_pwr_5g), OAL_FALSE},
#ifdef _PRE_WLAN_FEATURE_6G_EXTEND
    {"cfg_tpc_ru_max_pow_6g_3x3_c0", NVRAM_RU_3X3_MAX_POWER_6G_C0,
     &g_cust_cap.tb_ru_6g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_1].ru_pwr_6g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_6g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_1].ru_pwr_6g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_6g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_1].ru_pwr_6g), OAL_FALSE},
    {"cfg_tpc_ru_max_pow_6g_3x3_c1", NVRAM_RU_3X3_MAX_POWER_6G_C1,
     &g_cust_cap.tb_ru_6g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_2].ru_pwr_6g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_6g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_2].ru_pwr_6g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_6g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_2].ru_pwr_6g), OAL_FALSE},
    {"cfg_tpc_ru_max_pow_6g_3x3_c2", NVRAM_RU_3X3_MAX_POWER_6G_C2,
     &g_cust_cap.tb_ru_6g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_3].ru_pwr_6g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_6g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_3].ru_pwr_6g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_6g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_3].ru_pwr_6g), OAL_FALSE},
    {"cfg_tpc_ru_max_pow_6g_3x3_c3", NVRAM_RU_3X3_MAX_POWER_6G_C3,
     &g_cust_cap.tb_ru_6g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_4].ru_pwr_6g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_6g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_4].ru_pwr_6g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_6g_3x3_max_pow[HAL_POW_RF_SEL_CHAIN_4].ru_pwr_6g), OAL_FALSE},
#endif
    {"cfg_tpc_ru_max_pow_2g_4x4_c0", NVRAM_RU_4X4_MAX_POWER_2G_C0,
     &g_cust_cap.tb_ru_2g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_1].ru_pwr_2g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_2g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_1].ru_pwr_2g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_2g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_1].ru_pwr_2g), OAL_FALSE},
    {"cfg_tpc_ru_max_pow_2g_4x4_c1", NVRAM_RU_4X4_MAX_POWER_2G_C1,
     &g_cust_cap.tb_ru_2g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_2].ru_pwr_2g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_2g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_2].ru_pwr_2g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_2g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_2].ru_pwr_2g), OAL_FALSE},
    {"cfg_tpc_ru_max_pow_2g_4x4_c2", NVRAM_RU_4X4_MAX_POWER_2G_C2,
     &g_cust_cap.tb_ru_2g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_3].ru_pwr_2g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_2g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_3].ru_pwr_2g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_2g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_3].ru_pwr_2g), OAL_FALSE},
    {"cfg_tpc_ru_max_pow_2g_4x4_c3", NVRAM_RU_4X4_MAX_POWER_2G_C3,
     &g_cust_cap.tb_ru_2g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_4].ru_pwr_2g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_2g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_4].ru_pwr_2g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_2g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_4].ru_pwr_2g), OAL_FALSE},
    {"cfg_tpc_ru_max_pow_5g_4x4_c0", NVRAM_RU_4X4_MAX_POWER_5G_C0,
     &g_cust_cap.tb_ru_5g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_1].ru_pwr_5g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_5g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_1].ru_pwr_5g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_5g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_1].ru_pwr_5g), OAL_FALSE},
    {"cfg_tpc_ru_max_pow_5g_4x4_c1", NVRAM_RU_4X4_MAX_POWER_5G_C1,
     &g_cust_cap.tb_ru_5g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_2].ru_pwr_5g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_5g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_2].ru_pwr_5g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_5g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_2].ru_pwr_5g), OAL_FALSE},
    {"cfg_tpc_ru_max_pow_5g_4x4_c2", NVRAM_RU_4X4_MAX_POWER_5G_C2,
     &g_cust_cap.tb_ru_5g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_3].ru_pwr_5g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_5g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_3].ru_pwr_5g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_5g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_3].ru_pwr_5g), OAL_FALSE},
    {"cfg_tpc_ru_max_pow_5g_4x4_c3", NVRAM_RU_4X4_MAX_POWER_5G_C3,
     &g_cust_cap.tb_ru_5g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_4].ru_pwr_5g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_5g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_4].ru_pwr_5g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_5g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_4].ru_pwr_5g), OAL_FALSE},
#ifdef _PRE_WLAN_FEATURE_6G_EXTEND
    {"cfg_tpc_ru_max_pow_6g_4x4_c0", NVRAM_RU_4X4_MAX_POWER_6G_C0,
     &g_cust_cap.tb_ru_6g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_1].ru_pwr_6g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_6g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_1].ru_pwr_6g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_6g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_1].ru_pwr_6g), OAL_FALSE},
    {"cfg_tpc_ru_max_pow_6g_4x4_c1", NVRAM_RU_4X4_MAX_POWER_6G_C1,
     &g_cust_cap.tb_ru_6g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_2].ru_pwr_6g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_6g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_2].ru_pwr_6g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_6g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_2].ru_pwr_6g), OAL_FALSE},
    {"cfg_tpc_ru_max_pow_6g_4x4_c2", NVRAM_RU_4X4_MAX_POWER_6G_C2,
     &g_cust_cap.tb_ru_6g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_3].ru_pwr_6g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_6g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_3].ru_pwr_6g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_6g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_3].ru_pwr_6g), OAL_FALSE},
    {"cfg_tpc_ru_max_pow_6g_4x4_c3", NVRAM_RU_4X4_MAX_POWER_6G_C3,
     &g_cust_cap.tb_ru_6g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_4].ru_pwr_6g[WLAN_HE_RU_SIZE_26],
     sizeof(g_cust_cap.tb_ru_6g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_4].ru_pwr_6g[WLAN_HE_RU_SIZE_26]),
     oal_array_size(g_cust_cap.tb_ru_6g_4x4_max_pow[HAL_POW_RF_SEL_CHAIN_4].ru_pwr_6g), OAL_FALSE},
#endif
    {"dyn_bypass_2g_extlna_rssi_th_h", WLAN_CFG_CAP_DYN_BYPASS_2G_EXTLNA_TH_H,
     &g_cust_cap.dyn_bypass_extlna_rssi_th_h[WLAN_BAND_2G][0],
     sizeof(g_cust_cap.dyn_bypass_extlna_rssi_th_h[WLAN_BAND_2G][0]),
     oal_array_size(g_cust_cap.dyn_bypass_extlna_rssi_th_h[WLAN_BAND_2G]), OAL_FALSE},
    {"dyn_bypass_2g_extlna_rssi_th_l", WLAN_CFG_CAP_DYN_BYPASS_2G_EXTLNA_TH_L,
     &g_cust_cap.dyn_bypass_extlna_rssi_th_l[WLAN_BAND_2G][0],
     sizeof(g_cust_cap.dyn_bypass_extlna_rssi_th_l[WLAN_BAND_2G][0]),
     oal_array_size(g_cust_cap.dyn_bypass_extlna_rssi_th_l[WLAN_BAND_2G]), OAL_FALSE},
    {"dyn_bypass_5g_extlna_rssi_th_h", WLAN_CFG_CAP_DYN_BYPASS_5G_EXTLNA_TH_H,
     &g_cust_cap.dyn_bypass_extlna_rssi_th_h[WLAN_BAND_5G][0],
     sizeof(g_cust_cap.dyn_bypass_extlna_rssi_th_h[WLAN_BAND_5G][0]),
     oal_array_size(g_cust_cap.dyn_bypass_extlna_rssi_th_h[WLAN_BAND_5G]), OAL_FALSE},
    {"dyn_bypass_5g_extlna_rssi_th_l", WLAN_CFG_CAP_DYN_BYPASS_5G_EXTLNA_TH_L,
     &g_cust_cap.dyn_bypass_extlna_rssi_th_l[WLAN_BAND_5G][0],
     sizeof(g_cust_cap.dyn_bypass_extlna_rssi_th_l[WLAN_BAND_5G][0]),
     oal_array_size(g_cust_cap.dyn_bypass_extlna_rssi_th_l[WLAN_BAND_5G]), OAL_FALSE},
    {"power_cali_amend_c0", WLAN_CFG_POW_CALI_AMEND_C0,
     &g_cust_cap.offline_pow_cali_amend[WLAN_RF_CHANNEL_ZERO][0],
     sizeof(g_cust_cap.offline_pow_cali_amend[WLAN_RF_CHANNEL_ZERO][0]),
     oal_array_size(g_cust_cap.offline_pow_cali_amend[WLAN_RF_CHANNEL_ZERO]), OAL_FALSE},
    {"power_cali_amend_c1", WLAN_CFG_POW_CALI_AMEND_C1,
     &g_cust_cap.offline_pow_cali_amend[WLAN_RF_CHANNEL_ONE][0],
     sizeof(g_cust_cap.offline_pow_cali_amend[WLAN_RF_CHANNEL_ONE][0]),
     oal_array_size(g_cust_cap.offline_pow_cali_amend[WLAN_RF_CHANNEL_ONE]), OAL_FALSE},
    {"power_cali_amend_c2", WLAN_CFG_POW_CALI_AMEND_C2,
     &g_cust_cap.offline_pow_cali_amend[WLAN_RF_CHANNEL_TWO][0],
     sizeof(g_cust_cap.offline_pow_cali_amend[WLAN_RF_CHANNEL_TWO][0]),
     oal_array_size(g_cust_cap.offline_pow_cali_amend[WLAN_RF_CHANNEL_TWO]), OAL_FALSE},
    {"power_cali_amend_c3", WLAN_CFG_POW_CALI_AMEND_C3,
     &g_cust_cap.offline_pow_cali_amend[WLAN_RF_CHANNEL_THREE][0],
     sizeof(g_cust_cap.offline_pow_cali_amend[WLAN_RF_CHANNEL_THREE][0]),
     oal_array_size(g_cust_cap.offline_pow_cali_amend[WLAN_RF_CHANNEL_THREE]), OAL_FALSE},
};

