/*
 * Copyright (c) @CompanyNameMagicTag 2021-2023. All rights reserved.
 * 功能说明 : WIFI omeimage宏定义文件
 * 作    者 : wifi
 * 创建日期 : 2019年7月26日
 */

#ifndef WLAN_ONEIMAGE_DEFINE_H
#define WLAN_ONEIMAGE_DEFINE_H

/* 1 其他头文件包含 */
#include "wlan_oneimage_define_mac.h"
#include "wlan_oneimage_define_hmac1.h"
#include "wlan_oneimage_define_hmac2.h"
#include "wlan_oneimage_define_hmac3.h"
#include "wlan_oneimage_define_wal.h"
/* 2 宏定义 */
#if !defined(WIN32) && !defined(_PRE_WINDOWS_SUPPORT)
#define wlan_oneimage_rename(NAME)  NAME##_15

#define check_headroom_add_length   wlan_oneimage_rename(check_headroom_add_length)
#define event_fsm_table_register   wlan_oneimage_rename(event_fsm_table_register)
#define event_fsm_unregister   wlan_oneimage_rename(event_fsm_unregister)
#define g_160m_tone_lut   wlan_oneimage_rename(g_160m_tone_lut)
#define g_320m_tone_lut   wlan_oneimage_rename(g_320m_tone_lut)
#define g_625k_160m_tone_lut   wlan_oneimage_rename(g_625k_160m_tone_lut)
#define g_625k_320m_tone_lut   wlan_oneimage_rename(g_625k_320m_tone_lut)
#define g_625k_640m_tone_lut   wlan_oneimage_rename(g_625k_640m_tone_lut)
#define g_640m_tone_lut   wlan_oneimage_rename(g_640m_tone_lut)
#define g_as_mp15_160m_tone_lut   wlan_oneimage_rename(g_as_mp15_160m_tone_lut)
#define g_as_mp15_320m_tone_lut   wlan_oneimage_rename(g_as_mp15_320m_tone_lut)
#define g_as_mp15_625k_160m_tone_lut   wlan_oneimage_rename(g_as_mp15_625k_160m_tone_lut)
#define g_as_mp15_625k_320m_tone_lut   wlan_oneimage_rename(g_as_mp15_625k_320m_tone_lut)
#define g_as_mp15_625k_640m_tone_lut   wlan_oneimage_rename(g_as_mp15_625k_640m_tone_lut)
#define g_as_mp15_625k_80m_tone_lut   wlan_oneimage_rename(g_as_mp15_625k_80m_tone_lut)
#define g_as_mp15_640m_tone_lut   wlan_oneimage_rename(g_as_mp15_640m_tone_lut)
#define g_as_mp15_80m_tone_lut   wlan_oneimage_rename(g_as_mp15_80m_tone_lut)
#define g_as_rxiq_bw80m_siso_h_comp_320m   wlan_oneimage_rename(g_as_rxiq_bw80m_siso_h_comp_320m)
#define g_as_rxiq_h_comp_320m   wlan_oneimage_rename(g_as_rxiq_h_comp_320m)
#define g_as_rxiq_h_comp_80m   wlan_oneimage_rename(g_as_rxiq_h_comp_80m)
#define g_ast_11ax_debug_table   wlan_oneimage_rename(g_ast_11ax_debug_table)
#define g_ast_alg_cfg_map   wlan_oneimage_rename(g_ast_alg_cfg_map)
#define g_ast_atcmdsrv_mode_table   wlan_oneimage_rename(g_ast_atcmdsrv_mode_table)
#define g_ast_blacklist   wlan_oneimage_rename(g_ast_blacklist)
#define g_ast_board_wid_op_debug   wlan_oneimage_rename(g_ast_board_wid_op_debug)
#define g_ast_channel_list_2g   wlan_oneimage_rename(g_ast_channel_list_2g)
#define g_ast_channel_list_5g   wlan_oneimage_rename(g_ast_channel_list_5g)
#define g_ast_common_debug_table   wlan_oneimage_rename(g_ast_common_debug_table)
#define g_ast_cpufreq   wlan_oneimage_rename(g_ast_cpufreq)
#define g_ast_dfs_domain_table   wlan_oneimage_rename(g_ast_dfs_domain_table)
#define g_ast_hmac_high_prio_event_sub_table   wlan_oneimage_rename(g_ast_hmac_high_prio_event_sub_table)
#define g_ast_host_dmac_crx_table   wlan_oneimage_rename(g_ast_host_dmac_crx_table)
#define g_ast_hmac_tx_comp_event_sub_table   wlan_oneimage_rename(g_ast_hmac_tx_comp_event_sub_table)
#define g_ast_host_tx_dmac_drx   wlan_oneimage_rename(g_ast_host_tx_dmac_drx)
#define g_ast_hmac_tx_wlan_dtx   wlan_oneimage_rename(g_ast_hmac_tx_wlan_dtx)
#define g_ast_dmac_wlan_crx_event_sub_table   wlan_oneimage_rename(g_ast_dmac_wlan_crx_event_sub_table)
#define g_ast_host_wlan_ctx_event_sub_table   wlan_oneimage_rename(g_ast_host_wlan_ctx_event_sub_table)
#define g_ast_dmac_wlan_drx_event_sub_table   wlan_oneimage_rename(g_ast_dmac_wlan_drx_event_sub_table)
#define g_ast_dyn_cali_cfg_map   wlan_oneimage_rename(g_ast_dyn_cali_cfg_map)
#define g_ast_freq_map_2g   wlan_oneimage_rename(g_ast_freq_map_2g)
#define g_ast_freq_map_5g   wlan_oneimage_rename(g_ast_freq_map_5g)
#define g_mp15_rxiq_h_comp_160m   wlan_oneimage_rename(g_mp15_rxiq_h_comp_160m)
#define g_mp15_rxiq_h_comp_320m   wlan_oneimage_rename(g_mp15_rxiq_h_comp_320m)
#define g_mp15_rxiq_h_comp_40m   wlan_oneimage_rename(g_mp15_rxiq_h_comp_40m)
#define g_mp15_rxiq_h_comp_80m_fpga   wlan_oneimage_rename(g_mp15_rxiq_h_comp_80m_fpga)
#define g_mp15_rxiq_h_comp_80m   wlan_oneimage_rename(g_mp15_rxiq_h_comp_80m)
#define g_mp15_rxiq_40m_h_comp_160m   wlan_oneimage_rename(g_mp15_rxiq_40m_h_comp_160m)
#define g_mp15_txiq_h_comp_160m_fpga   wlan_oneimage_rename(g_mp15_txiq_h_comp_160m_fpga)
#define g_mp15_txiq_h_comp_160m   wlan_oneimage_rename(g_mp15_txiq_h_comp_160m)
#define g_mp15_2g_txiq_h_comp_320m   wlan_oneimage_rename(g_mp15_2g_txiq_h_comp_320m)
#define g_mp15_txiq_h_comp_320m   wlan_oneimage_rename(g_mp15_txiq_h_comp_320m)
#define g_mp15_txiq_h_comp_640m   wlan_oneimage_rename(g_mp15_txiq_h_comp_640m)
#define g_mp15_txiq_h_comp_80m   wlan_oneimage_rename(g_mp15_txiq_h_comp_80m)
#define g_en_need_close_fem_cali   wlan_oneimage_rename(g_en_need_close_fem_cali)
#define g_ast_hipriv_cmd_debug   wlan_oneimage_rename(g_ast_hipriv_cmd_debug)
#define g_ast_hmac_tcp_ack_buf_cfg_table   wlan_oneimage_rename(g_ast_hmac_tcp_ack_buf_cfg_table)
#define g_ast_hmac_wlan_crx_event_sub_table   wlan_oneimage_rename(g_ast_hmac_wlan_crx_event_sub_table)
#define g_ast_hmac_wlan_ctx_event_sub_table   wlan_oneimage_rename(g_ast_hmac_wlan_ctx_event_sub_table)
#define g_ast_hmac_wlan_drx_event_sub_table   wlan_oneimage_rename(g_ast_hmac_wlan_drx_event_sub_table)
#define g_ast_hmac_wlan_dtx_event_sub_table   wlan_oneimage_rename(g_ast_hmac_wlan_dtx_event_sub_table)
#define g_ast_hmac_wlan_misc_event_sub_table   wlan_oneimage_rename(g_ast_hmac_wlan_misc_event_sub_table)
#define g_ast_mac_rx_report_debug_table   wlan_oneimage_rename(g_ast_mac_rx_report_debug_table)
#define g_ast_mac_tx_report_debug_table   wlan_oneimage_rename(g_ast_mac_tx_report_debug_table)
#define g_ast_mode_map   wlan_oneimage_rename(g_ast_mode_map)
#define g_ast_set_str_table   wlan_oneimage_rename(g_ast_set_str_table)
#define g_ast_set_tlv_table   wlan_oneimage_rename(g_ast_set_tlv_table)
#define g_ast_wmm_initial_params_ap   wlan_oneimage_rename(g_ast_wmm_initial_params_ap)
#define g_ast_wmm_initial_params_bss   wlan_oneimage_rename(g_ast_wmm_initial_params_bss)
#define g_ast_wmm_initial_params_sta   wlan_oneimage_rename(g_ast_wmm_initial_params_sta)
#define g_txiq_h_comp_160m   wlan_oneimage_rename(g_txiq_h_comp_160m)
#define g_txiq_h_comp_320m   wlan_oneimage_rename(g_txiq_h_comp_320m)
#define g_txiq_h_comp_640m   wlan_oneimage_rename(g_txiq_h_comp_640m)
#define g_auc_avail_protocol_mode   wlan_oneimage_rename(g_auc_avail_protocol_mode)
#define g_auc_dfr_error_type   wlan_oneimage_rename(g_auc_dfr_error_type)
#define g_tas_switch_en   wlan_oneimage_rename(g_tas_switch_en)
#define g_cust_country_code_ignore_flag    wlan_oneimage_rename(g_cust_country_code_ignore_flag)
#define g_pro_line_params    wlan_oneimage_rename(g_pro_line_params)

#define g_en_nv_dp_init_is_null    wlan_oneimage_rename(g_en_nv_dp_init_is_null)
#define g_wlan_cust    wlan_oneimage_rename(g_wlan_cust)

#define g_cust_rf_cali    wlan_oneimage_rename(g_cust_rf_cali)
#define g_en_fact_cali_completed    wlan_oneimage_rename(g_en_fact_cali_completed)
#define g_cust_rf_front    wlan_oneimage_rename(g_cust_rf_front)

#define g_cust_dyn_pow    wlan_oneimage_rename(g_cust_dyn_pow)
#define g_wlan_cal_intvl_enable    wlan_oneimage_rename(g_wlan_cal_intvl_enable)
#define g_wlan_cal_disable_switch    wlan_oneimage_rename(g_wlan_cal_disable_switch)
#define g_wifi_country_code    wlan_oneimage_rename(g_wifi_country_code)

#define g_auc_huawei_oui   wlan_oneimage_rename(g_auc_huawei_oui)
#define g_auc_mac_device_radio_cap   wlan_oneimage_rename(g_auc_mac_device_radio_cap)
#define g_rx_filter_frag wlan_oneimage_rename(g_rx_filter_frag)
#define g_auc_p2p_oui   wlan_oneimage_rename(g_auc_p2p_oui)
#define g_auc_rsn_oui   wlan_oneimage_rename(g_auc_rsn_oui)
#define g_auc_wapi_pn_init   wlan_oneimage_rename(g_auc_wapi_pn_init)
#define g_auc_wfa_oui   wlan_oneimage_rename(g_auc_wfa_oui)
#define g_auc_wifiapmac   wlan_oneimage_rename(g_auc_wifiapmac)
#define g_auc_wifiGCGOmac   wlan_oneimage_rename(g_auc_wifiGCGOmac)
#define g_auc_wifinvmac   wlan_oneimage_rename(g_auc_wifinvmac)
#define g_auc_wifip2p0mac   wlan_oneimage_rename(g_auc_wifip2p0mac)
#define g_auc_wifistamac   wlan_oneimage_rename(g_auc_wifistamac)
#define g_auc_wmm_oui   wlan_oneimage_rename(g_auc_wmm_oui)
#define g_auc_wpa_oui   wlan_oneimage_rename(g_auc_wpa_oui)
#define g_auc_wps_oui   wlan_oneimage_rename(g_auc_wps_oui)
#define g_aul_cpumaxfreq   wlan_oneimage_rename(g_aul_cpumaxfreq)
#define g_bw_mode_table_2g   wlan_oneimage_rename(g_bw_mode_table_2g)
#define g_bw_mode_table_5g   wlan_oneimage_rename(g_bw_mode_table_5g)
#define g_cookie_array   wlan_oneimage_rename(g_cookie_array)
#define g_device_speed_freq_level   wlan_oneimage_rename(g_device_speed_freq_level)
#define g_en_bgscan_enable_flag   wlan_oneimage_rename(g_en_bgscan_enable_flag)
#define g_en_mimo_blacklist   wlan_oneimage_rename(g_en_mimo_blacklist)
#define g_en_hid2d_debug   wlan_oneimage_rename(g_en_hid2d_debug)
#define g_st_hid2d_debug_switch   wlan_oneimage_rename(g_st_hid2d_debug_switch)
#define g_st_data_collect_cfg   wlan_oneimage_rename(g_st_data_collect_cfg)
#define g_en_pk_mode_swtich   wlan_oneimage_rename(g_en_pk_mode_swtich)
#define g_en_wmmac_switch   wlan_oneimage_rename(g_en_wmmac_switch)
#define g_freq_lock_control   wlan_oneimage_rename(g_freq_lock_control)
#define g_hmac_chr_connect_code   wlan_oneimage_rename(g_hmac_chr_connect_code)
#define g_hmac_chr_del_ba_info   wlan_oneimage_rename(g_hmac_chr_del_ba_info)
#define g_hmac_chr_disasoc_reason   wlan_oneimage_rename(g_hmac_chr_disasoc_reason)
#define g_host_no_ba_freq_level   wlan_oneimage_rename(g_host_no_ba_freq_level)
#define g_host_speed_freq_level   wlan_oneimage_rename(g_host_speed_freq_level)
#define g_host_tx_pkts   wlan_oneimage_rename(g_host_tx_pkts)
#define g_st_hmac_dbac_handle_info   wlan_oneimage_rename(g_st_hmac_dbac_handle_info)
#define g_l_bandwidth   wlan_oneimage_rename(g_l_bandwidth)
#define g_l_mode   wlan_oneimage_rename(g_l_mode)
#define g_mac_fsm_input_type_priority_table   wlan_oneimage_rename(g_mac_fsm_input_type_priority_table)
#define g_mac_vap_state_priority_table   wlan_oneimage_rename(g_mac_vap_state_priority_table)
#define g_pd_bss_expire_time   wlan_oneimage_rename(g_pd_bss_expire_time)
#define g_st_mac_board   wlan_oneimage_rename(g_st_mac_board)
#define g_pst_mac_device_capability   wlan_oneimage_rename(g_pst_mac_device_capability)
#define g_pst_mac_res   wlan_oneimage_rename(g_pst_mac_res)
#define g_pst_wifi_auto_ddr   wlan_oneimage_rename(g_pst_wifi_auto_ddr)
#define g_gp_sys_kobject   wlan_oneimage_rename(g_gp_sys_kobject)
#define g_sk_pacing_shift   wlan_oneimage_rename(g_sk_pacing_shift)
#define g_st_ampdu_hw   wlan_oneimage_rename(g_st_ampdu_hw)
#define g_st_data_11b_rates   wlan_oneimage_rename(g_st_data_11b_rates)
#define g_st_data_legacy_ofdm_rates   wlan_oneimage_rename(g_st_data_legacy_ofdm_rates)
#define g_st_default_regdom   wlan_oneimage_rename(g_st_default_regdom)
#define g_st_dfr_info   wlan_oneimage_rename(g_st_dfr_info)
#define g_pst_auto_ddr_freq   wlan_oneimage_rename(g_pst_auto_ddr_freq)
#define g_ddr_qos_req_count   wlan_oneimage_rename(g_ddr_qos_req_count)
#define g_ddr_freq   wlan_oneimage_rename(g_ddr_freq)
#define g_st_hmac_board   wlan_oneimage_rename(g_st_hmac_board)
#define g_st_hmac_wakelock   wlan_oneimage_rename(g_st_hmac_wakelock)
#define g_st_ip_filter_ops   wlan_oneimage_rename(g_st_ip_filter_ops)
#define g_st_iw_handler_def   wlan_oneimage_rename(g_st_iw_handler_def)
#define g_st_mac_11c_snap_header   wlan_oneimage_rename(g_st_mac_11c_snap_header)
#define g_st_mac_data_rom_cb   wlan_oneimage_rename(g_st_mac_data_rom_cb)
#define g_st_mac_frame_other_rom_cb   wlan_oneimage_rename(g_st_mac_frame_other_rom_cb)
#define g_st_mac_frame_rom_cb   wlan_oneimage_rename(g_st_mac_frame_rom_cb)
#define g_st_mac_ie_rom_cb   wlan_oneimage_rename(g_st_mac_ie_rom_cb)
#define g_st_mac_regdomain_rom_cb   wlan_oneimage_rename(g_st_mac_regdomain_rom_cb)
#define g_st_mac_regdomain   wlan_oneimage_rename(g_st_mac_regdomain)
#define g_st_mac_user_rom_other_cb   wlan_oneimage_rename(g_st_mac_user_rom_other_cb)
#define g_alg_st_mac_vap_rom_cb   wlan_oneimage_rename(g_alg_st_mac_vap_rom_cb)
#define g_st_mac_device_custom_cfg   wlan_oneimage_rename(g_st_mac_device_custom_cfg)
#define g_st_pk_mode_high_th_table   wlan_oneimage_rename(g_st_pk_mode_high_th_table)
#define g_st_pk_mode_low_th_table   wlan_oneimage_rename(g_st_pk_mode_low_th_table)
#define g_st_pmqos_requset   wlan_oneimage_rename(g_st_pmqos_requset)
#define g_st_rssi_table_11a_ofdm   wlan_oneimage_rename(g_st_rssi_table_11a_ofdm)
#define g_st_rssi_table_11b   wlan_oneimage_rename(g_st_rssi_table_11b)
#define g_st_rssi_table_11g_ofdm   wlan_oneimage_rename(g_st_rssi_table_11g_ofdm)
#define g_st_rssi_table_ht20_ofdm   wlan_oneimage_rename(g_st_rssi_table_ht20_ofdm)
#define g_st_rssi_table_ht40_ofdm   wlan_oneimage_rename(g_st_rssi_table_ht40_ofdm)
#define g_st_rssi_table_vht80_ofdm   wlan_oneimage_rename(g_st_rssi_table_vht80_ofdm)
#define g_st_rx_buffer_size_stru   wlan_oneimage_rename(g_st_rx_buffer_size_stru)
#define g_st_rxdata_thread   wlan_oneimage_rename(g_st_rxdata_thread)
#define g_st_rx_dyn_bypass_extlna_switch   wlan_oneimage_rename(g_st_rx_dyn_bypass_extlna_switch)
#define g_st_small_amsdu_switch   wlan_oneimage_rename(g_st_small_amsdu_switch)
#define g_st_tcp_ack_buf_switch   wlan_oneimage_rename(g_st_tcp_ack_buf_switch)
#define g_st_tcp_ack_filter   wlan_oneimage_rename(g_st_tcp_ack_filter)
#define g_st_tx_large_amsdu   wlan_oneimage_rename(g_st_tx_large_amsdu)
#define g_st_wal_drv_func_hook   wlan_oneimage_rename(g_st_wal_drv_func_hook)
#define g_st_wal_ethtool_ops   wlan_oneimage_rename(g_st_wal_ethtool_ops)
#define g_st_wal_net_dev_ops   wlan_oneimage_rename(g_st_wal_net_dev_ops)
#define g_st_wal_wakelock   wlan_oneimage_rename(g_st_wal_wakelock)
#define g_st_wifi_callback   wlan_oneimage_rename(g_st_wifi_callback)
#define g_st_wifi_load   wlan_oneimage_rename(g_st_wifi_load)
#define g_st_wifi_radio_stat   wlan_oneimage_rename(g_st_wifi_radio_stat)
#define g_uc_cookie_array_bitmap   wlan_oneimage_rename(g_uc_cookie_array_bitmap)
#define g_uc_dev_lte_gpio_level   wlan_oneimage_rename(g_uc_dev_lte_gpio_level)
#define g_uc_host_rx_ampdu_amsdu   wlan_oneimage_rename(g_uc_host_rx_ampdu_amsdu)
#define g_uc_mbo_switch   wlan_oneimage_rename(g_uc_mbo_switch)
#define g_uc_dbac_dynamic_switch   wlan_oneimage_rename(g_uc_dbac_dynamic_switch)
#define g_uc_uapsd_cap   wlan_oneimage_rename(g_uc_uapsd_cap)
#define g_corram_data_20m   wlan_oneimage_rename(g_corram_data_20m)
#define g_corram_data_40m   wlan_oneimage_rename(g_corram_data_40m)
#define g_corram_data_80m   wlan_oneimage_rename(g_corram_data_80m)
#define g_orig_cpu_max_freq   wlan_oneimage_rename(g_orig_cpu_max_freq)
#define g_orig_cpu_min_freq   wlan_oneimage_rename(g_orig_cpu_min_freq)
#define g_orig_ddr_max_freq   wlan_oneimage_rename(g_orig_ddr_max_freq)
#define g_orig_ddr_min_freq   wlan_oneimage_rename(g_orig_ddr_min_freq)
#define g_us_efuse_buffer   wlan_oneimage_rename(g_us_efuse_buffer)
#define g_wal_config_seq_num   wlan_oneimage_rename(g_wal_config_seq_num)
#define g_wifi_init_flag   wlan_oneimage_rename(g_wifi_init_flag)
#define g_wifi_init_ret   wlan_oneimage_rename(g_wifi_init_ret)
#define g_wlan_cali_completed   wlan_oneimage_rename(g_wlan_cali_completed)
#define g_wait_wlan_power_on_cali   wlan_oneimage_rename(g_wait_wlan_power_on_cali)
#define g_st_default_hiex_cap wlan_oneimage_rename(g_st_default_hiex_cap)
#define g_bcast_addr wlan_oneimage_rename(g_bcast_addr)
#define g_oam_stat_info wlan_oneimage_rename(g_oam_stat_info)
#define g_chba_ps_throught_thres wlan_oneimage_rename(g_chba_ps_throught_thres)

#define mpxx_host_main_exit   wlan_oneimage_rename(mpxx_host_main_exit)
#define mpxx_host_main_init   wlan_oneimage_rename(mpxx_host_main_init)
#define hisi_cpufreq_get_maxfreq   wlan_oneimage_rename(hisi_cpufreq_get_maxfreq)
#define host_module_init   wlan_oneimage_rename(host_module_init)
#define hwifi_cfg_host_global_init_param   wlan_oneimage_rename(hwifi_cfg_host_global_init_param)
#define hwifi_cfg_pwr_ref_delta   wlan_oneimage_rename(hwifi_cfg_pwr_ref_delta)
#define hwifi_check_pwr_ref_delta   wlan_oneimage_rename(hwifi_check_pwr_ref_delta)
#define hwifi_config_host_global_11ax_ini_param   wlan_oneimage_rename(hwifi_config_host_global_11ax_ini_param)

#define hwifi_config_cpu_freq_ini_param   wlan_oneimage_rename(hwifi_config_cpu_freq_ini_param)
#define hwifi_config_host_global_ini_param   wlan_oneimage_rename(hwifi_config_host_global_ini_param)

#define hwifi_config_init_force   wlan_oneimage_rename(hwifi_config_init_force)
#define hwifi_config_init_ini   wlan_oneimage_rename(hwifi_config_init_ini)

#define hwifi_config_init    wlan_oneimage_rename(hwifi_config_init)

#define hwifi_get_cfg_params    wlan_oneimage_rename(hwifi_get_cfg_params)
#define hwifi_get_country_code    wlan_oneimage_rename(hwifi_get_country_code)

#define hwifi_get_init_priv_value    wlan_oneimage_rename(hwifi_get_init_priv_value)
#define hwifi_get_init_value    wlan_oneimage_rename(hwifi_get_init_value)
#define hwifi_get_mac_addr    wlan_oneimage_rename(hwifi_get_mac_addr)
#define hwifi_get_nvram_param    wlan_oneimage_rename(hwifi_get_nvram_param)

#define hwifi_get_regdomain_from_country_code    wlan_oneimage_rename(hwifi_get_regdomain_from_country_code)

#define hwifi_is_regdomain_changed    wlan_oneimage_rename(hwifi_is_regdomain_changed)
#define hwifi_set_country_code    wlan_oneimage_rename(hwifi_set_country_code)
#define host_params_init_first wlan_oneimage_rename(host_params_init_first)
#define hwifi_custom_adapt_device_ini_param wlan_oneimage_rename(hwifi_custom_adapt_device_ini_param)

#endif /* end of #if !defined(WIN32) */

#endif /* end of wlan_oneimage_define.h */
