
-include $(srctree)/drivers/platform_drivers/modem/drv/product_config/product_config.mk

obj-$(CONFIG_SIM_HOTPLUG_SPMI)     += sim_hotplug.o
obj-$(CONFIG_SIM_HOTPLUG_SPMI)     += sim_hw_mgr.o
obj-$(CONFIG_SIM_HOTPLUG_SPMI)     += sim_hw_service.o

