# Hisilicon IPP modules Makefile


obj-$(CONFIG_HISPIPP_V500) += arfeature_drv.o
obj-$(CONFIG_HISPIPP_V500) += cmdlst_drv.o
obj-$(CONFIG_HISPIPP_V500) += compare_drv.o
obj-$(CONFIG_HISPIPP_V500) += cvdr_drv.o
obj-$(CONFIG_HISPIPP_V500) += cvdr_opt.o
obj-$(CONFIG_HISPIPP_V500) += klt_drv.o
obj-$(CONFIG_HISPIPP_V500) += mc_drv.o
obj-$(CONFIG_HISPIPP_V500) += orb_enh_drv.o
obj-$(CONFIG_HISPIPP_V500) += reorder_drv.o

