ccflags-y += -Wextra -Wdate-time -Wfloat-equal -Wformat=2 -Wshadow

obj-y += xge_main.o xge_drv.o xge_ring.o xge_core.o xge_ethtool.o xge_statistics.o xge_export.o
obj-$(CONFIG_NET_VENDOR_HIXGEMAC_GPTP) += xge_ptp.o xge_hwstamp.o
obj-$(CONFIG_DFX_DEBUG_FS) += xge_debugfs.o
obj-y += hixgemac/
obj-y += platform/
