#
# Makefile for kernel echub driver.
#

obj-$(CONFIG_ARMPC_ECHUB_I2C)	+= echub_i2c.o
obj-y	+= keyboard/
obj-$(CONFIG_ARMPC_ECHUB_PMSYNC)	  += power/
obj-$(CONFIG_ARMPC_ECHUB_BATTERY)	  += battery/
obj-$(CONFIG_ARMPC_ECHUB_FNLED)		  += fnled/
obj-$(CONFIG_PC_ECHUB_THERMAL)		  += thermal/
obj-$(CONFIG_ARMPC_ECHUB_LOG)		  += echub_log/
obj-$(CONFIG_ARMPC_ECHUB_UPDATE)	  += echub_update/
obj-$(CONFIG_ARMPC_ECHUB_RTC)		  += rtc/
