
-include $(srctree)/drivers/platform_drivers/modem/drv/product_config/product_config.mk

subdir-ccflags-y := -Wall -Werror
obj-y       += msg_alias.o
obj-y       += msg_base.o
obj-y       += msg_tskque.o
obj-y       += msg_event.o
obj-y       += msg_mem.o
obj-y       += msg_core.o
obj-y       += msg_lite.o
obj-y       += msg_cmsg.o
obj-y       += msg_mntn.o
obj-y       += msg_reset.o
obj-y       += fipc_ops.o


GCOV_PROFILE := y