/*******************************************************************
 * Copyright (c) Hisilicon Technologies Co., Ltd. 2012-2018. All rights reserved.
 * File name    reorder_reg_offset.h
 * Description:
 *
 * Date        2021-12-28
 ******************************************************************/

#ifndef __REORDER_REG_OFFSET_H__
#define __REORDER_REG_OFFSET_H__

/******************************************************************************/
/*                     REORDER Registers' Definitions                         */
/******************************************************************************/

#define REORDER_REORDER_CFG_REG    0x0   /* Reorder Config */
#define REORDER_BLOCK_CFG_REG      0x4   /* BLOCK Config */
#define REORDER_TOTAL_KPT_NUM_REG  0x8   /* Total kpt number */
#define REORDER_PREFETCH_CFG_REG   0x10  /* Configure the prefetch */
#define REORDER_DEBUG_0_REG        0x20  /* Debug 0 */
#define REORDER_DEBUG_1_REG        0x24  /* Debug 1 */
#define REORDER_EC_0_REG           0x28  /* ec 0 */
#define REORDER_EC_1_REG           0x2C  /* ec 1 */
#define REORDER_KPT_NUMBER_0_REG   0x100 /* Feature number in each block */
#define REORDER_KPT_NUMBER_1_REG   0x104 /* Feature number in each block */
#define REORDER_KPT_NUMBER_2_REG   0x108 /* Feature number in each block */
#define REORDER_KPT_NUMBER_3_REG   0x10C /* Feature number in each block */
#define REORDER_KPT_NUMBER_4_REG   0x110 /* Feature number in each block */
#define REORDER_KPT_NUMBER_5_REG   0x114 /* Feature number in each block */
#define REORDER_KPT_NUMBER_6_REG   0x118 /* Feature number in each block */
#define REORDER_KPT_NUMBER_7_REG   0x11C /* Feature number in each block */
#define REORDER_KPT_NUMBER_8_REG   0x120 /* Feature number in each block */
#define REORDER_KPT_NUMBER_9_REG   0x124 /* Feature number in each block */
#define REORDER_KPT_NUMBER_10_REG  0x128 /* Feature number in each block */
#define REORDER_KPT_NUMBER_11_REG  0x12C /* Feature number in each block */
#define REORDER_KPT_NUMBER_12_REG  0x130 /* Feature number in each block */
#define REORDER_KPT_NUMBER_13_REG  0x134 /* Feature number in each block */
#define REORDER_KPT_NUMBER_14_REG  0x138 /* Feature number in each block */
#define REORDER_KPT_NUMBER_15_REG  0x13C /* Feature number in each block */
#define REORDER_KPT_NUMBER_16_REG  0x140 /* Feature number in each block */
#define REORDER_KPT_NUMBER_17_REG  0x144 /* Feature number in each block */
#define REORDER_KPT_NUMBER_18_REG  0x148 /* Feature number in each block */
#define REORDER_KPT_NUMBER_19_REG  0x14C /* Feature number in each block */
#define REORDER_KPT_NUMBER_20_REG  0x150 /* Feature number in each block */
#define REORDER_KPT_NUMBER_21_REG  0x154 /* Feature number in each block */
#define REORDER_KPT_NUMBER_22_REG  0x158 /* Feature number in each block */
#define REORDER_KPT_NUMBER_23_REG  0x15C /* Feature number in each block */
#define REORDER_KPT_NUMBER_24_REG  0x160 /* Feature number in each block */
#define REORDER_KPT_NUMBER_25_REG  0x164 /* Feature number in each block */
#define REORDER_KPT_NUMBER_26_REG  0x168 /* Feature number in each block */
#define REORDER_KPT_NUMBER_27_REG  0x16C /* Feature number in each block */
#define REORDER_KPT_NUMBER_28_REG  0x170 /* Feature number in each block */
#define REORDER_KPT_NUMBER_29_REG  0x174 /* Feature number in each block */
#define REORDER_KPT_NUMBER_30_REG  0x178 /* Feature number in each block */
#define REORDER_KPT_NUMBER_31_REG  0x17C /* Feature number in each block */
#define REORDER_KPT_NUMBER_32_REG  0x180 /* Feature number in each block */
#define REORDER_KPT_NUMBER_33_REG  0x184 /* Feature number in each block */
#define REORDER_KPT_NUMBER_34_REG  0x188 /* Feature number in each block */
#define REORDER_KPT_NUMBER_35_REG  0x18C /* Feature number in each block */
#define REORDER_KPT_NUMBER_36_REG  0x190 /* Feature number in each block */
#define REORDER_KPT_NUMBER_37_REG  0x194 /* Feature number in each block */
#define REORDER_KPT_NUMBER_38_REG  0x198 /* Feature number in each block */
#define REORDER_KPT_NUMBER_39_REG  0x19C /* Feature number in each block */
#define REORDER_KPT_NUMBER_40_REG  0x1A0 /* Feature number in each block */
#define REORDER_KPT_NUMBER_41_REG  0x1A4 /* Feature number in each block */
#define REORDER_KPT_NUMBER_42_REG  0x1A8 /* Feature number in each block */
#define REORDER_KPT_NUMBER_43_REG  0x1AC /* Feature number in each block */
#define REORDER_KPT_NUMBER_44_REG  0x1B0 /* Feature number in each block */
#define REORDER_KPT_NUMBER_45_REG  0x1B4 /* Feature number in each block */
#define REORDER_KPT_NUMBER_46_REG  0x1B8 /* Feature number in each block */
#define REORDER_KPT_NUMBER_47_REG  0x1BC /* Feature number in each block */
#define REORDER_KPT_NUMBER_48_REG  0x1C0 /* Feature number in each block */
#define REORDER_KPT_NUMBER_49_REG  0x1C4 /* Feature number in each block */
#define REORDER_KPT_NUMBER_50_REG  0x1C8 /* Feature number in each block */
#define REORDER_KPT_NUMBER_51_REG  0x1CC /* Feature number in each block */
#define REORDER_KPT_NUMBER_52_REG  0x1D0 /* Feature number in each block */
#define REORDER_KPT_NUMBER_53_REG  0x1D4 /* Feature number in each block */
#define REORDER_KPT_NUMBER_54_REG  0x1D8 /* Feature number in each block */
#define REORDER_KPT_NUMBER_55_REG  0x1DC /* Feature number in each block */
#define REORDER_KPT_NUMBER_56_REG  0x1E0 /* Feature number in each block */
#define REORDER_KPT_NUMBER_57_REG  0x1E4 /* Feature number in each block */
#define REORDER_KPT_NUMBER_58_REG  0x1E8 /* Feature number in each block */
#define REORDER_KPT_NUMBER_59_REG  0x1EC /* Feature number in each block */
#define REORDER_KPT_NUMBER_60_REG  0x1F0 /* Feature number in each block */
#define REORDER_KPT_NUMBER_61_REG  0x1F4 /* Feature number in each block */
#define REORDER_KPT_NUMBER_62_REG  0x1F8 /* Feature number in each block */
#define REORDER_KPT_NUMBER_63_REG  0x1FC /* Feature number in each block */
#define REORDER_KPT_NUMBER_64_REG  0x200 /* Feature number in each block */
#define REORDER_KPT_NUMBER_65_REG  0x204 /* Feature number in each block */
#define REORDER_KPT_NUMBER_66_REG  0x208 /* Feature number in each block */
#define REORDER_KPT_NUMBER_67_REG  0x20C /* Feature number in each block */
#define REORDER_KPT_NUMBER_68_REG  0x210 /* Feature number in each block */
#define REORDER_KPT_NUMBER_69_REG  0x214 /* Feature number in each block */
#define REORDER_KPT_NUMBER_70_REG  0x218 /* Feature number in each block */
#define REORDER_KPT_NUMBER_71_REG  0x21C /* Feature number in each block */
#define REORDER_KPT_NUMBER_72_REG  0x220 /* Feature number in each block */
#define REORDER_KPT_NUMBER_73_REG  0x224 /* Feature number in each block */
#define REORDER_KPT_NUMBER_74_REG  0x228 /* Feature number in each block */
#define REORDER_KPT_NUMBER_75_REG  0x22C /* Feature number in each block */
#define REORDER_KPT_NUMBER_76_REG  0x230 /* Feature number in each block */
#define REORDER_KPT_NUMBER_77_REG  0x234 /* Feature number in each block */
#define REORDER_KPT_NUMBER_78_REG  0x238 /* Feature number in each block */
#define REORDER_KPT_NUMBER_79_REG  0x23C /* Feature number in each block */
#define REORDER_KPT_NUMBER_80_REG  0x240 /* Feature number in each block */
#define REORDER_KPT_NUMBER_81_REG  0x244 /* Feature number in each block */
#define REORDER_KPT_NUMBER_82_REG  0x248 /* Feature number in each block */
#define REORDER_KPT_NUMBER_83_REG  0x24C /* Feature number in each block */
#define REORDER_KPT_NUMBER_84_REG  0x250 /* Feature number in each block */
#define REORDER_KPT_NUMBER_85_REG  0x254 /* Feature number in each block */
#define REORDER_KPT_NUMBER_86_REG  0x258 /* Feature number in each block */
#define REORDER_KPT_NUMBER_87_REG  0x25C /* Feature number in each block */
#define REORDER_KPT_NUMBER_88_REG  0x260 /* Feature number in each block */
#define REORDER_KPT_NUMBER_89_REG  0x264 /* Feature number in each block */
#define REORDER_KPT_NUMBER_90_REG  0x268 /* Feature number in each block */
#define REORDER_KPT_NUMBER_91_REG  0x26C /* Feature number in each block */
#define REORDER_KPT_NUMBER_92_REG  0x270 /* Feature number in each block */
#define REORDER_KPT_NUMBER_93_REG  0x274 /* Feature number in each block */
#define REORDER_KPT_NUMBER_94_REG  0x278 /* Feature number in each block */
#define REORDER_KPT_NUMBER_95_REG  0x27C /* Feature number in each block */
#define REORDER_KPT_NUMBER_96_REG  0x280 /* Feature number in each block */
#define REORDER_KPT_NUMBER_97_REG  0x284 /* Feature number in each block */
#define REORDER_KPT_NUMBER_98_REG  0x288 /* Feature number in each block */
#define REORDER_KPT_NUMBER_99_REG  0x28C /* Feature number in each block */
#define REORDER_KPT_NUMBER_100_REG 0x290 /* Feature number in each block */
#define REORDER_KPT_NUMBER_101_REG 0x294 /* Feature number in each block */
#define REORDER_KPT_NUMBER_102_REG 0x298 /* Feature number in each block */
#define REORDER_KPT_NUMBER_103_REG 0x29C /* Feature number in each block */
#define REORDER_KPT_NUMBER_104_REG 0x2A0 /* Feature number in each block */
#define REORDER_KPT_NUMBER_105_REG 0x2A4 /* Feature number in each block */
#define REORDER_KPT_NUMBER_106_REG 0x2A8 /* Feature number in each block */
#define REORDER_KPT_NUMBER_107_REG 0x2AC /* Feature number in each block */
#define REORDER_KPT_NUMBER_108_REG 0x2B0 /* Feature number in each block */
#define REORDER_KPT_NUMBER_109_REG 0x2B4 /* Feature number in each block */
#define REORDER_KPT_NUMBER_110_REG 0x2B8 /* Feature number in each block */
#define REORDER_KPT_NUMBER_111_REG 0x2BC /* Feature number in each block */
#define REORDER_KPT_NUMBER_112_REG 0x2C0 /* Feature number in each block */
#define REORDER_KPT_NUMBER_113_REG 0x2C4 /* Feature number in each block */
#define REORDER_KPT_NUMBER_114_REG 0x2C8 /* Feature number in each block */
#define REORDER_KPT_NUMBER_115_REG 0x2CC /* Feature number in each block */
#define REORDER_KPT_NUMBER_116_REG 0x2D0 /* Feature number in each block */
#define REORDER_KPT_NUMBER_117_REG 0x2D4 /* Feature number in each block */
#define REORDER_KPT_NUMBER_118_REG 0x2D8 /* Feature number in each block */
#define REORDER_KPT_NUMBER_119_REG 0x2DC /* Feature number in each block */
#define REORDER_KPT_NUMBER_120_REG 0x2E0 /* Feature number in each block */
#define REORDER_KPT_NUMBER_121_REG 0x2E4 /* Feature number in each block */
#define REORDER_KPT_NUMBER_122_REG 0x2E8 /* Feature number in each block */
#define REORDER_KPT_NUMBER_123_REG 0x2EC /* Feature number in each block */
#define REORDER_KPT_NUMBER_124_REG 0x2F0 /* Feature number in each block */
#define REORDER_KPT_NUMBER_125_REG 0x2F4 /* Feature number in each block */
#define REORDER_KPT_NUMBER_126_REG 0x2F8 /* Feature number in each block */
#define REORDER_KPT_NUMBER_127_REG 0x2FC /* Feature number in each block */
#define REORDER_KPT_NUMBER_128_REG 0x300 /* Feature number in each block */
#define REORDER_KPT_NUMBER_129_REG 0x304 /* Feature number in each block */
#define REORDER_KPT_NUMBER_130_REG 0x308 /* Feature number in each block */
#define REORDER_KPT_NUMBER_131_REG 0x30C /* Feature number in each block */
#define REORDER_KPT_NUMBER_132_REG 0x310 /* Feature number in each block */
#define REORDER_KPT_NUMBER_133_REG 0x314 /* Feature number in each block */
#define REORDER_KPT_NUMBER_134_REG 0x318 /* Feature number in each block */
#define REORDER_KPT_NUMBER_135_REG 0x31C /* Feature number in each block */
#define REORDER_KPT_NUMBER_136_REG 0x320 /* Feature number in each block */
#define REORDER_KPT_NUMBER_137_REG 0x324 /* Feature number in each block */
#define REORDER_KPT_NUMBER_138_REG 0x328 /* Feature number in each block */
#define REORDER_KPT_NUMBER_139_REG 0x32C /* Feature number in each block */
#define REORDER_KPT_NUMBER_140_REG 0x330 /* Feature number in each block */
#define REORDER_KPT_NUMBER_141_REG 0x334 /* Feature number in each block */
#define REORDER_KPT_NUMBER_142_REG 0x338 /* Feature number in each block */
#define REORDER_KPT_NUMBER_143_REG 0x33C /* Feature number in each block */
#define REORDER_KPT_NUMBER_144_REG 0x340 /* Feature number in each block */
#define REORDER_KPT_NUMBER_145_REG 0x344 /* Feature number in each block */
#define REORDER_KPT_NUMBER_146_REG 0x348 /* Feature number in each block */
#define REORDER_KPT_NUMBER_147_REG 0x34C /* Feature number in each block */
#define REORDER_KPT_NUMBER_148_REG 0x350 /* Feature number in each block */
#define REORDER_KPT_NUMBER_149_REG 0x354 /* Feature number in each block */
#define REORDER_KPT_NUMBER_150_REG 0x358 /* Feature number in each block */
#define REORDER_KPT_NUMBER_151_REG 0x35C /* Feature number in each block */
#define REORDER_KPT_NUMBER_152_REG 0x360 /* Feature number in each block */
#define REORDER_KPT_NUMBER_153_REG 0x364 /* Feature number in each block */
#define REORDER_KPT_NUMBER_154_REG 0x368 /* Feature number in each block */
#define REORDER_KPT_NUMBER_155_REG 0x36C /* Feature number in each block */
#define REORDER_KPT_NUMBER_156_REG 0x370 /* Feature number in each block */
#define REORDER_KPT_NUMBER_157_REG 0x374 /* Feature number in each block */
#define REORDER_KPT_NUMBER_158_REG 0x378 /* Feature number in each block */
#define REORDER_KPT_NUMBER_159_REG 0x37C /* Feature number in each block */
#define REORDER_KPT_NUMBER_160_REG 0x380 /* Feature number in each block */
#define REORDER_KPT_NUMBER_161_REG 0x384 /* Feature number in each block */
#define REORDER_KPT_NUMBER_162_REG 0x388 /* Feature number in each block */
#define REORDER_KPT_NUMBER_163_REG 0x38C /* Feature number in each block */
#define REORDER_KPT_NUMBER_164_REG 0x390 /* Feature number in each block */
#define REORDER_KPT_NUMBER_165_REG 0x394 /* Feature number in each block */
#define REORDER_KPT_NUMBER_166_REG 0x398 /* Feature number in each block */
#define REORDER_KPT_NUMBER_167_REG 0x39C /* Feature number in each block */
#define REORDER_KPT_NUMBER_168_REG 0x3A0 /* Feature number in each block */
#define REORDER_KPT_NUMBER_169_REG 0x3A4 /* Feature number in each block */
#define REORDER_KPT_NUMBER_170_REG 0x3A8 /* Feature number in each block */
#define REORDER_KPT_NUMBER_171_REG 0x3AC /* Feature number in each block */
#define REORDER_KPT_NUMBER_172_REG 0x3B0 /* Feature number in each block */
#define REORDER_KPT_NUMBER_173_REG 0x3B4 /* Feature number in each block */
#define REORDER_KPT_NUMBER_174_REG 0x3B8 /* Feature number in each block */
#define REORDER_KPT_NUMBER_175_REG 0x3BC /* Feature number in each block */
#define REORDER_KPT_NUMBER_176_REG 0x3C0 /* Feature number in each block */
#define REORDER_KPT_NUMBER_177_REG 0x3C4 /* Feature number in each block */
#define REORDER_KPT_NUMBER_178_REG 0x3C8 /* Feature number in each block */
#define REORDER_KPT_NUMBER_179_REG 0x3CC /* Feature number in each block */
#define REORDER_KPT_NUMBER_180_REG 0x3D0 /* Feature number in each block */
#define REORDER_KPT_NUMBER_181_REG 0x3D4 /* Feature number in each block */
#define REORDER_KPT_NUMBER_182_REG 0x3D8 /* Feature number in each block */
#define REORDER_KPT_NUMBER_183_REG 0x3DC /* Feature number in each block */
#define REORDER_KPT_NUMBER_184_REG 0x3E0 /* Feature number in each block */
#define REORDER_KPT_NUMBER_185_REG 0x3E4 /* Feature number in each block */
#define REORDER_KPT_NUMBER_186_REG 0x3E8 /* Feature number in each block */
#define REORDER_KPT_NUMBER_187_REG 0x3EC /* Feature number in each block */
#define REORDER_KPT_NUMBER_188_REG 0x3F0 /* Feature number in each block */
#define REORDER_KPT_NUMBER_189_REG 0x3F4 /* Feature number in each block */
#define REORDER_KPT_NUMBER_190_REG 0x3F8 /* Feature number in each block */
#define REORDER_KPT_NUMBER_191_REG 0x3FC /* Feature number in each block */
#define REORDER_KPT_NUMBER_192_REG 0x400 /* Feature number in each block */
#define REORDER_KPT_NUMBER_193_REG 0x404 /* Feature number in each block */
#define REORDER_KPT_NUMBER_194_REG 0x408 /* Feature number in each block */
#define REORDER_KPT_NUMBER_195_REG 0x40C /* Feature number in each block */
#define REORDER_KPT_NUMBER_196_REG 0x410 /* Feature number in each block */
#define REORDER_KPT_NUMBER_197_REG 0x414 /* Feature number in each block */
#define REORDER_KPT_NUMBER_198_REG 0x418 /* Feature number in each block */
#define REORDER_KPT_NUMBER_199_REG 0x41C /* Feature number in each block */
#define REORDER_KPT_NUMBER_200_REG 0x420 /* Feature number in each block */
#define REORDER_KPT_NUMBER_201_REG 0x424 /* Feature number in each block */
#define REORDER_KPT_NUMBER_202_REG 0x428 /* Feature number in each block */
#define REORDER_KPT_NUMBER_203_REG 0x42C /* Feature number in each block */
#define REORDER_KPT_NUMBER_204_REG 0x430 /* Feature number in each block */
#define REORDER_KPT_NUMBER_205_REG 0x434 /* Feature number in each block */
#define REORDER_KPT_NUMBER_206_REG 0x438 /* Feature number in each block */
#define REORDER_KPT_NUMBER_207_REG 0x43C /* Feature number in each block */
#define REORDER_KPT_NUMBER_208_REG 0x440 /* Feature number in each block */
#define REORDER_KPT_NUMBER_209_REG 0x444 /* Feature number in each block */
#define REORDER_KPT_NUMBER_210_REG 0x448 /* Feature number in each block */
#define REORDER_KPT_NUMBER_211_REG 0x44C /* Feature number in each block */
#define REORDER_KPT_NUMBER_212_REG 0x450 /* Feature number in each block */
#define REORDER_KPT_NUMBER_213_REG 0x454 /* Feature number in each block */
#define REORDER_KPT_NUMBER_214_REG 0x458 /* Feature number in each block */
#define REORDER_KPT_NUMBER_215_REG 0x45C /* Feature number in each block */
#define REORDER_KPT_NUMBER_216_REG 0x460 /* Feature number in each block */
#define REORDER_KPT_NUMBER_217_REG 0x464 /* Feature number in each block */
#define REORDER_KPT_NUMBER_218_REG 0x468 /* Feature number in each block */
#define REORDER_KPT_NUMBER_219_REG 0x46C /* Feature number in each block */
#define REORDER_KPT_NUMBER_220_REG 0x470 /* Feature number in each block */
#define REORDER_KPT_NUMBER_221_REG 0x474 /* Feature number in each block */
#define REORDER_KPT_NUMBER_222_REG 0x478 /* Feature number in each block */
#define REORDER_KPT_NUMBER_223_REG 0x47C /* Feature number in each block */
#define REORDER_KPT_NUMBER_224_REG 0x480 /* Feature number in each block */
#define REORDER_KPT_NUMBER_225_REG 0x484 /* Feature number in each block */
#define REORDER_KPT_NUMBER_226_REG 0x488 /* Feature number in each block */
#define REORDER_KPT_NUMBER_227_REG 0x48C /* Feature number in each block */
#define REORDER_KPT_NUMBER_228_REG 0x490 /* Feature number in each block */
#define REORDER_KPT_NUMBER_229_REG 0x494 /* Feature number in each block */
#define REORDER_KPT_NUMBER_230_REG 0x498 /* Feature number in each block */
#define REORDER_KPT_NUMBER_231_REG 0x49C /* Feature number in each block */
#define REORDER_KPT_NUMBER_232_REG 0x4A0 /* Feature number in each block */
#define REORDER_KPT_NUMBER_233_REG 0x4A4 /* Feature number in each block */
#define REORDER_KPT_NUMBER_234_REG 0x4A8 /* Feature number in each block */
#define REORDER_KPT_NUMBER_235_REG 0x4AC /* Feature number in each block */
#define REORDER_KPT_NUMBER_236_REG 0x4B0 /* Feature number in each block */
#define REORDER_KPT_NUMBER_237_REG 0x4B4 /* Feature number in each block */
#define REORDER_KPT_NUMBER_238_REG 0x4B8 /* Feature number in each block */
#define REORDER_KPT_NUMBER_239_REG 0x4BC /* Feature number in each block */
#define REORDER_KPT_NUMBER_240_REG 0x4C0 /* Feature number in each block */
#define REORDER_KPT_NUMBER_241_REG 0x4C4 /* Feature number in each block */
#define REORDER_KPT_NUMBER_242_REG 0x4C8 /* Feature number in each block */
#define REORDER_KPT_NUMBER_243_REG 0x4CC /* Feature number in each block */
#define REORDER_KPT_NUMBER_244_REG 0x4D0 /* Feature number in each block */
#define REORDER_KPT_NUMBER_245_REG 0x4D4 /* Feature number in each block */
#define REORDER_KPT_NUMBER_246_REG 0x4D8 /* Feature number in each block */
#define REORDER_KPT_NUMBER_247_REG 0x4DC /* Feature number in each block */
#define REORDER_KPT_NUMBER_248_REG 0x4E0 /* Feature number in each block */
#define REORDER_KPT_NUMBER_249_REG 0x4E4 /* Feature number in each block */
#define REORDER_KPT_NUMBER_250_REG 0x4E8 /* Feature number in each block */
#define REORDER_KPT_NUMBER_251_REG 0x4EC /* Feature number in each block */
#define REORDER_KPT_NUMBER_252_REG 0x4F0 /* Feature number in each block */
#define REORDER_KPT_NUMBER_253_REG 0x4F4 /* Feature number in each block */
#define REORDER_KPT_NUMBER_254_REG 0x4F8 /* Feature number in each block */
#define REORDER_KPT_NUMBER_255_REG 0x4FC /* Feature number in each block */

#endif // __REORDER_REG_OFFSET_H__
