FKD_DIR :=$(srctree)/platform_source/ffrt/ffts/fkd
FPD_DIR :=$(srctree)/platform_source/ffrt/ffts/fpd
UNIFORM_ID_DIR :=$(srctree)/platform_source/ffrt/uniform_id

export FKD_DIR FPD_DIR UNIFORM_ID_DIR

obj-$(CONFIG_FFRT_FFTS) += fkd/
obj-$(CONFIG_FFRT_FFTS) += fpd/