ccflags-y += -I$(srctree)/drivers/block/zram
obj-y += hyperhold_core.o hyperhold_manager.o hyperhold_schedule.o hyperhold_list.o hyperhold_area.o hyperhold_perf.o hyperhold_stats.o hyperhold_ctrl.o hyperhold_lru_rmap.o hyperhold_cache.o hyperhold_file.o hyperhold_space.o
obj-$(CONFIG_HH_REMAP) += hyperhold_remap.o
obj-$(CONFIG_HH_REMAP_DEBUG) += hyperhold_remap_debug.o
obj-$(CONFIG_HP_TURBO) += hyperhold_turbo.o
obj-$(CONFIG_HP_TURBO_DEBUG) += hyperhold_turbo_debug.o
