obj-$(CONFIG_SCHARGER_V700)          += scharger_coul/
obj-$(CONFIG_COUL_PMIC6X55V500)      += pmic_coul/
obj-$(CONFIG_COUL_PMIC6X21V900)      += pmic_coul/
obj-$(CONFIG_COUL_PMIC6X21BV100)      += pmic_coul/
