obj-$(CONFIG_HW_PD_COMMON) += hw_pd_entry.o
obj-$(CONFIG_HW_PD_COMMON) += hw_pd_misc.o
obj-$(CONFIG_HW_PD_COMMON) += hw_pd_usb.o
obj-$(CONFIG_HW_PD_COMMON) += hw_pd_power.o
obj-$(CONFIG_HW_PD_COMMON) += hw_pd_event.o

