CAMERA_SOC_CHIP_NAME := $(strip $(subst ", ,$(CONFIG_VENDOR_CHIP_PREFIX)))

ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera

ifeq ($(CONFIG_KERNEL_CAMERA_ISPV110), y)
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform/$(CAMERA_SOC_CHIP_NAME)
obj-y += $(CAMERA_SOC_CHIP_NAME)/
endif

ifeq ($(CONFIG_KERNEL_CAMERA_ISPV150), y)
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform/$(CAMERA_SOC_CHIP_NAME)
obj-y += $(CAMERA_SOC_CHIP_NAME)/
endif

ifeq ($(CONFIG_KERNEL_CAMERA_ISPV160), y)
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform/$(CAMERA_SOC_CHIP_NAME)
obj-y += $(CAMERA_SOC_CHIP_NAME)/
endif

ifeq ($(CONFIG_KERNEL_CAMERA_ISPV120), y)
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform/$(CAMERA_SOC_CHIP_NAME)
obj-y += $(CAMERA_SOC_CHIP_NAME)/
endif

ifeq ($(CONFIG_KERNEL_CAMERA_ISPV130), y)
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform/$(CAMERA_SOC_CHIP_NAME)
obj-y += $(CAMERA_SOC_CHIP_NAME)/
endif

ifeq ($(CONFIG_KERNEL_CAMERA_ISPV200), y)
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform/$(CAMERA_SOC_CHIP_NAME)
obj-y += $(CAMERA_SOC_CHIP_NAME)/
endif

ifeq ($(CONFIG_KERNEL_CAMERA_ISPV250), y)
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform/$(CAMERA_SOC_CHIP_NAME)
obj-y += $(CAMERA_SOC_CHIP_NAME)/
endif

ifeq ($(CONFIG_KERNEL_CAMERA_ISPV210), y)
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform/$(CAMERA_SOC_CHIP_NAME)
obj-y += $(CAMERA_SOC_CHIP_NAME)/
endif

ifeq ($(CONFIG_KERNEL_CAMERA_ISPV310), y)
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform/$(CAMERA_SOC_CHIP_NAME)
obj-y += $(CAMERA_SOC_CHIP_NAME)/
endif

ifeq ($(CONFIG_KERNEL_CAMERA_ISPV300), y)
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform/$(CAMERA_SOC_CHIP_NAME)
obj-y += $(CAMERA_SOC_CHIP_NAME)/
endif

ifeq ($(CONFIG_KERNEL_CAMERA_ISPV350), y)
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform/$(CAMERA_SOC_CHIP_NAME)
obj-y += $(CAMERA_SOC_CHIP_NAME)/
endif

ifeq ($(CONFIG_KERNEL_CAMERA_ISPV360), y)
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform/charlotte
obj-y += charlotte/
endif

ifeq ($(CONFIG_KERNEL_CAMERA_ISPV500), y)
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform/$(CAMERA_SOC_CHIP_NAME)
obj-y += $(CAMERA_SOC_CHIP_NAME)/
endif

ifeq ($(CONFIG_CAMERA_ISPV220), y)
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform/$(CAMERA_SOC_CHIP_NAME)
obj-y += $(CAMERA_SOC_CHIP_NAME)/
endif

ifeq ($(CONFIG_CAMERA_ISPV230), y)
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform/$(CAMERA_SOC_CHIP_NAME)
obj-y += $(CAMERA_SOC_CHIP_NAME)/
endif
