#
#QIC Makefile
#

obj-$(CONFIG_DFX_SEC_QIC) += dfx_sec_qic.o                               \
                             dfx_sec_qic_dump.o


obj-$(CONFIG_DFX_SEC_QIC_V100) += qic_v100/dfx_sec_qic_init.o             \
                                  qic_v100/dfx_sec_qic_err_probe.o

obj-$(CONFIG_DFX_SEC_QIC_V300) += qic_v300/dfx_sec_qic_init.o             \
                                  qic_v300/dfx_sec_qic_err_probe.o

obj-$(CONFIG_DFX_SEC_QIC_V100_MODID_REGISTER) += qic_v100/dfx_sec_qic_modid_register.o
obj-$(CONFIG_DFX_SEC_QIC_V300_MODID_REGISTER) += qic_v300/dfx_sec_qic_modid_register.o
