obj-y                   := sysview.o sysview_hids.o sysview_mprobe.o sysview_comm.o sysview_msg.o

GCOV_PROFILE := y
GCOV_PROFILE_sysview_mprobe.o := n
GCOV_PROFILE_sysview.o := n
GCOV_PROFILE_sysview_comm.o := n
GCOV_PROFILE_sysview_msg.o := n
GCOV_PROFILE_sysview_hids.o := n