ccflags-y += -I$(srctree)/drivers/platform_drivers/tzdriver

obj-$(CONFIG_DFX_DEBUG_FS)	+= load_demo_ca.o
obj-$(CONFIG_DFX_DEBUG_FS)	+= load_demo_test.o

ccflags-y += -Wdate-time -Wextra -Wfloat-equal -Wformat=2 -Wshadow
