# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_CPS2023) += cps2023.o
obj-$(CONFIG_CPS2023) += cps2023_i2c.o
obj-$(CONFIG_CPS2023) += cps2023_scp.o
obj-$(CONFIG_CPS2023) += cps2023_ufcs.o
obj-$(CONFIG_CPS2023) += cps2023_ovp_switch.o
