obj-y					:= coresight_funnel.o coresight_replicator.o coresight_tmc.o coresight_trace_mgr.o coresight_mprobe.o

GCOV_PROFILE := y
GCOV_PROFILE_coresight_tmc.o := n
GCOV_PROFILE_coresight_trace_mgr.o := n
GCOV_PROFILE_coresight_mprobe.o := n
GCOV_PROFILE_coresight_funnel.o := n
GCOV_PROFILE_coresight_replicator.o := n