
CFG_FEATURE_ON := 1

CFG_FEATURE_OFF := 0

CFG_ENABLE_BUILD_VARS := YES

CFG_BSP_CONFIG_PHONE_TYPE := YES

CFG_CONFIG_VERSION_STUB := NO

CFG_HW_VERSION_STUB := 0x2DF5FC15

CFG_BOARD_VERSION_STUB := 0x0

CFG_CONFIG_NVIM := YES

CFG_CONFIG_NV_FUSION_MSG := YES

CFG_FEATURE_NVA_ON := YES

CFG_FEATURE_NV_FLASH_ON := NO

CFG_FEATURE_NV_EMMC_ON := YES

CFG_FEATURE_NV_LFILE_ON := NO

CFG_FEATURE_NV_RFILE_ON := NO

CFG_FEATURE_DIS_HMAC_CHECK := NO

CFG_ENABLE_BUILD_SOCP := YES

CFG_CONFIG_DEFLATE := NO

CFG_SOCP_V300 := YES

CFG_CONFIG_BBPDS := YES

CFG_ENABLE_BUILD_PRINT := YES

CFG_FEATURE_HDS_PRINTLOG := FEATURE_OFF

CFG_FEATURE_HDS_TRANSLOG := FEATURE_OFF

CFG_CONFIG_DIAG_SYSTEM := YES

CFG_DIAG_SYSTEM_5G := YES

CFG_DIAG_SYSTEM_FUSION := YES

CFG_CONFIG_DIAG_NETLINK := YES

CFG_CONFIG_DIAG_APCNFCH_SIZE := 262144

CFG_CONFIG_DIAG_APLOGCH_SIZE := 524288

CFG_CONFIG_DIAG_CNFDSTCH_THRESHOLD := 256

CFG_CONFIG_DIAG_CNFDSTCH_SIZE := 524288

CFG_CONFIG_DIAG_LOGDSTCH_THRESHOLD := 65536

CFG_CONFIG_DIAG_LOGDSTCH_SIZE := 1048576

CFG_CONFIG_DIAG_DSTCH_FREEBUF_THRD := 4232

CFG_CONFIG_CHR_FS := YES

CFG_CONFIG_MODEM_CORESIGHT := NO

CFG_ENABLE_BUILD_OM := YES

CFG_CONFIG_MODEM_MINI_DUMP := YES

CFG_CONFIG_MODEM_FULL_DUMP := NO

CFG_ENABLE_BUILD_DUMP_MDM_LPM3 := YES

CFG_CONFIG_DUMP_PLATFORM_V200 := YES

CFG_CONFIG_TRNG_SEED := YES

CFG_CONFIG_VRL_SIZE := 8192

CFG_CONFIG_MLOADER := YES

CFG_CONFIG_LOAD_SEC_IMAGE := YES

CFG_CONFIG_MODEM_SECBOOT_CLEAN_DDR_USER := YES

CFG_CONFIG_DFXCERT_VERIFY := YES

CFG_CONFIG_MLOADER_COLD_PATCH := YES

CFG_CONFIG_COMPRESS_CCORE_IMAGE := YES

CFG_CONFIG_KERNEL_DTS_DECOUPLED := YES

CFG_CONFIG_MODEM_DTB_LOAD_IN_KERNEL := YES

CFG_CONFIG_PHONE_VERSION_DIFF_SOC_LEVEL := YES

CFG_CONFIG_ENABLE_DTO := YES

CFG_CONFIG_MODEM_PINCTRL := YES

CFG_CONFIG_EFUSE := YES

CFG_CONFIG_RFILE_ON := YES

CFG_MODEM_FW_PARTITION_SIZE := 123731968

CFG_MODEM_NV_UPDATE_PARTITION_SIZE := 16777216

CFG_MODEM_NV_CUST_PARTITION_SIZE := 16777216

CFG_CONFIG_NV_FUSION := YES

CFG_CONFIG_MODULE_TIMER := YES

CFG_CONFIG_MODEM_TIMER := YES

CFG_CONFIG_NMI := YES

CFG_CONFIG_MALLOC_UNIFIED := YES

CFG_CONFIG_SHARED_MEMORY := YES

CFG_CONFIG_SYSBOOT_PARA := YES

CFG_CONFIG_MEMORY_LAYOUT := YES

CFG_CONFIG_SYSBUS := NO

CFG_CONFIG_WAN := YES

CFG_CONFIG_PFA := YES

CFG_CONFIG_PFA_PHONE_SOC := YES

CFG_CONFIG_DRV_LTEV := YES

CFG_CONFIG_DRA := YES

CFG_CONFIG_DRA_V3 := YES

CFG_FEATURE_HISOCKET := FEATURE_OFF

CFG_CONFIG_NET_OM := NO

CFG_CONFIG_BTEST_PHONE := YES

CFG_CONFIG_VDEV := YES

CFG_CONFIG_VDEV_PHONE := YES

CFG_CONFIG_VDEV_BRIDGE := NO

CFG_CONFIG_VDEV_DEBUG := NO

CFG_CONFIG_MCI_CUST_CHN := NO

CFG_CONFIG_MCI_ATP := NO

CFG_CONFIG_MCI_SOCKET := NO

CFG_CONFIG_USB_RELAY := YES

CFG_CONFIG_RELAY_USB_BUFF_NUM := 128

CFG_CONFIG_UART_RELAY := NO

CFG_ENABLE_TEST_CODE := NO

CFG_CONFIG_FIPC_V200 := YES

CFG_CONFIG_FIPC_SUPPORT_HIFI_RESET := YES

CFG_CONFIG_MODEM_MSG := YES

CFG_CONFIG_MODULE_IPC_FUSION := NO

CFG_CONFIG_MODULE_IPCMSG := YES

CFG_MDRV_TEST := NO

CFG_CONFIG_SYSCTRL := YES

CFG_CONFIG_LLT_MDRV := NO

CFG_CONFIG_ECDC := NO

CFG_CONFIG_MODEM_RESET := YES

CFG_CONFIG_MPROBE := NO

CFG_CONFIG_AP_QIC := YES

CFG_CONFIG_CSHELL := NO

CFG_MEM_LAYOUT_TYPE := 0
