set(CFG_FEATURE_ON 1)

set(CFG_FEATURE_OFF 0)

set(CFG_ENABLE_BUILD_VARS YES)

set(CFG_BSP_CONFIG_PHONE_TYPE YES)

set(CFG_CONFIG_VERSION_STUB NO)

set(CFG_HW_VERSION_STUB 0x2DF5FC15)

set(CFG_BOARD_VERSION_STUB 0x0)

set(CFG_CONFIG_NVIM YES)

set(CFG_CONFIG_NV_FUSION_MSG YES)

set(CFG_FEATURE_NVA_ON YES)

set(CFG_FEATURE_NV_FLASH_ON NO)

set(CFG_FEATURE_NV_EMMC_ON YES)

set(CFG_FEATURE_NV_LFILE_ON NO)

set(CFG_FEATURE_NV_RFILE_ON NO)

set(CFG_FEATURE_DIS_HMAC_CHECK NO)

set(CFG_ENABLE_BUILD_SOCP YES)

set(CFG_CONFIG_DEFLATE NO)

set(CFG_SOCP_V300 YES)

set(CFG_CONFIG_BBPDS YES)

set(CFG_ENABLE_BUILD_PRINT YES)

set(CFG_FEATURE_HDS_PRINTLOG FEATURE_OFF)

set(CFG_FEATURE_HDS_TRANSLOG FEATURE_OFF)

set(CFG_CONFIG_DIAG_SYSTEM YES)

set(CFG_DIAG_SYSTEM_5G YES)

set(CFG_DIAG_SYSTEM_FUSION YES)

set(CFG_CONFIG_DIAG_NETLINK YES)

set(CFG_CONFIG_DIAG_APCNFCH_SIZE 262144)

set(CFG_CONFIG_DIAG_APLOGCH_SIZE 524288)

set(CFG_CONFIG_DIAG_CNFDSTCH_THRESHOLD 256)

set(CFG_CONFIG_DIAG_CNFDSTCH_SIZE 524288)

set(CFG_CONFIG_DIAG_LOGDSTCH_THRESHOLD 65536)

set(CFG_CONFIG_DIAG_LOGDSTCH_SIZE 1048576)

set(CFG_CONFIG_DIAG_DSTCH_FREEBUF_THRD 4232)

set(CFG_CONFIG_CHR_FS YES)

set(CFG_CONFIG_MODEM_CORESIGHT NO)

set(CFG_ENABLE_BUILD_OM YES)

set(CFG_CONFIG_MODEM_MINI_DUMP YES)

set(CFG_CONFIG_MODEM_FULL_DUMP NO)

set(CFG_ENABLE_BUILD_DUMP_MDM_LPM3 YES)

set(CFG_CONFIG_DUMP_PLATFORM_V200 YES)

set(CFG_CONFIG_TRNG_SEED YES)

set(CFG_CONFIG_VRL_SIZE 8192)

set(CFG_CONFIG_MLOADER YES)

set(CFG_CONFIG_LOAD_SEC_IMAGE YES)

set(CFG_CONFIG_MODEM_SECBOOT_CLEAN_DDR_USER YES)

set(CFG_CONFIG_DFXCERT_VERIFY YES)

set(CFG_CONFIG_MLOADER_COLD_PATCH YES)

set(CFG_CONFIG_COMPRESS_CCORE_IMAGE YES)

set(CFG_CONFIG_KERNEL_DTS_DECOUPLED YES)

set(CFG_CONFIG_MODEM_DTB_LOAD_IN_KERNEL YES)

set(CFG_CONFIG_PHONE_VERSION_DIFF_SOC_LEVEL YES)

set(CFG_CONFIG_ENABLE_DTO YES)

set(CFG_CONFIG_MODEM_PINCTRL YES)

set(CFG_CONFIG_EFUSE YES)

set(CFG_CONFIG_RFILE_ON YES)

set(CFG_MODEM_FW_PARTITION_SIZE 123731968)

set(CFG_MODEM_NV_UPDATE_PARTITION_SIZE 16777216)

set(CFG_MODEM_NV_CUST_PARTITION_SIZE 16777216)

set(CFG_CONFIG_NV_FUSION YES)

set(CFG_CONFIG_MODULE_TIMER YES)

set(CFG_CONFIG_MODEM_TIMER YES)

set(CFG_CONFIG_NMI YES)

set(CFG_CONFIG_MALLOC_UNIFIED YES)

set(CFG_CONFIG_SHARED_MEMORY YES)

set(CFG_CONFIG_SYSBOOT_PARA YES)

set(CFG_CONFIG_MEMORY_LAYOUT YES)

set(CFG_CONFIG_SYSBUS NO)

set(CFG_CONFIG_WAN YES)

set(CFG_CONFIG_PFA YES)

set(CFG_CONFIG_PFA_PHONE_SOC YES)

set(CFG_CONFIG_DRV_LTEV YES)

set(CFG_CONFIG_DRA YES)

set(CFG_CONFIG_DRA_V3 YES)

set(CFG_FEATURE_HISOCKET FEATURE_OFF)

set(CFG_CONFIG_NET_OM NO)

set(CFG_CONFIG_BTEST_PHONE YES)

set(CFG_CONFIG_VDEV YES)

set(CFG_CONFIG_VDEV_PHONE YES)

set(CFG_CONFIG_VDEV_BRIDGE NO)

set(CFG_CONFIG_VDEV_DEBUG NO)

set(CFG_CONFIG_MCI_CUST_CHN NO)

set(CFG_CONFIG_MCI_ATP NO)

set(CFG_CONFIG_MCI_SOCKET NO)

set(CFG_CONFIG_USB_RELAY YES)

set(CFG_CONFIG_RELAY_USB_BUFF_NUM 128)

set(CFG_CONFIG_UART_RELAY NO)

set(CFG_ENABLE_TEST_CODE NO)

set(CFG_CONFIG_FIPC_V200 YES)

set(CFG_CONFIG_FIPC_SUPPORT_HIFI_RESET YES)

set(CFG_CONFIG_MODEM_MSG YES)

set(CFG_CONFIG_MODULE_IPC_FUSION NO)

set(CFG_CONFIG_MODULE_IPCMSG YES)

set(CFG_MDRV_TEST NO)

set(CFG_CONFIG_SYSCTRL YES)

set(CFG_CONFIG_LLT_MDRV NO)

set(CFG_CONFIG_ECDC NO)

set(CFG_CONFIG_MODEM_RESET YES)

set(CFG_CONFIG_MPROBE NO)

set(CFG_CONFIG_AP_QIC YES)

set(CFG_CONFIG_CSHELL NO)

set(CFG_MEM_LAYOUT_TYPE 0)

