ifeq ($(CONFIG_TZDRIVER),y)

obj-$(CONFIG_TZDRIVER_INTERNAL) += tzdriver_internal/
obj-$(CONFIG_TZDRIVER) += agent_rpmb/
obj-$(CONFIG_TZDRIVER) += auth/
obj-$(CONFIG_TZDRIVER) += core/
obj-$(CONFIG_TZDRIVER) += tlogger/
obj-$(CONFIG_TZDRIVER) += ion/
obj-$(CONFIG_TZDRIVER) += tui/
obj-$(CONFIG_TZDRIVER) += whitelist/

endif
