NPU_ARCH_VERSION=npu_v210
CONFIG_NPU_PM_FUSION=y
CONFIG_NPU_AUTOFS=y
CONFIG_NPU_SDMA=n
CONFIG_NPU_SYSCACHE=y
CONFIG_NPU_DIRECT=y
NPU_CHIP_TYPE :=$(strip $(subst ", ,$(CONFIG_VENDOR_CHIP_SUFFIX)))
ifeq ($(NPU_CHIP_TYPE), es)
    NPU_GLOBAL_CFLAGS += -DCONFIG_NPU_SDMA
endif

export NPU_ARCH_VERSION CONFIG_NPU_PM_FUSION CONFIG_NPU_AUTOFS CONFIG_NPU_SDMA CONFIG_NPU_DIRECT
export CONFIG_NPU_SYSCACHE

NPU_GLOBAL_CFLAGS += -DCONFIG_NPU_AUTOFS
NPU_GLOBAL_CFLAGS += -DCONFIG_NPU_SYSCACHE
NPU_GLOBAL_CFLAGS += -DCONFIG_NPU_SUPPORT_AIV
NPU_GLOBAL_CFLAGS += -DCONFIG_NPU_DIRECT

