NPU_ARCH_VERSION=npu_v100

export NPU_ARCH_VERSION

NPU_GLOBAL_CFLAGS += -DCONFIG_NPU_NOC

NPU_CHIP_PLATFORM :=$(strip $(subst ", ,$(CONFIG_VENDOR_CHIP_PREFIX)))
NPU_CHIP_TYPE :=$(strip $(subst ", ,$(CONFIG_VENDOR_CHIP_SUFFIX)))
ifneq ($(NPU_CHIP_TYPE),)
	NPU_CHIP_VERSION=$(NPU_CHIP_PLATFORM)_$(NPU_CHIP_TYPE)
	NPU_CHIP_CFG=y
	export NPU_CHIP_CFG
endif

