ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/sensor

subdir-ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/idi2axi_sensor
subdir-ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/idi2axi_sensor/include
subdir-ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/idi2axi_sensor/platform
subdir-ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/idi2axi
subdir-ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/idi2axi/include
subdir-ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform
subdir-ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/sensor
subdir-ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera

obj-y += i2a_sensor_kit.o
obj-y += i2a_i2c.o
obj-y += i2a_hwsensor.o

obj-$(CONFIG_IDI2AXI_V100) += platform/v100/

