#
# echub power moudule
#

obj-$(CONFIG_ARMPC_ECHUB_PMSYNC) += ec_state_sync.o
obj-$(CONFIG_ARMPC_ECHUB_PMSYNC) += ec_regulator.o
obj-$(CONFIG_ARMPC_ECHUB_LID) += echub_lid.o
obj-$(CONFIG_ARMPC_ECHUB_CHARGE_STATUS) += echub_charge_status.o
obj-$(CONFIG_ARMPC_ECHUB_WAKEALARM) += echub_wakealarm.o
