ccflags-$(CONFIG_DDR_CRATER) += -I$(srctree)/platform_source/cee/drivers/ddrc/ddrcflux/crater
ccflags-$(CONFIG_DDR_NORTHERNCROSS) += -I$(srctree)/platform_source/cee/drivers/ddrc/ddrcflux/northerncross
obj-$(CONFIG_DDR_DDRC_FLUX_SOFTTIMER) += ddr_ddrcflux_drv.o
