# SPDX-License-Identifier: GPL-2.0
# obj-$(CONFIG_HW_IC_HC32L110) += mcu_hc32l110/

obj-$(CONFIG_HW_MCU_DRIVER) += mcu_hc32l110.o
obj-$(CONFIG_HW_MCU_DRIVER) += mcu_hc32l110_i2c.o
obj-$(CONFIG_HW_MCU_DRIVER) += mcu_hc32l110_fw.o
