#
# Makefile for kernel vendor pcie.
#

obj-$(CONFIG_HIPCIE_CTRL) += hi_pcie_ctrl.o
obj-$(CONFIG_HIPCIE_CTRL) += hi_pcie_ctrl_common.o
obj-$(CONFIG_HIPCIE_CTRL) += hi_pcie_ctrl_int.o
obj-$(CONFIG_HIPCIE_CTRL) += hi_pcie_ctrl_dfx.o
obj-$(CONFIG_HIPCIE_CTRL_RC) += hi_pcie_ctrl_rc.o
obj-$(CONFIG_HIPCIE_CTRL_EP) += hi_pcie_ctrl_ep.o
obj-$(CONFIG_HIPCIE_CTRL_DMA) += hi_pcie_ctrl_dma.o