#ifndef __DDR_PERF_SCENE_H__
#define __DDR_PERF_SCENE_H__ 
enum perf_scene_case_id {
 PERF_SCENE_CASEI = 0,
 PERF_SCENE_CASEII,
 PERF_SCENE_CASEIII,
 PERF_SCENE_CASEIV,
 PERF_SCENE_CASEV,
 PERF_SCENE_CASEVI,
 PERF_SCENE_CASE_MAX
};
#endif
