obj-y += scharger_v800_watchdog.o
obj-y += scharger_v800_buck.o
obj-y += scharger_v800_dc.o
obj-y += scharger_v800_adc.o
obj-y += scharger_v800_irq.o
obj-y += scharger_v800_waterdet.o
obj-y += scharger_v800_log.o
