/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2022-2022. All rights reserved.
 * Description: commu_svc_base.h
 * Create: 2022-10-21
 */

#ifndef __SVC_ID_H__
#define __SVC_ID_H__

#include "sh_typedef.h"

/**
 * @brief service id.
 *
 */
enum service_id {
	SERVICE_ID_MGR = 0,
	SERVICE_ID_COMMU,
	SERVICE_ID_SM,          // sensor manager.
	SERVICE_ID_DM,          // data manager.
	SERVICE_ID_HCS,
	SERVICE_ID_CTCC,
	SERVICE_ID_DYNLOAD,
	SERVICE_ID_PM_QOS,
	SERVICE_ID_AMSM,
	SERVICE_ID_SENSOR_DBG_SVC,
	SERVICE_ID_DEMO,

	PCST_SAMGR_COMM_TEST_DEMO_ID,
	PCST_HCS_TEST_DEMO_ID,
	DEMO_SM_PRESSURE_ID,
	DEMO_SM_PRESSURE1_ID,
	DEMO_SM_PRESSURE2_ID,
	DEMO_SM_PRESSURE3_ID,
	DEMO_SM_PRESSURE4_ID,
	DEMO_SM_PRESSURE5_ID,
	DEMO_SM_PRESSURE6_ID,
	DEMO_SM_PRESSURE7_ID,
	DEMO_SM_PRESSURE8_ID,
	DEMO_SM_PRESSURE9_ID,
	DEMO_SM_PRESSURE10_ID,
	DEMO_SM_PRESSURE11_ID,
	DEMO_SM_PRESSURE12_ID,
	DEMO_SM_PRESSURE13_ID,
	DEMO_SM_PRESSURE14_ID,
	DEMO_SM_PRESSURE15_ID,
	DEMO_SM_REQUESTER_ID,
	DEMO_SM_PCST_ID,
	DEMO_SM_ID_MAX,

	SERVICE_ID_MAX,
};

#endif
