
ccflags-y  += -I$(srctree)/platform_source/smart/drivers
subdir-ccflags-y += -I$(srctree)/platform_source/smart/drivers
obj-$(CONFIG_CONTEXTHUB)   += bsp/
obj-y   += channels/
obj-$(CONFIG_BSP_SYSCOUNTER) += syscounter/