set(CFG_FEATURE_ON 1)

set(CFG_FEATURE_OFF 0)

set(CFG_CONFIG_PS_AP_ENG NO)

set(CFG_CONFIG_RNIC YES)

set(CFG_CONFIG_RNIC_CUST_NAME NO)

set(CFG_CONFIG_RNIC_LAN_FORWARD NO)

set(CFG_CONFIG_RNIC_SRS YES)

set(CFG_CONFIG_RNIC_GRO YES)

set(CFG_CONFIG_RNIC_IMS YES)

set(CFG_CONFIG_RNIC_TUN YES)

set(CFG_CONFIG_RNIC_LTEV YES)

set(CFG_CONFIG_IPS YES)

set(CFG_CONFIG_IPS_NFEXT YES)

set(CFG_CONFIG_RNIC_PKTCAP NO)

set(CFG_CONFIG_RNIC_DPL YES)

set(CFG_CONFIG_RNIC_DPL_LATENCY NO)

set(CFG_CONFIG_RNIC_D2D YES)

set(CFG_CONFIG_RNIC_MULTI_IF NO)

set(CFG_CONFIG_RNIC_PFA_V2 NO)

set(CFG_CONFIG_RNIC_WAKEUP NO)

set(CFG_CONFIG_RNIC_PRIORITY_MAP NO)

set(CFG_CONFIG_RNIC_FORWARD_MODE NO)

set(CFG_CONFIG_PCS YES)

set(CFG_CONFIG_PCS_BC_CAP_DIR YES)

set(CFG_FEATURE_BASTET YES)

set(CFG_CONFIG_RNIC_DUMP YES)

