
CFG_FEATURE_ON := 1

CFG_FEATURE_OFF := 0

CFG_CONFIG_PS_AP_ENG := NO

CFG_CONFIG_RNIC := YES

CFG_CONFIG_RNIC_CUST_NAME := NO

CFG_CONFIG_RNIC_LAN_FORWARD := NO

CFG_CONFIG_RNIC_SRS := YES

CFG_CONFIG_RNIC_GRO := YES

CFG_CONFIG_RNIC_IMS := YES

CFG_CONFIG_RNIC_TUN := YES

CFG_CONFIG_RNIC_LTEV := YES

CFG_CONFIG_IPS := YES

CFG_CONFIG_IPS_NFEXT := YES

CFG_CONFIG_RNIC_PKTCAP := NO

CFG_CONFIG_RNIC_DPL := YES

CFG_CONFIG_RNIC_DPL_LATENCY := NO

CFG_CONFIG_RNIC_D2D := YES

CFG_CONFIG_RNIC_MULTI_IF := NO

CFG_CONFIG_RNIC_PFA_V2 := NO

CFG_CONFIG_RNIC_WAKEUP := NO

CFG_CONFIG_RNIC_PRIORITY_MAP := NO

CFG_CONFIG_RNIC_FORWARD_MODE := NO

CFG_CONFIG_PCS := YES

CFG_CONFIG_PCS_BC_CAP_DIR := YES

CFG_FEATURE_BASTET := YES

CFG_CONFIG_RNIC_DUMP := YES
