EXTRA_CFLAGS += -I$(srctree)/platform_source/camera/drivers/media/native/camera/
EXTRA_CFLAGS += -I$(srctree)/platform_source/camera/drivers/media/native/camera/cam_star_module/
EXTRA_CFLAGS += -I$(srctree)/platform_source/camera/drivers/media/native/camera/cam_star_module/hc32l110/
EXTRA_CFLAGS += -fno-pic

obj-$(CONFIG_KERNEL_CAMERA_SENSORMOTOR) += hc32l110.o
obj-$(CONFIG_KERNEL_CAMERA_SENSORMOTOR) += hc32l110_fw.o
obj-$(CONFIG_KERNEL_CAMERA_SENSORMOTOR) += hc32l110_state_machine.o
