# If you want to compile into modular drive, will need to decide
# according to the following configuration to compile.
# If the CONFIG_UKMD_ENABLE is not defined, display module isn't compiled.

ifeq ($(CONFIG_UKMD_ENABLE),y)

obj-y += cmdlist/
obj-y += uksm/

ifeq ($(CONFIG_MDFX_KMD),y)
obj-y += mntn/
endif

endif
