# SPDX-License-Identifier: GPL-2.0
#
# huawei battery balance driver
#

obj-$(CONFIG_HUAWEI_BATTERY_CHARGE_BALANCE) += battery_charge_balance.o
obj-$(CONFIG_HUAWEI_BATTERY_CHARGE_BALANCE) += battery_charge_balance_parallel.o
obj-$(CONFIG_HUAWEI_BATTERY_CHARGE_BALANCE) += battery_charge_balance_serial.o
