ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera
ccflags-y += -I$(srctree)/drivers/platform_drivers/ap/platform/common

obj-y += v100_idi2axi.o plat_csi2if.o plat_idi2axi.o
