obj-$(CONFIG_HW_RSMC) += rsmc_driver.o
rsmc_driver-y :=
rsmc_driver-y += rsmc_chiptype_select.o
rsmc_driver-$(CONFIG_HW_RSMC_X801) += x801/rsmc_start_x801.o
rsmc_driver-$(CONFIG_HW_RSMC_X801) += x801/rsmc_msg_loop_x801.o
rsmc_driver-$(CONFIG_HW_RSMC_X801) += x801/rsmc_spi_x801.o
rsmc_driver-$(CONFIG_HW_RSMC_X801) += x801/rsmc_device_x801.o

rsmc_driver-$(CONFIG_HW_RSMC_X800) += x800/rsmc_start_x800.o
rsmc_driver-$(CONFIG_HW_RSMC_X800) += x800/rsmc_msg_loop.o
rsmc_driver-$(CONFIG_HW_RSMC_X800) += x800/rsmc_spi_drv.o
rsmc_driver-$(CONFIG_HW_RSMC_X800) += x800/rsmc_x800_device.o
rsmc_driver-$(CONFIG_HW_RSMC_X800) += x800/rsmc_rx_ctrl.o
rsmc_driver-$(CONFIG_HW_RSMC_X800) += x800/rsmc_tx_ctrl.o
rsmc_driver-$(CONFIG_HW_RSMC_X800) += x800/rsmc_spi_ctrl.o
rsmc_driver-$(CONFIG_HW_RSMC_X800) += x800/rsmc_test.o
rsmc_driver-$(CONFIG_HW_RSMC_X800) += x800/track.o
