#
# Makefile for PERF.
#

obj-$(CONFIG_HUAWEI_PERF) += \
	perf.o \
	perf_process_cputime_stats.o \
	perf_thread_status_stats.o \
	perf_system_info.o \
	perf_system_memory_info.o \
	perf_proc_memory_info.o \
	perf_lpm_limit_freq.o \
	utils/perf_buffered_log_sender.o\
	utils/perf_utils.o
