ifneq ($(filter y,$(CONFIG_DA_COMBINE_V3_CODEC) $(CONFIG_SND_SOC_DA_COMBINE_V5)),)
endif
obj-$(CONFIG_HIFI_DSP_ONE_TRACK) += hifi_dsp/
obj-$(CONFIG_SOUND_TRIGGER) += soundtrigger/
obj-$(CONFIG_HIFI_MAILBOX) += hifi_mailbox/
ifneq ($(filter y,$(CONFIG_CODEC_DSP_MISC) $(CONFIG_HIFI_BB)),)
endif
obj-$(CONFIG_SOC_MAD) += soc_mad/
obj-$(CONFIG_HIFI_BB) += rdr/
