#ifndef __H_PM_COMMON_H__
#define __H_PM_COMMON_H__ 
#define AP_MASK BIT(0)
#define MODEM_MASK BIT(1)
#define HIFI_MASK BIT(2)
#define IOMCU_MASK BIT(3)
#define LPMCU_MASK BIT(4)
#define GENERAL_SEE_MASK BIT(5)
#define CODEC_MASK BIT(6)
#define ASP_MASK BIT(7)
#define MODEM_NR_MASK BIT(8)
#define GPU_MASK BIT(9)
#define SC_LP_FLAG_ULSR_BIT 15
#define SC_LP_FLAG_ULSR_MASK 0x00008000
#define SR_TRACE_REG(base) SOC_SCTRL_SCPERSTAT_POR_RESERVED0_ADDR(base)
#endif
