# SPDX-License-Identifier: GPL-2.0
obj-y += ground_loop_compensate/
obj-$(CONFIG_AFE_FUEL_GAUGE) += afe_coul/
obj-$(CONFIG_BQ27Z561_FUEL_GAUGE) += bq27z561/
obj-$(CONFIG_RT9426_FUEL_GAUGE) += rt9426/
obj-$(CONFIG_BQ40Z50_FUEL_GAUGE) += bq40z50/
obj-$(CONFIG_BQ40Z50_FUEL_GAUGE) += cbm8580/
obj-$(CONFIG_CW2217_FUEL_GAUGE) += cw2217/