# Hisilicon IPP segment Makefile

obj-$(CONFIG_HISPIPP_V500) += segment_enh_arfeature.o
obj-$(CONFIG_HISPIPP_V500) += segment_common.o
obj-$(CONFIG_HISPIPP_V500) += segment_ipp_adapter.o
obj-$(CONFIG_HISPIPP_V500) += segment_ipp_adapter_sub.o
obj-$(CONFIG_HISPIPP_V500) += segment_ipp_path.o
obj-$(CONFIG_HISPIPP_V500) += segment_matcher.o
obj-$(CONFIG_HISPIPP_V500) += segment_mc.o
obj-$(CONFIG_HISPIPP_V500) += segment_klt.o

