/**
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 */

#ifndef DKMD_ISR_H
#define DKMD_ISR_H

#include "ukmd_isr.h"

enum {
	DSI_INT_FRM_START = BIT(0),
	DSI_INT_FRM_END = BIT(1),
	DSI_INT_UNDER_FLOW = BIT(2),
	DSI_INT_VFP_END = BIT(3),
	DSI_INT_VSYNC = BIT(4),
	DSI_INT_VBP = BIT(5),
	DSI_INT_VFP = BIT(6),
	DSI_INT_VACT0_START = BIT(7),
	DSI_INT_VACT0_END = BIT(8),
	DSI_INT_VACT1_START = BIT(9),
	DSI_INT_VACT1_END = BIT(10),
	DSI_INT_LCD_TE1 = BIT(11),
	DSI_INT_LCD_TE0 = BIT(12),
	DSI_INT_VACT_TIME_ABNORMAL = BIT(24),
	DSI_INT_DATA_CONTINUE_INTERRUPT = BIT(25),

	DSI_EDP_IRQ_HPD = BIT(30),
	/* in acpu dfr mode, report vsync by te isr */
	DSI_INT_VSYNC_COUNT_BY_TE = BIT(31),
};

enum {
	DPU_LBUF_CMN_NS_INT = BIT(30),
	DPU_DDIC0_DLBCD_NS_INT = BIT(20),
	DPU_WBUF_NS_INT = BIT(19),
	DPU_HDR_NS_INT = BIT(18),
	DPU_CMD_NS_INT = BIT(16),
	DPU_DBCU_TBU_RT_NS_INT = BIT(15),
	DPU_DBCU_TBU_SRT_NS_INT = BIT(14),
	DPU_LBUF_CTL_NS_INT = BIT(13),
	DPU_SMART_DMA0_NS_INT = BIT(12),
	DPU_SMART_DMA1_NS_INT = BIT(11),
	DPU_SMART_DMA2_NS_INT = BIT(10),
	DPU_SMART_DMA3_NS_INT = BIT(9),
	DPU_WCH0_NS_INT = BIT(8),
	DPU_WCH1_NS_INT = BIT(7),
	DPU_WCH2_NS_INT = BIT(6),
	DPU_DACC_NS_INT = BIT(5),
	DPU_DPP0_HIACE_NS_INT = BIT(4),
	DPU_HEMCD0_NS_INT = BIT(3),
	DPU_WCH3_NS_INT = BIT(3),
	DPU_DDE_NS_INT = BIT(2), // ffd le isr on 740
	DPU_DPP1_HIACE_NS_INT = BIT(1),
	DPU_HEMCD1_NS_INT = BIT(0),
};

enum {
	DPU_DACC_NS_SCENE0 = BIT(0),
	DPU_DACC_NS_SCENE1 = BIT(1),
	DPU_DACC_NS_SCENE2 = BIT(2),
	DPU_DACC_NS_SCENE3 = BIT(3),
	DPU_DACC_NS_SCENE4 = BIT(4),
	DPU_DACC_NS_SCENE5 = BIT(5),
	DPU_DACC_NS_SCENE6 = BIT(6),
	DPU_DACC_NS_SCENE7 = BIT(7),
};

enum {
	DEFAULT_TE = BIT(0),
	VALID_VSYNC = BIT(1),
	NORMAL_TE = BIT(2),
	COUNT_VSYNC = BIT(3),
	SELF_REFRESH = BIT(4),
	DIMMING_DONE = BIT(5),
	MISMATCH_TE = BIT(6),
	LTM_IHIST_DONE = BIT(9),
	ISR_PPC_DONE = BIT(10), // ppc done
	ASYNC_TX_DONE = BIT(13),
	DPU_DACC_LOG_BUF_FULL = BIT(14),
};

enum {
	DPU_FFD_LE_NS_DPP_LE = BIT(0), // le isr after dpp
	DPU_FFD_LE_NS_PRE_LE = BIT(1), // le isr pre ov
	DPU_FFD_LE_NS_FFD_INT = BIT(3), // ffd isr
};

enum {
	NOTIFY_VSYNC = BIT(0),
	NOTIFY_TIMELINE = BIT(1),
	NOTIFY_BOTH_VSYNC_TIMELINE = BIT(2),
	NOTIFY_DIMMING_DONE = BIT(3),
	NOTIFY_DCS_SEND = BIT(4),
	NOTIFY_REFRESH = BIT(5),
	NOTIFY_PPC_DONE = BIT(6), // PPC stand for panel partial control
	NOTIFY_TUNNEL_VSYNC = BIT(7),
};

// only used in v700
enum {
	DPU_DACC_SECONDARY_ISR_VALID_VSYNC,
	DPU_DACC_SECONDARY_ISR_COUNT_VSYNC,
	DPU_DACC_SECONDARY_ISR_SELF_REFRESH,
	DPU_DACC_SECONDARY_ISR_DIMMING_DONE,
	DPU_DACC_SECONDARY_ISR_DCS_SEND,
	DACC_SECONDARY_ISR_VSYNC_AND_SELF_REFRESH,
	DACC_SECONDARY_ISR_COUNT_VSYNC_AND_DIMMING_DONE,
	DACC_SECONDARY_ISR_ADJUST_VSYNC,
	DACC_SECONDARY_ISR_TE,
	DPU_DACC_SECONDARY_ISR_LTM_IHIST = 9,
	DPU_DACC_LOG_ISR_AP_READ = 14,
};

enum {
	DACC_SECONDARY_ISR_PPC_DONE = BIT(0), // only used in v700
};

enum {
	DDIC_DLBCD_INT = BIT(0),
	DDIC_IRC_INT = BIT(1),
};

enum {
	WCH_SDMA4_END_INTS = BIT(4),
	WCH3_FRM_END_INTS = BIT(7),
	WCH_WLT_END_INTS = BIT(8),
	WCH_WLT_ERR_INTS = BIT(9),
	WCH_BLK_END_INTS = BIT(10),
	WCH_FRM_END_INTS = BIT(11),
};

enum {
	HDR_LTM_HIST_STAT_END_INTS = BIT(0),
	HDR_GTM_HIST_STAT_END_INTS = BIT(1),
};

enum {
	DPU_M1_QIC_INTR_ERR_TB_DSS_CFG = BIT(28),
	DPU_M1_QIC_INTR_SAFETY_TB_DSS_CFG = BIT(27),
	DPU_M1_QIC_INTR_SAFETY_ERR_TB_DSS_CFG = BIT(26),
	DPU_M1_QIC_INTR_ERR_IB_DSS_RT0_DATA_RD = BIT(24),
	DPU_M1_QIC_INTR_SAFETY_IB_DSS_RT0_DATA_RD = BIT(23),
	DPU_M1_QIC_INTR_SAFETY_ERR_IB_DSS_RT0_DATA_RD = BIT(22),
	DPU_M1_QIC_INTR_ERR_IB_DSS_RT0_DATA_WR = BIT(20),
	DPU_M1_QIC_INTR_SAFETY_IB_DSS_RT0_DATA_WR = BIT(19),
	DPU_M1_QIC_INTR_SAFETY_ERR_IB_DSS_RT0_DATA_WR = BIT(18),
	DPU_M1_QIC_INTR_ERR_IB_DSS_RT1_DATA_RD = BIT(16),
	DPU_M1_QIC_INTR_SAFETY_IB_DSS_RT1_DATA_RD = BIT(15),
	DPU_M1_QIC_INTR_SAFETY_ERR_IB_DSS_RT1_DATA_RD = BIT(14),
	DPU_M1_QIC_INTR_ERR_IB_DSS_RT2_DATA_RD = BIT(12),
	DPU_M1_QIC_INTR_SAFETY_IB_DSS_RT2_DATA_RD = BIT(11),
	DPU_M1_QIC_INTR_SAFETY_ERR_IB_DSS_RT2_DATA_RD = BIT(10),
	DPU_M1_QIC_INTR_ERR_IB_DSS_RT2_DATA_WR = BIT(8),
	DPU_M1_QIC_INTR_SAFETY_IB_DSS_RT2_DATA_WR = BIT(7),
	DPU_M1_QIC_INTR_SAFETY_ERR_IB_DSS_RT2_DATA_WR = BIT(6),
	DPU_M1_QIC_INTR_ERR_IB_DSS_RT3_DATA_RD = BIT(4),
	DPU_M1_QIC_INTR_SAFETY_IB_DSS_RT3_DATA_RD = BIT(3),
	DPU_M1_QIC_INTR_SAFETY_ERR_IB_DSS_RT3_DATA_RD = BIT(2),
	DPU_M1_QIC_INTR_ERR_RT_0_RD_REQ = BIT(0),
};

enum {
	DPU_M1_QIC_INTR_ERR_RT_0_RD_RSP = BIT(22),
	DPU_M1_QIC_INTR_ERR_RT_0_REQ = BIT(18),
	DPU_M1_QIC_INTR_ERR_RT_0_RSP = BIT(14),
	DPU_M1_QIC_INTR_ERR_RT_QCP_DSS_CFG_REQ = BIT(10),
	DPU_M1_QIC_INTR_ERR_RT_QCP_DSS_CFG_RSP = BIT(6),
	DPU_M1_QIC_INTR_ERR_TB_QCP_DSS = BIT(2),
	DPU_M1_QIC_INTR_SAFETY_TB_QCP_DSS = BIT(1),
	DPU_M1_QIC_INTR_SAFETY_ERR_TB_QCP_DSS = BIT(0),
};
#endif