
EXTRA_CFLAGS += -I$(srctree)/platform_source/ffrt/hts/dfx
EXTRA_CFLAGS += -I$(srctree)/platform_source/ffrt/hts/hkd_chip_test
EXTRA_CFLAGS += -I$(srctree)/drivers/platform_drivers/ap/platform/$(FFTS_CHIP_PLATFORM_DIR)

obj-y += hkd.o

hkd-objs :=  hts_devinit.o hts_ioctl_services.o hts_proc_ctx.o hts_atf.o hts_irq.o hts_pm.o hts.o hts_hw_config.o