# Makefile for the spartlink.
#
# Each configuration option enables a list of files.

obj-$(CONFIG_HUAWEI_SPARKLINK)  += sparklink_core.o sparklink_i2c_ops.o
obj-$(CONFIG_HUAWEI_1162)  += hi116x_driver.o hi116x_fwupdate.o hi116x_wltx.o
obj-$(CONFIG_HUAWEI_SPARKLINK_UART)  += sparklink_uart.o