/*
 * Copyright (c) Hisilicon Technologies Co., Ltd. 2023-2023. All rights reserved.
 *
 * This program is free software and is provided to you under the terms of the
 * GNU General Public License version 2 as published by the Free Software
 * Foundation, and any use by you of this program is subject to the terms
 * of such GNU licence.
 */

#ifndef DATAN_JOBTRACE_TYPE_DEFS_H
#define DATAN_JOBTRACE_TYPE_DEFS_H

#include "linux/types.h"

#define SWTRACE_VERSION    3
#define STRLEN_MAX         64

#define PACKET_STREAMID_POS  0
#define PACKET_STREAMID_LEN  8
#define PACKET_STREAMID_MASK (((u32) 1<<PACKET_STREAMID_LEN) - 1)

#define PACKET_RSVD1_POS     (PACKET_STREAMID_POS + PACKET_STREAMID_LEN)
#define PACKET_RSVD1_LEN     8

#define PACKET_TYPE_POS      (PACKET_RSVD1_POS + PACKET_RSVD1_LEN)
#define PACKET_TYPE_LEN      3
#define PACKET_TYPE_MASK     (((u32) 1<<PACKET_TYPE_LEN) - 1)

#define PACKET_CLASS_POS     (PACKET_TYPE_POS + PACKET_TYPE_LEN)
#define PACKET_CLASS_LEN     7
#define PACKET_CLASS_MASK    (((u32) 1<<PACKET_CLASS_LEN) - 1)

#define PACKET_FAMILY_POS    (PACKET_CLASS_POS + PACKET_CLASS_LEN)
#define PACKET_FAMILY_LEN    6
#define PACKET_FAMILY_MASK   (((u32) 1<<PACKET_FAMILY_LEN) - 1)

#define PACKET_LENGTH_POS    0u
#define PACKET_LENGTH_LEN    24u
#define PACKET_LENGTH_MASK   (((u32) 1u<<PACKET_LENGTH_LEN) - 1u)
#define PACKET_SEQBIT_POS    (PACKET_LENGTH_POS + PACKET_LENGTH_LEN)
#define PACKET_SEQBIT_LEN    1u
#define PACKET_SEQBIT_MASK   (((u32) 1u<<PACKET_SEQBIT_LEN) - 1u)
#define PACKET_RSVD2_POS     (PACKET_SEQBIT_POS + PACKET_SEQBIT_LEN)
#define PACKET_RSVD2_LEN     7
#define PACKET_WORD1_POS     4 /* bytes */

#define PACKET_HEADER_SIZE   8 /* bytes */

#define PACKET_NUMBER_SIZE   4 /* bytes */

enum jobtrace_type {
	JOBTRACE_TYPE_OBJ_DECL,
	JOBTRACE_TYPE_OBJ_SUM,
	JOBTRACE_TYPE_OBJ,
	JOBTRACE_TYPE_AUX_DECL,
	JOBTRACE_TYPE_AUX,
	JOBTRACE_TYPE_LOCAL,

	JOBTRACE_TYPE_COUNT
};

enum jobtrace_obj_msg_id {
	KDATAN_TL_NEW_CTX,
	KDATAN_TL_RET_AS_CTX,
	KDATAN_TL_WRITE_REG,
	KDATAN_TL_ATTRIB_AS_CONFIG,
	KDATAN_TL_RET_QUEUE_CHANNEL,
	KDATAN_TL_SUBMIT_QUEUE,
	KDATAN_TL_NEW_WAIT_IRQ,
	KDATAN_JD_UPDATE_JIT_MEMORY,
	KDATAN_TL_DUMP_FW,
	KDATAN_TL_WAIT_CMD_DONE,
	KDATAN_JD_DUMP_FCP_PT,
	KDATAN_JD_DUMP_PT,
	KDATAN_JD_DUMP_CD,
	KDATAN_JD_DUMP_CMDQ,
	KDATAN_SET_PTR,
	KDATAN_SET_GET_INDEX,
	KDATAN_SET_PUT_IDX,

	JOBTRACE_OBJ_CNT
};

enum jobtrace_local_msg_id {
	KDATAN_TL_LOCAL_CHK_SOFTQ,

	JOBTRACE_LOCAL_MSG_CNT
};

enum kdatan_cq_irq_status_type {
	KDATAN_JOBTRACE_IRQ_SVD_STATUS = 0,
	KDATAN_JOBTRACE_IRQ_STOP_STATUS,
	KDATAN_JOBTRACE_IRQ_NOTIFY_STATUS,
	KDATAN_JOBTRACE_IRQ_TIMEOUT_STATUS,
	KDATAN_JOBTRACE_IRQ_SIGNAL_RENDER_STATUS,
	KDATAN_JOBTRACE_IRQ_SIGNAL_BINNING_STATUS,
	KDATAN_JOBTRACE_IRQ_SIGNAL_COMPUTE_STATUS,
	KDATAN_JOBTRACE_IRQ_SIGNAL_BVH_STATUS,
	KDATAN_JOBTRACE_IRQ_SIGNAL_RT_STATUS,
	KDATAN_JOBTRACE_IRQ_SUBQ0_STATUS,
	KDATAN_JOBTRACE_IRQ_SUBQ1_STATUS,
	KDATAN_JOBTRACE_IRQ_SUBQ2_STATUS,
	KDATAN_JOBTRACE_IRQ_SUBQ3_STATUS,
	KDATAN_JOBTRACE_IRQ_SUBQ4_STATUS,
	KDATAN_JOBTRACE_IRQ_SUBQ5_STATUS,
	KDATAN_JOBTRACE_IRQ_SUBQ6_STATUS,
	KDATAN_JOBTRACE_IRQ_SUBQ7_STATUS,
	KDATAN_JOBTRACE_IRQ_BOUNDARY_STATUS,
};
#endif

