ccflags-y += -Wextra -Wdate-time -Wfloat-equal -Wshadow -Wformat=2

PM_DIR :=$(srctree)/platform_source/cee/drivers/pm

EXTRA_CFLAGS += -I$(PM_DIR)
EXTRA_CFLAGS += -I$(srctree)/drivers/huawei_platform/inputhub/default

obj-y += test_sr.o
