# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_FB_KERNEL_LOGO) += fb_kernel_logo.o
obj-$(CONFIG_FB_KERNEL_LOGO) += res_flash/light_spot_res.o
obj-$(CONFIG_FB_KERNEL_LOGO) += res_word_chn/word_chn_res.o
obj-$(CONFIG_FB_KERNEL_LOGO) += res_word_eng/word_eng_res.o