obj-$(CONFIG_HW_STAT) += hw_stat.o
obj-$(CONFIG_HW_STAT_FAULT) += fault_stat/
obj-$(CONFIG_HW_STAT_IOSTAT) += hw_iostat/
obj-$(CONFIG_HW_STAT_PSI) += psi/
obj-$(CONFIG_HW_STAT_BLK_INFO) += blk_info/
obj-$(CONFIG_HW_STAT_TRACING_MARK_WRITE) += hw_stat_tracing_mark_write.o
obj-$(CONFIG_HW_STAT_PHYMEM) += phymem/
